# -*- coding: utf-8 -*-
# Dati notizia nd-af — Afghanistan: mandati CPI per persecuzione di genere (8 lug 2025)
# 4 sezioni: la terza ("Non è la religione, è potere") è il blocco al-Azhar/OCI, in evidenza.
import html as _html

_ICC   = "https://www.icc-cpi.int/news/situation-afghanistan-icc-pre-trial-chamber-ii-issues-arrest-warrants-haibatullah-akhundzada"
_UNNEWS= "https://www.ohchr.org/en/press-releases/2025/07/afghanistan-un-experts-welcome-arrest-warrants-senior-taliban-leaders"
_AJ    = "https://www.aljazeera.com/news/2025/7/8/icc-arrest-warrants-for-taliban-leaders-over-alleged-persecution-of-women"
_F24   = "https://www.france24.com/en/asia-pacific/20250708-icc-issues-arrest-warrants-for-taliban-leaders-over-persecution-of-women"
_AZHAR = "https://english.ahram.org.eg/NewsContent/1/1234/483095/Egypt/Foreign-Affairs/AlAzhar-grand-imam-calls-on-Taliban-to-reconsider-.aspx"
_OIC   = "https://www.voanews.com/a/muslim-countries-blast-taliban-for-university-ban-for-afghan-women/6887860.html"

_FT = {'it':'Fonti','en':'Sources','fr':'Sources','de':'Quellen','es':'Fuentes','pt':'Fontes',
       'tr':'Kaynaklar','zh':'来源','ar':'المصادر','he':'מקורות','ru':'Источники'}
def _a(url,label): return '<a href="%s" target="_blank" rel="noopener noreferrer">%s</a>'%(url,_html.escape(label))
LANGS=['it','en','fr','de','es','pt','tr','zh','ar','he','ru']
_AZL={'it':'al-Azhar','en':'al-Azhar','fr':'al-Azhar','de':'al-Azhar','es':'al-Azhar','pt':'al-Azhar','tr':'el-Ezher','zh':'爱资哈尔','ar':'الأزهر','he':'אל-אזהר','ru':'аль-Азхар'}
SRC={}
for _l in LANGS:
    SRC[_l]='%s: %s · %s · %s · %s · %s · %s'%(_FT[_l], _a(_ICC,'ICC'), _a(_UNNEWS,'OHCHR'), _a(_AJ,'Al Jazeera'), _a(_F24,'France 24'), _a(_AZHAR,_AZL[_l]), _a(_OIC,'OIC'))

DATE = {'it':'Giugno 2026','en':'June 2026','fr':'Juin 2026','de':'Juni 2026','es':'Junio de 2026',
        'pt':'Junho de 2026','tr':'Haziran 2026','zh':'2026年6月','ar':'يونيو 2026','he':'יוני 2026','ru':'Июнь 2026'}
SHARE = {'it':'Condividi','en':'Share','fr':'Partager','de':'Teilen','es':'Compartir','pt':'Partilhar',
         'tr':'Paylaş','zh':'分享','ar':'مشاركة','he':'שיתוף','ru':'Поделиться'}
READ  = {'it':"Leggi l'analisi",'en':'Read the analysis','fr':"Lire l'analyse",'de':'Analyse lesen',
         'es':'Leer el análisis','pt':'Ler a análise','tr':'Analizi oku','zh':'阅读分析',
         'ar':'اقرأ التحليل','he':'קראו את הניתוח','ru':'Читать анализ'}
FLAB  = dict(_FT)
LABELS = {
 'it':['Il fatto','Commento giuridico','Non è la religione, è potere','Implicazioni'],
 'en':['The fact','Legal commentary','Not religion, but power','Implications'],
 'fr':['Le fait','Commentaire juridique','Non la religion, mais le pouvoir','Implications'],
 'de':['Der Sachverhalt','Rechtlicher Kommentar','Nicht Religion, sondern Macht','Konsequenzen'],
 'es':['El hecho','Comentario jurídico','No es la religión, es poder','Implicaciones'],
 'pt':['O facto','Comentário jurídico','Não é a religião, é poder','Implicações'],
 'tr':['Olgu','Hukuki yorum','Din değil, iktidar','Sonuçlar'],
 'zh':['事实','法律评注','不是宗教，而是权力','影响'],
 'ar':['الواقعة','تعليق قانوني','ليس الدين، بل السلطة','التبعات'],
 'he':['העובדה','פרשנות משפטית','לא הדת, אלא הכוח','השלכות'],
 'ru':['Факт','Правовой комментарий','Не религия, а власть','Последствия'],
}
AF = {}

AF['it'] = {
 'title':"Afghanistan: la Corte Penale Internazionale accusa i vertici talebani di persecuzione di genere",
 'quote':"«Equivale a un apartheid di genere.» — Richard Bennett, Relatore speciale ONU per l'Afghanistan",
 'labels':LABELS['it'],
 'bodies':[
  "L'8 luglio 2025 la Camera preliminare II della Corte Penale Internazionale ha emesso mandati d'arresto contro il leader supremo dei talebani, Haibatullah Akhundzada, e il capo della giustizia, Abdul Hakim Haqqani, per il crimine contro l'umanità di persecuzione su basi di genere (art. 7, par. 1, lett. h dello Statuto di Roma). Secondo i giudici, dalla presa del potere il 15 agosto 2021 i talebani hanno privato sistematicamente donne e ragazze — con decreti ed editti — dei diritti all'istruzione, al movimento, all'espressione, alla vita privata e familiare, e hanno colpito anche chi non si conformava alla loro politica di genere e chi era percepito come «alleato di donne e ragazze». Le ragazze sono escluse dall'istruzione oltre la primaria; alle donne è vietata gran parte del lavoro e il movimento senza un tutore maschile. I mandati restano secretati, ma la Corte ne ha reso pubblica l'esistenza perché la condotta è in corso e la conoscenza può contribuire a prevenirla. I talebani hanno respinto la decisione come «annunci senza senso» e dichiarato di non riconoscere la Corte.",
  "La Camera ha fissato un punto che allarga la portata del diritto: la persecuzione di genere non è solo violenza diretta, ma anche il danno istituzionalizzato, cioè l'imposizione di norme sociali discriminatorie. È la prima volta che la Corte contesta la persecuzione di genere come crimine contro l'umanità. Il quadro dei diritti negati chiama in causa anche la Convenzione sui diritti dell'infanzia (l'istruzione delle bambine) e la Convenzione sull'eliminazione di ogni forma di discriminazione contro le donne, che l'Afghanistan ha ratificato nel 2003. Il Relatore speciale ONU Richard Bennett ha definito l'effetto cumulativo delle restrizioni equivalente a un apartheid di genere — ma qui va tenuta la distinzione: l'apartheid di genere non è (ancora) un crimine dello Statuto di Roma, e proprio per questo la Corte ha usato la fattispecie più vicina disponibile, la persecuzione; donne afghane e giuristi ne chiedono la codificazione. E i mandati sono al livello dei «motivi ragionevoli», non una condanna.",
  "Va detto con nettezza, perché disinnesca la lettura più comune — «è la loro religione». Le misure talebane sono state condannate come contrarie alla sharia dal Grande Imam di al-Azhar, la massima autorità del sunnismo, che ha ricordato l'obbligo per uomini e donne di cercare la conoscenza «dalla culla alla tomba»; l'Organizzazione per la Cooperazione Islamica ne ha chiesto la revoca, e condanne sono giunte da Arabia Saudita, Emirati, Qatar, Turchia e Pakistan. Il dato decisivo: l'Afghanistan è l'unico Paese al mondo — musulmano o no — a vietare l'istruzione secondaria alle ragazze. Un caso isolato non prova una regola su quasi due miliardi di fedeli. Per questo gli organi terzi non giudicano una religione, ma una struttura di potere: la Corte non contesta un'eresia, contesta la persecuzione come crimine contro l'umanità; il Relatore ONU parla di apartheid di genere — una struttura di dominio, non una fede.",
  "È di nuovo il divario tra il diritto scritto e la sua applicazione. I mandati esistono, la Corte ha parlato, ma Akhundzada e Haqqani restano al potere e i talebani non riconoscono L'Aia: come già per i mandati su al-Bashir o su Netanyahu e Gallant, l'atto giudiziario da solo non arresta nessuno. Il criterio, però, è indipendente dall'identità: la persecuzione di genere è un crimine chiunque la commetta, e lo stesso standard interroga ogni regime che sottometta le donne, non solo quello di Kabul. Gli esperti ONU lo traducono in un monito: nessuna normalizzazione di un regime che nega i diritti fondamentali a più di metà della popolazione. Voltarsi, qui, significa lasciare che l'esclusione di metà di un popolo diventi una normalità che nessuno contesta. Il diritto vale per tutti, o non vale per nessuno.",
 ]}

AF['en'] = {
 'title':"Afghanistan: the International Criminal Court charges the Taliban leadership with gender persecution",
 'quote':"“It amounts to gender apartheid.” — Richard Bennett, UN Special Rapporteur on Afghanistan",
 'labels':LABELS['en'],
 'bodies':[
  "On 8 July 2025 Pre-Trial Chamber II of the International Criminal Court issued arrest warrants against the Taliban's supreme leader, Haibatullah Akhundzada, and its chief justice, Abdul Hakim Haqqani, for the crime against humanity of persecution on gender grounds (article 7(1)(h) of the Rome Statute). According to the judges, since seizing power on 15 August 2021 the Taliban have systematically deprived women and girls — through decrees and edicts — of the rights to education, movement, expression, and private and family life, and have also targeted those who did not conform to their gender policy and those perceived as “allies of women and girls.” Girls are barred from education beyond the primary level; women are banned from most work and from movement without a male guardian. The warrants remain under seal, but the Court disclosed their existence because the conduct is ongoing and awareness may help prevent it. The Taliban rejected the decision as “nonsense” and declared they do not recognise the Court.",
  "The Chamber set a point that widens the reach of the law: gender persecution is not only direct violence, but also institutionalised harm — the imposition of discriminatory social norms. It is the first time the Court has charged gender persecution as a crime against humanity. The framework of denied rights also engages the Convention on the Rights of the Child (girls' education) and the Convention on the Elimination of All Forms of Discrimination against Women, which Afghanistan ratified in 2003. UN Special Rapporteur Richard Bennett has called the cumulative effect of the restrictions tantamount to gender apartheid — but a distinction must be kept here: gender apartheid is not (yet) a crime under the Rome Statute, which is precisely why the Court used the closest available category, persecution; Afghan women and jurists are campaigning for its codification. And the warrants are at the level of “reasonable grounds,” not a conviction.",
  "It must be said plainly, because it defuses the most common reading — “it's their religion.” The Taliban measures were condemned as contrary to sharia by the Grand Imam of al-Azhar, the highest authority of Sunni Islam, who recalled the obligation for men and women to seek knowledge “from the cradle to the grave”; the Organisation of Islamic Cooperation called for their reversal, and condemnations came from Saudi Arabia, the Emirates, Qatar, Turkey and Pakistan. The decisive fact: Afghanistan is the only country in the world — Muslim or not — to ban secondary education for girls. A single case does not prove a rule about nearly two billion believers. This is why third-party bodies do not judge a religion, but a power structure: the Court does not charge a heresy, it charges persecution as a crime against humanity; the UN Rapporteur speaks of gender apartheid — a structure of domination, not a faith.",
  "It is again the gap between the written law and its application. The warrants exist, the Court has spoken, but Akhundzada and Haqqani remain in power and the Taliban do not recognise The Hague: as with the warrants for al-Bashir or for Netanyahu and Gallant, the judicial act alone arrests no one. The criterion, though, is independent of identity: gender persecution is a crime whoever commits it, and the same standard questions every regime that subjugates women, not only the one in Kabul. UN experts translate it into a warning: no normalisation of a regime that denies fundamental rights to more than half its population. To look away here is to let the exclusion of half a people become a normality no one contests. The law applies to everyone, or it applies to no one.",
 ]}

AF['fr'] = {
 'title':"Afghanistan : la Cour pénale internationale accuse les dirigeants talibans de persécution de genre",
 'quote':"« Cela équivaut à un apartheid de genre. » — Richard Bennett, Rapporteur spécial de l'ONU pour l'Afghanistan",
 'labels':LABELS['fr'],
 'bodies':[
  "Le 8 juillet 2025, la Chambre préliminaire II de la Cour pénale internationale a émis des mandats d'arrêt contre le chef suprême des talibans, Haibatullah Akhundzada, et le chef de la justice, Abdul Hakim Haqqani, pour le crime contre l'humanité de persécution fondée sur le genre (article 7-1-h du Statut de Rome). Selon les juges, depuis la prise du pouvoir le 15 août 2021, les talibans ont systématiquement privé femmes et filles — par décrets et édits — des droits à l'éducation, au mouvement, à l'expression, à la vie privée et familiale, et ont aussi visé ceux qui ne se conformaient pas à leur politique de genre et ceux perçus comme « alliés des femmes et des filles ». Les filles sont exclues de l'éducation au-delà du primaire ; le travail et le déplacement sans tuteur masculin sont largement interdits aux femmes. Les mandats restent scellés, mais la Cour en a révélé l'existence car la conduite est en cours et sa connaissance peut aider à la prévenir. Les talibans ont rejeté la décision comme « absurde » et déclaré ne pas reconnaître la Cour.",
  "La Chambre a posé un point qui élargit la portée du droit : la persécution de genre n'est pas seulement la violence directe, mais aussi le préjudice institutionnalisé — l'imposition de normes sociales discriminatoires. C'est la première fois que la Cour retient la persécution de genre comme crime contre l'humanité. Le cadre des droits niés met aussi en jeu la Convention relative aux droits de l'enfant (l'éducation des filles) et la Convention sur l'élimination de toutes les formes de discrimination à l'égard des femmes, que l'Afghanistan a ratifiée en 2003. Le Rapporteur spécial de l'ONU Richard Bennett a qualifié l'effet cumulé des restrictions d'équivalent à un apartheid de genre — mais il faut ici maintenir la distinction : l'apartheid de genre n'est pas (encore) un crime du Statut de Rome, et c'est pourquoi la Cour a utilisé la qualification la plus proche disponible, la persécution ; des Afghanes et des juristes en réclament la codification. Et les mandats sont au niveau des « motifs raisonnables », non d'une condamnation.",
  "Il faut le dire nettement, car cela désamorce la lecture la plus courante — « c'est leur religion ». Les mesures talibanes ont été condamnées comme contraires à la charia par le Grand Imam d'al-Azhar, la plus haute autorité du sunnisme, qui a rappelé l'obligation pour les hommes et les femmes de chercher le savoir « du berceau à la tombe » ; l'Organisation de la coopération islamique en a demandé la révocation, et des condamnations sont venues d'Arabie saoudite, des Émirats, du Qatar, de Turquie et du Pakistan. Le fait décisif : l'Afghanistan est le seul pays au monde — musulman ou non — à interdire l'éducation secondaire aux filles. Un cas isolé ne prouve pas une règle sur près de deux milliards de croyants. C'est pourquoi les organes tiers ne jugent pas une religion, mais une structure de pouvoir : la Cour ne retient pas une hérésie, elle retient la persécution comme crime contre l'humanité ; le Rapporteur de l'ONU parle d'apartheid de genre — une structure de domination, non une foi.",
  "C'est de nouveau l'écart entre le droit écrit et son application. Les mandats existent, la Cour a parlé, mais Akhundzada et Haqqani restent au pouvoir et les talibans ne reconnaissent pas La Haye : comme pour les mandats contre al-Bachir ou contre Netanyahou et Gallant, l'acte judiciaire seul n'arrête personne. Le critère, pourtant, est indépendant de l'identité : la persécution de genre est un crime quel qu'en soit l'auteur, et le même standard interroge tout régime qui soumet les femmes, pas seulement celui de Kaboul. Les experts de l'ONU en font un avertissement : aucune normalisation d'un régime qui nie les droits fondamentaux à plus de la moitié de sa population. Détourner le regard, ici, c'est laisser l'exclusion de la moitié d'un peuple devenir une normalité que nul ne conteste. Le droit vaut pour tous, ou il ne vaut pour personne.",
 ]}

AF['de'] = {
 'title':"Afghanistan: Der Internationale Strafgerichtshof beschuldigt die Taliban-Führung der Geschlechterverfolgung",
 'quote':"„Es kommt einer Geschlechter-Apartheid gleich.“ — Richard Bennett, UN-Sonderberichterstatter für Afghanistan",
 'labels':LABELS['de'],
 'bodies':[
  "Am 8. Juli 2025 erließ die Vorverfahrenskammer II des Internationalen Strafgerichtshofs Haftbefehle gegen den obersten Führer der Taliban, Haibatullah Akhundzada, und den Obersten Richter, Abdul Hakim Haqqani, wegen des Verbrechens gegen die Menschlichkeit der Verfolgung aus Gründen des Geschlechts (Artikel 7 Absatz 1 Buchstabe h des Römischen Statuts). Nach Auffassung der Richter haben die Taliban seit der Machtübernahme am 15. August 2021 Frauen und Mädchen durch Dekrete und Erlasse systematisch der Rechte auf Bildung, Bewegung, Meinungsäußerung sowie Privat- und Familienleben beraubt und auch jene ins Visier genommen, die sich ihrer Geschlechterpolitik nicht fügten oder als „Verbündete von Frauen und Mädchen“ galten. Mädchen ist Bildung über die Grundstufe hinaus verwehrt; Frauen sind von den meisten Tätigkeiten und von Bewegung ohne männlichen Vormund ausgeschlossen. Die Haftbefehle bleiben versiegelt, doch der Gerichtshof machte ihre Existenz öffentlich, weil das Verhalten andauert und Bewusstsein zur Verhütung beitragen kann. Die Taliban wiesen die Entscheidung als „Unsinn“ zurück und erklärten, den Gerichtshof nicht anzuerkennen.",
  "Die Kammer setzte einen Punkt, der die Reichweite des Rechts erweitert: Geschlechterverfolgung ist nicht nur direkte Gewalt, sondern auch institutionalisierter Schaden — die Auferlegung diskriminierender gesellschaftlicher Normen. Es ist das erste Mal, dass der Gerichtshof Geschlechterverfolgung als Verbrechen gegen die Menschlichkeit anklagt. Der Rahmen der verweigerten Rechte berührt auch das Übereinkommen über die Rechte des Kindes (Bildung der Mädchen) und das Übereinkommen zur Beseitigung jeder Form von Diskriminierung der Frau, das Afghanistan 2003 ratifiziert hat. Der UN-Sonderberichterstatter Richard Bennett nannte die kumulative Wirkung der Beschränkungen einer Geschlechter-Apartheid gleichkommend — doch hier ist die Unterscheidung zu wahren: Geschlechter-Apartheid ist (noch) kein Verbrechen des Römischen Statuts, weshalb der Gerichtshof die nächstliegende verfügbare Kategorie nutzte, die Verfolgung; afghanische Frauen und Juristen fordern ihre Kodifizierung. Und die Haftbefehle sind auf der Ebene „hinreichender Gründe“, keine Verurteilung.",
  "Es muss klar gesagt werden, denn es entkräftet die häufigste Lesart — „es ist ihre Religion“. Die Taliban-Maßnahmen wurden vom Großimam von al-Azhar, der höchsten Autorität des sunnitischen Islam, als der Scharia widersprechend verurteilt; er erinnerte an die Pflicht für Männer und Frauen, Wissen „von der Wiege bis zur Bahre“ zu suchen. Die Organisation für Islamische Zusammenarbeit forderte ihre Rücknahme, und Verurteilungen kamen aus Saudi-Arabien, den Emiraten, Katar, der Türkei und Pakistan. Die entscheidende Tatsache: Afghanistan ist das einzige Land der Welt — muslimisch oder nicht —, das Mädchen die weiterführende Bildung verbietet. Ein Einzelfall beweist keine Regel über fast zwei Milliarden Gläubige. Deshalb beurteilen Dritte keine Religion, sondern eine Machtstruktur: der Gerichtshof klagt keine Häresie an, sondern Verfolgung als Verbrechen gegen die Menschlichkeit; der UN-Berichterstatter spricht von Geschlechter-Apartheid — eine Herrschaftsstruktur, kein Glaube.",
  "Es ist erneut die Kluft zwischen geschriebenem Recht und seiner Anwendung. Die Haftbefehle bestehen, der Gerichtshof hat gesprochen, doch Akhundzada und Haqqani bleiben an der Macht und die Taliban erkennen Den Haag nicht an: wie bei den Haftbefehlen gegen al-Bashir oder gegen Netanyahu und Gallant verhaftet der Rechtsakt allein niemanden. Das Kriterium aber ist unabhängig von der Identität: Geschlechterverfolgung ist ein Verbrechen, wer sie auch begeht, und derselbe Maßstab befragt jedes Regime, das Frauen unterwirft, nicht nur das in Kabul. UN-Experten machen daraus eine Warnung: keine Normalisierung eines Regimes, das mehr als der Hälfte seiner Bevölkerung Grundrechte verweigert. Wegzusehen heißt hier, die Ausgrenzung der Hälfte eines Volkes zu einer Normalität werden zu lassen, die niemand bestreitet. Das Recht gilt für alle, oder es gilt für niemanden.",
 ]}

AF['es'] = {
 'title':"Afganistán: la Corte Penal Internacional acusa a la cúpula talibán de persecución de género",
 'quote':"«Equivale a un apartheid de género.» — Richard Bennett, Relator especial de la ONU para Afganistán",
 'labels':LABELS['es'],
 'bodies':[
  "El 8 de julio de 2025 la Sala de Cuestiones Preliminares II de la Corte Penal Internacional emitió órdenes de arresto contra el líder supremo de los talibanes, Haibatullah Akhundzada, y el jefe de la justicia, Abdul Hakim Haqqani, por el crimen de lesa humanidad de persecución por motivos de género (artículo 7.1.h del Estatuto de Roma). Según los jueces, desde la toma del poder el 15 de agosto de 2021 los talibanes han privado sistemáticamente a mujeres y niñas — mediante decretos y edictos — de los derechos a la educación, al movimiento, a la expresión y a la vida privada y familiar, y también han atacado a quienes no se ajustaban a su política de género y a quienes eran percibidos como «aliados de las mujeres y las niñas». Las niñas quedan excluidas de la educación más allá de la primaria; a las mujeres se les prohíbe gran parte del trabajo y el movimiento sin tutor masculino. Las órdenes permanecen bajo sello, pero la Corte reveló su existencia porque la conducta continúa y su conocimiento puede ayudar a prevenirla. Los talibanes rechazaron la decisión como «sinsentido» y declararon no reconocer a la Corte.",
  "La Sala fijó un punto que amplía el alcance del derecho: la persecución de género no es solo violencia directa, sino también el daño institucionalizado — la imposición de normas sociales discriminatorias. Es la primera vez que la Corte imputa la persecución de género como crimen de lesa humanidad. El marco de los derechos negados invoca también la Convención sobre los Derechos del Niño (la educación de las niñas) y la Convención sobre la eliminación de todas las formas de discriminación contra la mujer, que Afganistán ratificó en 2003. El Relator especial de la ONU Richard Bennett calificó el efecto acumulado de las restricciones como equivalente a un apartheid de género — pero aquí debe mantenerse la distinción: el apartheid de género no es (todavía) un crimen del Estatuto de Roma, y por eso la Corte usó la figura más cercana disponible, la persecución; mujeres afganas y juristas piden su codificación. Y las órdenes están en el nivel de «motivos razonables», no de una condena.",
  "Hay que decirlo con nitidez, porque desactiva la lectura más común — «es su religión». Las medidas talibanas fueron condenadas como contrarias a la sharia por el Gran Imam de al-Azhar, la máxima autoridad del sunismo, que recordó la obligación de hombres y mujeres de buscar el conocimiento «de la cuna a la tumba»; la Organización para la Cooperación Islámica pidió su revocación, y llegaron condenas de Arabia Saudí, los Emiratos, Catar, Turquía y Pakistán. El dato decisivo: Afganistán es el único país del mundo — musulmán o no — que prohíbe la educación secundaria a las niñas. Un caso aislado no prueba una regla sobre casi dos mil millones de creyentes. Por eso los órganos terceros no juzgan una religión, sino una estructura de poder: la Corte no imputa una herejía, imputa la persecución como crimen de lesa humanidad; el Relator de la ONU habla de apartheid de género — una estructura de dominación, no una fe.",
  "Es de nuevo la brecha entre el derecho escrito y su aplicación. Las órdenes existen, la Corte ha hablado, pero Akhundzada y Haqqani siguen en el poder y los talibanes no reconocen La Haya: como con las órdenes contra al-Bashir o contra Netanyahu y Gallant, el acto judicial por sí solo no arresta a nadie. El criterio, sin embargo, es independiente de la identidad: la persecución de género es un crimen quienquiera que la cometa, y el mismo estándar interroga a todo régimen que someta a las mujeres, no solo al de Kabul. Los expertos de la ONU lo traducen en una advertencia: ninguna normalización de un régimen que niega los derechos fundamentales a más de la mitad de su población. Voltear la mirada, aquí, es dejar que la exclusión de la mitad de un pueblo se vuelva una normalidad que nadie cuestiona. El derecho vale para todos, o no vale para nadie.",
 ]}

AF['pt'] = {
 'title':"Afeganistão: o Tribunal Penal Internacional acusa a cúpula talibã de perseguição de género",
 'quote':"«Equivale a um apartheid de género.» — Richard Bennett, Relator especial da ONU para o Afeganistão",
 'labels':LABELS['pt'],
 'bodies':[
  "Em 8 de julho de 2025 a Câmara de Instrução II do Tribunal Penal Internacional emitiu mandados de detenção contra o líder supremo dos talibãs, Haibatullah Akhundzada, e o chefe da justiça, Abdul Hakim Haqqani, pelo crime contra a humanidade de perseguição com base no género (artigo 7.º, n.º 1, alínea h, do Estatuto de Roma). Segundo os juízes, desde a tomada do poder em 15 de agosto de 2021 os talibãs privaram sistematicamente mulheres e raparigas — por decretos e éditos — dos direitos à educação, ao movimento, à expressão e à vida privada e familiar, e visaram também quem não se conformava com a sua política de género e quem era visto como «aliado das mulheres e raparigas». As raparigas estão excluídas do ensino além do primário; às mulheres é vedada grande parte do trabalho e o movimento sem tutor masculino. Os mandados permanecem selados, mas o Tribunal revelou a sua existência porque a conduta está em curso e o conhecimento pode ajudar a preveni-la. Os talibãs rejeitaram a decisão como «disparate» e declararam não reconhecer o Tribunal.",
  "A Câmara fixou um ponto que alarga o alcance do direito: a perseguição de género não é apenas violência direta, mas também o dano institucionalizado — a imposição de normas sociais discriminatórias. É a primeira vez que o Tribunal imputa a perseguição de género como crime contra a humanidade. O quadro dos direitos negados convoca também a Convenção sobre os Direitos da Criança (a educação das raparigas) e a Convenção sobre a Eliminação de Todas as Formas de Discriminação contra as Mulheres, que o Afeganistão ratificou em 2003. O Relator especial da ONU Richard Bennett qualificou o efeito cumulativo das restrições como equivalente a um apartheid de género — mas aqui deve manter-se a distinção: o apartheid de género não é (ainda) um crime do Estatuto de Roma, e por isso o Tribunal usou a figura mais próxima disponível, a perseguição; mulheres afegãs e juristas pedem a sua codificação. E os mandados estão no nível dos «motivos razoáveis», não de uma condenação.",
  "Há que dizê-lo com nitidez, porque desarma a leitura mais comum — «é a religião deles». As medidas talibãs foram condenadas como contrárias à sharia pelo Grão-Imã de al-Azhar, a máxima autoridade do sunismo, que recordou a obrigação de homens e mulheres de buscar o conhecimento «do berço ao túmulo»; a Organização para a Cooperação Islâmica pediu a sua revogação, e condenações vieram da Arábia Saudita, dos Emirados, do Catar, da Turquia e do Paquistão. O dado decisivo: o Afeganistão é o único país do mundo — muçulmano ou não — a proibir o ensino secundário às raparigas. Um caso isolado não prova uma regra sobre quase dois mil milhões de crentes. Por isso os órgãos terceiros não julgam uma religião, mas uma estrutura de poder: o Tribunal não imputa uma heresia, imputa a perseguição como crime contra a humanidade; o Relator da ONU fala de apartheid de género — uma estrutura de domínio, não uma fé.",
  "É de novo o fosso entre o direito escrito e a sua aplicação. Os mandados existem, o Tribunal falou, mas Akhundzada e Haqqani continuam no poder e os talibãs não reconhecem Haia: como nos mandados contra al-Bashir ou contra Netanyahu e Gallant, o ato judicial por si só não detém ninguém. O critério, porém, é independente da identidade: a perseguição de género é um crime seja quem for a cometê-la, e o mesmo padrão interroga todo regime que submeta as mulheres, não só o de Cabul. Os peritos da ONU traduzem-no num aviso: nenhuma normalização de um regime que nega os direitos fundamentais a mais de metade da sua população. Voltar o olhar, aqui, é deixar que a exclusão de metade de um povo se torne uma normalidade que ninguém contesta. O direito vale para todos, ou não vale para ninguém.",
 ]}

AF['tr'] = {
 'title':"Afganistan: Uluslararası Ceza Mahkemesi, Taliban liderliğini cinsiyet temelli zulümle suçluyor",
 'quote':"«Bu bir cinsiyet apartheid'ine denk düşüyor.» — Richard Bennett, BM Afganistan Özel Raportörü",
 'labels':LABELS['tr'],
 'bodies':[
  "8 Temmuz 2025'te Uluslararası Ceza Mahkemesi'nin II. Ön Yargılama Dairesi, Taliban'ın yüksek lideri Haibatullah Akhundzada ve baş yargıç Abdul Hakim Haqqani hakkında, cinsiyet temelli zulüm insanlığa karşı suçundan (Roma Statüsü'nün 7(1)(h) maddesi) tutuklama emirleri çıkardı. Yargıçlara göre, 15 Ağustos 2021'de iktidarı ele geçirmelerinden bu yana Taliban, kararname ve fermanlarla kadınları ve kızları eğitim, hareket, ifade, özel ve aile yaşamı haklarından sistematik olarak yoksun bıraktı; cinsiyet politikalarına uymayanları ve «kadın ve kızların müttefiki» görülenleri de hedef aldı. Kızlar ilkokul sonrası eğitimden dışlanıyor; kadınlara işin büyük kısmı ve erkek vasi olmadan hareket yasak. Emirler mühürlü kalıyor, ancak Mahkeme, davranış sürdüğü ve farkındalığın önlemeye yardımcı olabileceği için varlıklarını açıkladı. Taliban kararı «saçmalık» diye reddetti ve Mahkeme'yi tanımadığını bildirdi.",
  "Daire, hukukun kapsamını genişleten bir noktayı belirledi: cinsiyet temelli zulüm yalnızca doğrudan şiddet değil, aynı zamanda kurumsallaşmış zarardır — ayrımcı toplumsal normların dayatılması. Mahkeme'nin cinsiyet temelli zulmü insanlığa karşı suç olarak ilk kez suçlamasıdır. İnkâr edilen haklar çerçevesi ayrıca Çocuk Haklarına Dair Sözleşme'yi (kızların eğitimi) ve Afganistan'ın 2003'te onayladığı Kadınlara Karşı Her Türlü Ayrımcılığın Önlenmesi Sözleşmesi'ni çağırır. BM Özel Raportörü Richard Bennett kısıtlamaların kümülatif etkisini bir cinsiyet apartheid'ine denk saydı — ama burada ayrım korunmalı: cinsiyet apartheid'i (henüz) Roma Statüsü'nün bir suçu değil, Mahkeme de bu yüzden mevcut en yakın nitelendirmeyi, zulmü kullandı; Afgan kadınları ve hukukçular kodifikasyonunu istiyor. Ve emirler «makul gerekçeler» düzeyinde, bir mahkûmiyet değil.",
  "Bunu açıkça söylemek gerek, çünkü en yaygın okumayı — «bu onların dini» — etkisiz kılar. Taliban önlemleri, sünniliğin en yüksek otoritesi el-Ezher Büyük İmamı tarafından şeriata aykırı olarak kınandı; kadın ve erkeğin bilgiyi «beşikten mezara» arama yükümlülüğünü hatırlattı. İslam İşbirliği Teşkilatı geri alınmasını istedi; Suudi Arabistan, Emirlikler, Katar, Türkiye ve Pakistan'dan kınamalar geldi. Belirleyici olgu: Afganistan, dünyada — Müslüman olsun olmasın — kızlara ortaöğretimi yasaklayan tek ülke. Tek bir vaka, yaklaşık iki milyar inanan hakkında bir kural kanıtlamaz. Bu yüzden üçüncü taraf organlar bir dini değil, bir iktidar yapısını yargılar: Mahkeme bir sapkınlığı değil, insanlığa karşı suç olarak zulmü suçlar; BM Raportörü cinsiyet apartheid'inden söz eder — bir egemenlik yapısı, bir inanç değil.",
  "Yine yazılı hukuk ile uygulaması arasındaki uçurum. Emirler var, Mahkeme konuştu, ama Akhundzada ve Haqqani iktidarda kalıyor ve Taliban Lahey'i tanımıyor: al-Beşir ya da Netanyahu ve Gallant hakkındaki emirlerde olduğu gibi, yargısal işlem tek başına kimseyi tutuklamaz. Ölçüt ise kimlikten bağımsızdır: cinsiyet temelli zulüm, kim işlerse işlesin bir suçtur ve aynı standart, yalnızca Kabil'dekini değil, kadınları boyunduruk altına alan her rejimi sorgular. BM uzmanları bunu bir uyarıya çevirir: nüfusunun yarısından fazlasına temel hakları reddeden bir rejimin normalleştirilmemesi. Burada başını çevirmek, bir halkın yarısının dışlanmasının kimsenin itiraz etmediği bir olağanlığa dönüşmesine izin vermektir. Hukuk herkes için geçerlidir ya da hiç kimse için.",
 ]}

AF['zh'] = {
 'title':"阿富汗：国际刑事法院指控塔利班高层犯有性别迫害罪",
 'quote':"“这等同于性别隔离。” —— 联合国阿富汗问题特别报告员理查德·班尼特",
 'labels':LABELS['zh'],
 'bodies':[
  "2025年7月8日，国际刑事法院第二预审分庭对塔利班最高领导人海巴图拉·阿洪扎达和首席大法官阿卜杜勒·哈基姆·哈卡尼签发逮捕令，指控其犯有基于性别的迫害这一危害人类罪（《罗马规约》第7条第1款第(h)项）。法官认为，自2021年8月15日夺权以来，塔利班以法令和敕令系统性地剥夺了妇女和女童受教育、行动、表达以及私人和家庭生活的权利，并打击不服从其性别政策者和被视为“妇女与女童的盟友”者。女童被排除在小学之后的教育之外；妇女被禁止从事大部分工作、并被禁止在没有男性监护人陪同下出行。逮捕令仍处于密封状态，但法院公开了其存在，因为相关行为仍在持续，公众知情有助于预防。塔利班将该决定斥为“无稽之谈”，并声明不承认该法院。",
  "分庭确立了一个拓展法律范围的要点：性别迫害不仅是直接暴力，也包括制度化的伤害——即强加歧视性的社会规范。这是法院首次将性别迫害作为危害人类罪加以指控。被剥夺权利的框架还牵涉《儿童权利公约》（女童教育）以及阿富汗于2003年批准的《消除对妇女一切形式歧视公约》。联合国特别报告员理查德·班尼特称这些限制的累积效应等同于性别隔离——但此处须保持区分：性别隔离（尚）不是《罗马规约》下的罪行，正因如此法院使用了现有最接近的罪名，即迫害；阿富汗妇女与法律人士正推动将其入罪。而逮捕令处于“合理理由”的层级，并非定罪。",
  "这一点必须讲明，因为它拆解了最常见的说法——“这是他们的宗教”。塔利班的措施被逊尼派最高权威机构爱资哈尔的大伊玛目谴责为违背沙里亚，他重申男女都负有“从摇篮到坟墓”求知的义务；伊斯兰合作组织要求撤销，沙特、阿联酋、卡塔尔、土耳其和巴基斯坦也发出谴责。决定性的事实是：阿富汗是全世界——无论是否穆斯林国家——唯一禁止女童接受中等教育的国家。孤例无法证明关于近二十亿信众的规律。正因如此，第三方机构审视的不是一种宗教，而是一种权力结构：法院指控的不是异端，而是作为危害人类罪的迫害；联合国报告员谈的是性别隔离——一种支配结构，而非一种信仰。",
  "这又一次是成文法与其适用之间的落差。逮捕令存在，法院已发声，但阿洪扎达和哈卡尼仍然当权，塔利班不承认海牙：正如针对巴希尔或针对内塔尼亚胡和加兰特的逮捕令一样，司法行为本身逮捕不了任何人。然而标准与身份无关：性别迫害无论由谁实施都是犯罪，同样的标准也拷问每一个压制妇女的政权，而不仅仅是喀布尔的政权。联合国专家将其化为一句警告：不得将一个否认其半数以上人口基本权利的政权正常化。在此转过头去，就是任由半数人口被排斥成为无人质疑的常态。法律要么对所有人适用，要么对任何人都不适用。",
 ]}

AF['ar'] = {
 'title':"أفغانستان: المحكمة الجنائية الدولية تتهم قيادة طالبان بالاضطهاد على أساس الجنس",
 'quote':"«إنه يرقى إلى فصل عنصري قائم على الجنس.» — ريتشارد بينيت، المقرر الأممي الخاص بأفغانستان",
 'labels':LABELS['ar'],
 'bodies':[
  "في 8 يوليو 2025 أصدرت الدائرة التمهيدية الثانية للمحكمة الجنائية الدولية مذكّرتَي توقيف بحق زعيم طالبان الأعلى هيبة الله أخوندزاده ورئيس القضاء عبد الحكيم حقاني، بتهمة الاضطهاد على أساس الجنس بوصفه جريمة ضد الإنسانية (المادة 7(1)(ح) من نظام روما الأساسي). وبحسب القضاة، فمنذ استيلائها على السلطة في 15 أغسطس 2021، حرمت طالبان النساء والفتيات منهجياً — بمراسيم وأوامر — من الحق في التعليم والتنقّل والتعبير والحياة الخاصة والأسرية، واستهدفت أيضاً من لم يمتثل لسياستها الجندرية ومن اعتُبر «حليفاً للنساء والفتيات». تُستبعَد الفتيات من التعليم بعد المرحلة الابتدائية؛ وتُمنَع النساء من معظم العمل ومن التنقّل دون محرم. تبقى المذكّرتان مختومتين، لكن المحكمة كشفت عن وجودهما لأن السلوك مستمر ولأن المعرفة قد تسهم في منعه. رفضت طالبان القرار ووصفته بأنه «كلام فارغ»، وأعلنت أنها لا تعترف بالمحكمة.",
  "أرست الدائرة نقطة توسّع نطاق القانون: الاضطهاد على أساس الجنس ليس عنفاً مباشراً فحسب، بل أيضاً ضرراً ممأسَساً — أي فرض معايير اجتماعية تمييزية. وهي المرة الأولى التي تلاحق فيها المحكمة الاضطهاد الجندري بوصفه جريمة ضد الإنسانية. ويستدعي إطار الحقوق المسلوبة أيضاً اتفاقية حقوق الطفل (تعليم الفتيات) واتفاقية القضاء على جميع أشكال التمييز ضد المرأة، التي صدّقت عليها أفغانستان عام 2003. ووصف المقرر الأممي الخاص ريتشارد بينيت الأثر التراكمي للقيود بأنه يرقى إلى فصل عنصري قائم على الجنس — لكن يجب هنا الإبقاء على التمييز: الفصل العنصري الجندري ليس (بعد) جريمة في نظام روما الأساسي، ولذلك استخدمت المحكمة أقرب توصيف متاح، وهو الاضطهاد؛ وتطالب أفغانيات وحقوقيون بتقنينه. والمذكّرتان في مستوى «الأسباب المعقولة»، لا إدانة.",
  "لا بدّ من قول هذا بوضوح، لأنه يفكّك القراءة الأكثر شيوعاً — «إنه دينهم». فقد أدان التدابير باعتبارها مخالفة للشريعة شيخُ الأزهر، أعلى مرجعية في السنّة، مذكّراً بواجب طلب العلم للرجال والنساء «من المهد إلى اللحد»؛ وطالبت منظمة التعاون الإسلامي بإلغائها، وجاءت إدانات من السعودية والإمارات وقطر وتركيا وباكستان. والحقيقة الحاسمة: أفغانستان هي البلد الوحيد في العالم — مسلماً كان أم لا — الذي يمنع التعليم الثانوي عن الفتيات. حالة منفردة لا تثبت قاعدة على نحو ملياري مؤمن تقريباً. لذلك لا تحاكم الهيئات المحايدة ديناً، بل بنية سلطة: المحكمة لا تلاحق هرطقة، بل تلاحق الاضطهاد بوصفه جريمة ضد الإنسانية؛ والمقرر الأممي يتحدث عن فصل عنصري جندري — بنية هيمنة، لا عقيدة.",
  "إنها من جديد الفجوة بين القانون المكتوب وتطبيقه. المذكّرتان قائمتان، والمحكمة تكلّمت، لكن أخوندزاده وحقاني ما زالا في السلطة وطالبان لا تعترف بلاهاي: كما في مذكّرات البشير أو نتنياهو وغالانت، لا يعتقل الإجراء القضائي وحده أحداً. غير أن المعيار مستقل عن الهوية: الاضطهاد الجندري جريمة أياً كان مرتكبه، والمعيار نفسه يسائل كل نظام يُخضِع النساء، لا نظام كابول وحده. ويحوّله خبراء الأمم المتحدة إلى تحذير: لا تطبيع لنظام ينكر الحقوق الأساسية لأكثر من نصف سكانه. أن تشيح بوجهك هنا يعني أن تدع إقصاء نصف شعب يصير أمراً عادياً لا يعترض عليه أحد. القانون يسري على الجميع، أو لا يسري على أحد.",
 ]}

AF['he'] = {
 'title':"אפגניסטן: בית הדין הפלילי הבינלאומי מאשים את הנהגת הטליבאן ברדיפה מגדרית",
 'quote':"»זה עולה כדי אפרטהייד מגדרי.« — ריצ'רד בנט, הדווח המיוחד של האו״ם לאפגניסטן",
 'labels':LABELS['he'],
 'bodies':[
  "ב-8 ביולי 2025 הוציאה לשכת קדם-המשפט II של בית הדין הפלילי הבינלאומי צווי מעצר נגד מנהיג הטליבאן העליון הייבתאללה אחונדזאדה ונגד השופט הראשי עבד אל-חכים חקאני, בגין הפשע נגד האנושות של רדיפה על רקע מגדרי (סעיף 7(1)(ח) לחוקת רומא). לפי השופטים, מאז תפיסת השלטון ב-15 באוגוסט 2021 שללו הטליבאן באופן שיטתי מנשים ונערות — בצווים ובגזירות — את הזכויות לחינוך, לתנועה, לביטוי ולחיים פרטיים ומשפחתיים, ופגעו גם במי שלא הלמו את מדיניות המגדר שלהם ובמי שנתפסו כ»בני ברית של נשים ונערות«. נערות מודרות מחינוך מעבר ליסודי; לנשים אסורים רוב סוגי העבודה והתנועה ללא אפוטרופוס גבר. הצווים נותרים חתומים, אך בית הדין חשף את קיומם משום שההתנהלות נמשכת והמודעות עשויה לסייע במניעתה. הטליבאן דחו את ההחלטה כ»שטויות« והצהירו שאינם מכירים בבית הדין.",
  "הלשכה קבעה נקודה שמרחיבה את תחולת הדין: רדיפה מגדרית אינה רק אלימות ישירה, אלא גם נזק ממוסד — כפיית נורמות חברתיות מפלות. זו הפעם הראשונה שבית הדין מייחס רדיפה מגדרית כפשע נגד האנושות. מסגרת הזכויות הנשללות מערבת גם את האמנה בדבר זכויות הילד (חינוך הנערות) ואת האמנה לביטול כל צורות האפליה נגד נשים, שאפגניסטן אשררה ב-2003. הדווח המיוחד של האו״ם ריצ'רד בנט כינה את ההשפעה המצטברת של ההגבלות כשקולה לאפרטהייד מגדרי — אך כאן יש לשמור על ההבחנה: אפרטהייד מגדרי אינו (עדיין) פשע לפי חוקת רומא, ולכן בית הדין השתמש בהגדרה הקרובה ביותר הזמינה, הרדיפה; נשים אפגניות ומשפטנים פועלים לעיגונו כפשע. והצווים הם ברמת «יסוד סביר», לא הרשעה.",
  "צריך לומר זאת בבירור, כי הדבר מפרק את הקריאה הרווחת — «זו הדת שלהם». צעדי הטליבאן גונו כמנוגדים לשריעה בידי האימאם הגדול של אל-אזהר, הסמכות העליונה של האסלאם הסוני, שהזכיר את חובת הגברים והנשים לבקש ידע «מהעריסה עד הקבר«; ארגון שיתוף הפעולה האסלאמי דרש את ביטולם, וגינויים הגיעו מסעודיה, מאיחוד האמירויות, מקטר, מטורקיה ומפקיסטן. העובדה המכרעת: אפגניסטן היא המדינה היחידה בעולם — מוסלמית או לא — האוסרת חינוך תיכוני על נערות. מקרה יחיד אינו מוכיח כלל על כמעט שני מיליארד מאמינים. משום כך גופים שלישיים אינם שופטים דת, אלא מבנה כוח: בית הדין אינו מייחס כפירה, אלא רדיפה כפשע נגד האנושות; הדווח של האו״ם מדבר על אפרטהייד מגדרי — מבנה שליטה, לא אמונה.",
  "זהו שוב הפער בין הדין הכתוב ליישומו. הצווים קיימים, בית הדין דיבר, אך אחונדזאדה וחקאני נותרים בשלטון והטליבאן אינם מכירים בהאג: כמו בצווים נגד אל-בשיר או נגד נתניהו וגלנט, הפעולה השיפוטית לבדה אינה עוצרת איש. אך אמת המידה אינה תלויה בזהות: רדיפה מגדרית היא פשע מי שלא יבצע אותה, ואותו סטנדרט חוקר כל משטר המשעבד נשים, לא רק זה שבקאבול. מומחי האו״ם מתרגמים זאת לאזהרה: אין להכשיר משטר השולל זכויות יסוד מיותר ממחצית אוכלוסייתו. להפנות מבט כאן פירושו לתת להדרת מחצית מעם להפוך לנורמה שאיש אינו מערער עליה. הדין חל על הכול, או שאינו חל על איש.",
 ]}

AF['ru'] = {
 'title':"Афганистан: Международный уголовный суд обвиняет руководство талибов в гендерном преследовании",
 'quote':"«Это равнозначно гендерному апартеиду.» — Ричард Беннетт, спецдокладчик ООН по Афганистану",
 'labels':LABELS['ru'],
 'bodies':[
  "8 июля 2025 года Палата предварительного производства II Международного уголовного суда выдала ордера на арест верховного лидера талибов Хайбатуллы Ахундзады и главного судьи Абдул Хакима Хаккани по обвинению в преступлении против человечности в форме преследования по гендерному признаку (статья 7(1)(h) Римского статута). По мнению судей, с захвата власти 15 августа 2021 года талибы систематически лишали женщин и девочек — указами и эдиктами — прав на образование, передвижение, выражение мнений, частную и семейную жизнь, а также преследовали тех, кто не подчинялся их гендерной политике, и тех, кого считали «союзниками женщин и девочек». Девочки отстранены от образования сверх начального; женщинам запрещена большая часть работы и передвижение без сопровождающего мужчины. Ордера остаются под грифом секретности, но Суд обнародовал их существование, поскольку деяние продолжается и осведомлённость может способствовать его предотвращению. Талибы отвергли решение как «чепуху» и заявили, что не признают Суд.",
  "Палата закрепила положение, расширяющее охват права: гендерное преследование — это не только прямое насилие, но и институционализированный вред, то есть навязывание дискриминационных социальных норм. Суд впервые вменяет гендерное преследование как преступление против человечности. Рамка отобранных прав затрагивает также Конвенцию о правах ребёнка (образование девочек) и Конвенцию о ликвидации всех форм дискриминации в отношении женщин, которую Афганистан ратифицировал в 2003 году. Спецдокладчик ООН Ричард Беннетт назвал совокупный эффект ограничений равнозначным гендерному апартеиду — но здесь следует сохранять различие: гендерный апартеид (пока) не является преступлением по Римскому статуту, и именно поэтому Суд использовал ближайшую доступную квалификацию — преследование; афганские женщины и юристы добиваются его кодификации. А ордера — на уровне «разумных оснований», а не приговора.",
  "Это нужно сказать прямо, потому что это обезоруживает самое расхожее прочтение — «это их религия». Меры талибов были осуждены как противоречащие шариату Великим имамом аль-Азхара, высшим авторитетом суннизма, напомнившим об обязанности мужчин и женщин искать знание «от колыбели до могилы»; Организация исламского сотрудничества призвала их отменить, а осуждения прозвучали из Саудовской Аравии, Эмиратов, Катара, Турции и Пакистана. Решающий факт: Афганистан — единственная страна в мире (мусульманская или нет), запрещающая девочкам среднее образование. Единичный случай не доказывает правила о почти двух миллиардах верующих. Поэтому сторонние органы судят не религию, а структуру власти: Суд вменяет не ересь, а преследование как преступление против человечности; докладчик ООН говорит о гендерном апартеиде — структуре господства, а не о вере.",
  "Это снова разрыв между писаным правом и его применением. Ордера есть, Суд высказался, но Ахундзада и Хаккани остаются у власти, а талибы не признают Гаагу: как и с ордерами на аль-Башира или на Нетаньяху и Галанта, один лишь судебный акт никого не арестует. Однако критерий не зависит от личности: гендерное преследование — преступление, кто бы его ни совершал, и тот же стандарт спрашивает с любого режима, подчиняющего женщин, а не только с кабульского. Эксперты ООН переводят это в предупреждение: никакой нормализации режима, отказывающего более чем половине населения в основных правах. Отвернуться здесь — значит позволить исключению половины народа стать нормой, которую никто не оспаривает. Право действует для всех или ни для кого.",
 ]}

TAGS = ['Afghanistan','Donne','Corte penale internazionale','Diritto internazionale','Crisi dimenticate']
