# -*- coding: utf-8 -*-
# Dati notizia nd-ht — Haiti: forza di soppressione ONU/USA contro gang per metà minorenni
# Schema identico a sd.py/mya.py. REGOLA DI FERRO: fonti reali; due dati sensibili ATTRIBUITI.

import html as _html

_UNNEWS = "https://news.un.org/en/story/2026/01/1166801"
_SCR    = "https://www.securitycouncilreport.org/monthly-forecast/2026-04/haiti-34.php"
_IRC    = "https://www.rescue.org/article/haitis-gang-violence-crisis-what-know-and-how-help"
_UNICEF = "https://www.unicef.org/press-releases/violence-drives-haitis-children-armed-groups-half-all-members-are-now-children"

_FT = {'it':'Fonti','en':'Sources','fr':'Sources','de':'Quellen','es':'Fuentes','pt':'Fontes',
       'tr':'Kaynaklar','zh':'来源','ar':'المصادر','he':'מקורות','ru':'Источники'}
def _a(url,label):
    return '<a href="%s" target="_blank" rel="noopener noreferrer">%s</a>'%(url,_html.escape(label))

LANGS=['it','en','fr','de','es','pt','tr','zh','ar','he','ru']
SRC={}
for _l in LANGS:
    SRC[_l]='%s: %s · %s · %s · %s'%(_FT[_l], _a(_UNNEWS,'UN News'), _a(_SCR,'Security Council Report'), _a(_IRC,'IRC'), _a(_UNICEF,'UNICEF'))

DATE = {'it':'Giugno 2026','en':'June 2026','fr':'Juin 2026','de':'Juni 2026','es':'Junio de 2026',
        'pt':'Junho de 2026','tr':'Haziran 2026','zh':'2026年6月','ar':'يونيو 2026','he':'יוני 2026','ru':'Июнь 2026'}
SHARE = {'it':'Condividi','en':'Share','fr':'Partager','de':'Teilen','es':'Compartir','pt':'Partilhar',
         'tr':'Paylaş','zh':'分享','ar':'مشاركة','he':'שיתוף','ru':'Поделиться'}
READ  = {'it':"Leggi l'analisi",'en':'Read the analysis','fr':"Lire l'analyse",'de':'Analyse lesen',
         'es':'Leer el análisis','pt':'Ler a análise','tr':'Analizi oku','zh':'阅读分析',
         'ar':'اقرأ التحليل','he':'קראו את הניתוח','ru':'Читать анализ'}
FLAB  = dict(_FT)
LABELS = {
 'it':['Il fatto','Commento giuridico','Implicazioni'],'en':['The fact','Legal commentary','Implications'],
 'fr':['Le fait','Commentaire juridique','Implications'],'de':['Der Sachverhalt','Rechtlicher Kommentar','Konsequenzen'],
 'es':['El hecho','Comentario jurídico','Implicaciones'],'pt':['O facto','Comentário jurídico','Implicações'],
 'tr':['Olgu','Hukuki yorum','Sonuçlar'],'zh':['事实','法律评注','影响'],
 'ar':['الواقعة','تعليق قانوني','التبعات'],'he':['העובדה','פרשנות משפטית','השלכות'],
 'ru':['Факт','Правовой комментарий','Последствия'],
}

HT = {}

# ===================== IT =====================
HT['it'] = {
 'title':"Haiti: una «forza di soppressione» autorizzata dall'ONU contro gang fatte per metà di bambini",
 'quote':"«La sola applicazione della sicurezza non basterà a risolvere i problemi di governance.» — António Guterres, Segretario generale dell'ONU",
 'labels':LABELS['it'],
 'bodies':[
  "Il 30 settembre 2025 il Consiglio di Sicurezza dell'ONU ha adottato la risoluzione 2793, trasformando la missione multinazionale di sostegno alla sicurezza (MSS, a guida keniana, autorizzata nel 2023 dalla risoluzione 2699) in una «Gang Suppression Force» da un massimo di 5.550 uomini, con il mandato di condurre «operazioni anti-gang per neutralizzare, isolare e scoraggiare» le bande. È una forza autorizzata dall'ONU ma non un'operazione ONU; gli Stati Uniti ne sono stati i principali artefici, e Cina, Russia e Pakistan si sono astenuti per dubbi su regole d'ingaggio, finanziamento, supervisione e responsabilità. I primi contingenti dal Ciad sono attesi ad aprile 2026. Sul terreno, la coalizione di gang Viv Ansanm controlla fino al 90% di Port-au-Prince e si espande verso i dipartimenti di Artibonite e Centre. La crisi umanitaria è tra le più gravi e meno finanziate al mondo: 6,4 milioni di persone — oltre metà della popolazione, inclusi 2,8 milioni di bambini — hanno bisogno di assistenza, e più di un haitiano su dieci è sfollato; a fine 2025 la risposta umanitaria era coperta solo al 24%. Secondo l'ACLED, nel 2025 si contano oltre 4.500 morti, tra i bilanci più alti al mondo; gli omicidi volontari in Artibonite e Centre sono cresciuti del 210% tra gennaio e agosto 2025. Le morti per droni e raid aerei sono aumentate del 120% nel primo trimestre 2026: secondo l'IRC e Medici Senza Frontiere, le forze governative e la compagnia militare privata Vectus Global hanno condotto attacchi con droni in aree residenziali, con vittime civili.",
  "Qui il diritto si applica in tre direzioni. Verso le gang: il reclutamento e l'uso di minori nelle ostilità è vietato dal Protocollo opzionale alla Convenzione sui diritti dell'infanzia (2000), che lo qualifica come crimine di guerra, e gli abusi sui civili — omicidi, stupri, sequestri — violano la stessa Convenzione sui diritti dell'infanzia e i principi del diritto umanitario. Verso lo Stato haitiano: l'uso di droni in aree abitate mette alla prova il principio di distinzione e la protezione dei civili (IV Convenzione di Ginevra), e l'Alta Commissaria per i diritti umani ha definito «non necessario o sproporzionato» l'uso della forza, con operazioni che «potrebbero essere descritte come uccisioni mirate». Verso la forza autorizzata dall'ONU: la stessa risoluzione 2793 richiama il rispetto dei diritti umani e la protezione dei minori, ma — secondo fonti del Consiglio — diversi Stati hanno criticato una direttiva statunitense incentrata sull'«uccidere» i membri delle gang, in un Paese dove, secondo le stime dell'ONU e dell'UNICEF, dal 30 al 50% dei miliziani sono minori. Il regime sanzionatorio e l'embargo sulle armi (risoluzione 2653) hanno finora colpito pochissimi individui, mentre la maggior parte delle armi che alimentano le gang arriva dagli Stati Uniti.",
  "È il banco di prova della simmetria portato al limite: lo stesso standard va applicato a chi commette le violenze e a chi dichiara di venire a fermarle. Una forza battezzata «di soppressione», con una postura orientata all'uso letale della forza contro una popolazione armata composta per metà da minori, solleva una domanda che il diritto pone da sempre: un bambino con un fucile resta, sul piano giuridico, prima di tutto una vittima da proteggere e reintegrare, non un bersaglio — e la stessa UNICEF ricorda che i minori reclutati vanno trattati anzitutto come bambini. Eppure Haiti resta una delle crisi più dimenticate del pianeta, con la risposta umanitaria coperta a un quarto e la sofferenza fuori dai radar. Il diritto vale per chi spara e per chi dice di venire a riportare l'ordine, o non vale per nessuno.",
 ]}

# ===================== EN =====================
HT['en'] = {
 'title':"Haiti: a UN-authorized “suppression force” against gangs half made of children",
 'quote':"“Security enforcement alone will not be enough to resolve the governance problems.” — António Guterres, UN Secretary-General",
 'labels':LABELS['en'],
 'bodies':[
  "On 30 September 2025 the UN Security Council adopted resolution 2793, transforming the Multinational Security Support mission (MSS, Kenyan-led, authorized in 2023 by resolution 2699) into a “Gang Suppression Force” of up to 5,550 personnel, mandated to conduct “counter-gang operations to neutralize, isolate and deter” the gangs. It is a UN-authorized force but not a UN operation; the United States was its main architect, and China, Russia and Pakistan abstained over concerns about rules of engagement, funding, oversight and accountability. The first contingents from Chad are expected in April 2026. On the ground, the Viv Ansanm gang coalition controls up to 90% of Port-au-Prince and is expanding into the Artibonite and Centre departments. The humanitarian crisis is among the world's gravest and least-funded: 6.4 million people — over half the population, including 2.8 million children — need assistance, and more than one Haitian in ten is displaced; by the end of 2025 the humanitarian response was only 24% funded. According to ACLED, more than 4,500 people were killed in 2025, among the highest tolls in the world; intentional homicides in Artibonite and Centre rose 210% between January and August 2025. Deaths from drone and air strikes rose 120% in the first quarter of 2026: according to the IRC and Médecins Sans Frontières, government forces and the private military company Vectus Global carried out drone strikes in residential areas, with civilian casualties.",
  "Here the law applies in three directions. Towards the gangs: the recruitment and use of minors in hostilities is prohibited by the Optional Protocol to the Convention on the Rights of the Child (2000), which classifies it as a war crime, and abuses against civilians — killings, rapes, kidnappings — violate the Convention on the Rights of the Child itself and the principles of humanitarian law. Towards the Haitian State: the use of drones in inhabited areas tests the principle of distinction and the protection of civilians (Fourth Geneva Convention), and the High Commissioner for Human Rights has called the use of force “unnecessary or disproportionate,” with operations that “could be described as targeted killings.” Towards the UN-authorized force: resolution 2793 itself invokes respect for human rights and the protection of minors, but — according to Council sources — several States have criticized a US directive focused on “killing” gang members, in a country where, according to UN and UNICEF estimates, 30 to 50% of the fighters are minors. The sanctions regime and the arms embargo (resolution 2653) have so far hit very few individuals, while most of the weapons fuelling the gangs come from the United States.",
  "This is the symmetry test pushed to its limit: the same standard must apply to those who commit the violence and to those who claim to come to stop it. A force named “suppression,” with a posture oriented towards the lethal use of force against an armed population half composed of minors, raises a question the law has always posed: a child with a rifle remains, in legal terms, first of all a victim to be protected and reintegrated, not a target — and UNICEF itself recalls that recruited minors must be treated first as children. And yet Haiti remains one of the planet's most forgotten crises, its humanitarian response funded at a quarter and its suffering off the radar. The law applies to those who shoot and to those who say they come to restore order, or it applies to no one.",
 ]}

# ===================== FR =====================
HT['fr'] = {
 'title':"Haïti : une « force de suppression » autorisée par l'ONU contre des gangs faits pour moitié d'enfants",
 'quote':"« La seule application de la sécurité ne suffira pas à résoudre les problèmes de gouvernance. » — António Guterres, Secrétaire général de l'ONU",
 'labels':LABELS['fr'],
 'bodies':[
  "Le 30 septembre 2025, le Conseil de sécurité de l'ONU a adopté la résolution 2793, transformant la mission multinationale d'appui à la sécurité (MSS, dirigée par le Kenya, autorisée en 2023 par la résolution 2699) en une « Gang Suppression Force » d'au plus 5 550 hommes, chargée de mener des « opérations anti-gangs pour neutraliser, isoler et dissuader » les bandes. C'est une force autorisée par l'ONU mais non une opération de l'ONU ; les États-Unis en ont été les principaux artisans, et la Chine, la Russie et le Pakistan se sont abstenus, par doutes sur les règles d'engagement, le financement, la supervision et la responsabilité. Les premiers contingents du Tchad sont attendus en avril 2026. Sur le terrain, la coalition de gangs Viv Ansanm contrôle jusqu'à 90 % de Port-au-Prince et s'étend vers les départements de l'Artibonite et du Centre. La crise humanitaire est parmi les plus graves et les moins financées au monde : 6,4 millions de personnes — plus de la moitié de la population, dont 2,8 millions d'enfants — ont besoin d'assistance, et plus d'un Haïtien sur dix est déplacé ; fin 2025, la réponse humanitaire n'était financée qu'à 24 %. Selon l'ACLED, plus de 4 500 personnes ont été tuées en 2025, l'un des bilans les plus élevés au monde ; les homicides volontaires dans l'Artibonite et le Centre ont augmenté de 210 % entre janvier et août 2025. Les morts par drones et frappes aériennes ont bondi de 120 % au premier trimestre 2026 : selon l'IRC et Médecins Sans Frontières, les forces gouvernementales et la société militaire privée Vectus Global ont mené des frappes de drones dans des zones résidentielles, avec des victimes civiles.",
  "Ici le droit s'applique dans trois directions. Envers les gangs : le recrutement et l'emploi de mineurs dans les hostilités sont interdits par le Protocole facultatif à la Convention relative aux droits de l'enfant (2000), qui les qualifie de crime de guerre, et les abus contre les civils — meurtres, viols, enlèvements — violent la Convention relative aux droits de l'enfant elle-même et les principes du droit humanitaire. Envers l'État haïtien : l'emploi de drones en zones habitées met à l'épreuve le principe de distinction et la protection des civils (IVe Convention de Genève), et la Haute-Commissaire aux droits de l'homme a qualifié l'usage de la force de « non nécessaire ou disproportionné », avec des opérations qui « pourraient être décrites comme des exécutions ciblées ». Envers la force autorisée par l'ONU : la résolution 2793 elle-même invoque le respect des droits humains et la protection des mineurs, mais — selon des sources du Conseil — plusieurs États ont critiqué une directive américaine centrée sur le fait de « tuer » les membres des gangs, dans un pays où, selon les estimations de l'ONU et de l'UNICEF, 30 à 50 % des miliciens sont mineurs. Le régime de sanctions et l'embargo sur les armes (résolution 2653) n'ont jusqu'ici touché que très peu d'individus, tandis que la plupart des armes qui alimentent les gangs viennent des États-Unis.",
  "C'est le test de la symétrie poussé à sa limite : la même norme doit s'appliquer à ceux qui commettent les violences et à ceux qui disent venir les arrêter. Une force baptisée « de suppression », dotée d'une posture orientée vers l'usage létal de la force contre une population armée composée pour moitié de mineurs, soulève une question que le droit pose depuis toujours : un enfant avec un fusil demeure, en droit, avant tout une victime à protéger et à réintégrer, non une cible — et l'UNICEF elle-même rappelle que les mineurs recrutés doivent être traités d'abord comme des enfants. Et pourtant Haïti reste l'une des crises les plus oubliées de la planète, sa réponse humanitaire financée au quart et sa souffrance hors des radars. Le droit vaut pour ceux qui tirent et pour ceux qui disent venir rétablir l'ordre, ou il ne vaut pour personne.",
 ]}

# ===================== DE =====================
HT['de'] = {
 'title':"Haiti: eine von der UNO autorisierte „Unterdrückungstruppe“ gegen zur Hälfte aus Kindern bestehende Banden",
 'quote':"„Sicherheitsdurchsetzung allein wird nicht genügen, um die Regierungsprobleme zu lösen.“ — António Guterres, UN-Generalsekretär",
 'labels':LABELS['de'],
 'bodies':[
  "Am 30. September 2025 verabschiedete der UN-Sicherheitsrat die Resolution 2793 und wandelte die Multinationale Sicherheitsunterstützungsmission (MSS, unter kenianischer Führung, 2023 durch Resolution 2699 autorisiert) in eine „Gang Suppression Force“ von höchstens 5.550 Personen um, beauftragt mit „Anti-Banden-Operationen, um die Banden zu neutralisieren, zu isolieren und abzuschrecken“. Es ist eine von der UNO autorisierte Truppe, aber keine UN-Operation; die Vereinigten Staaten waren ihr Hauptarchitekt, und China, Russland und Pakistan enthielten sich wegen Bedenken zu Einsatzregeln, Finanzierung, Aufsicht und Rechenschaft. Die ersten Kontingente aus dem Tschad werden im April 2026 erwartet. Vor Ort kontrolliert die Bandenkoalition Viv Ansanm bis zu 90 % von Port-au-Prince und dehnt sich in die Departements Artibonite und Centre aus. Die humanitäre Krise gehört zu den schwersten und am wenigsten finanzierten der Welt: 6,4 Millionen Menschen — mehr als die Hälfte der Bevölkerung, darunter 2,8 Millionen Kinder — brauchen Hilfe, und mehr als jeder zehnte Haitianer ist vertrieben; Ende 2025 war die humanitäre Hilfe nur zu 24 % finanziert. Laut ACLED wurden 2025 mehr als 4.500 Menschen getötet, eine der höchsten Bilanzen weltweit; vorsätzliche Tötungen in Artibonite und Centre stiegen zwischen Januar und August 2025 um 210 %. Todesfälle durch Drohnen und Luftangriffe stiegen im ersten Quartal 2026 um 120 %: laut IRC und Ärzte ohne Grenzen führten Regierungskräfte und das private Militärunternehmen Vectus Global Drohnenangriffe in Wohngebieten durch, mit zivilen Opfern.",
  "Hier wirkt das Recht in drei Richtungen. Gegenüber den Banden: die Rekrutierung und der Einsatz Minderjähriger in Feindseligkeiten sind durch das Fakultativprotokoll zum Übereinkommen über die Rechte des Kindes (2000) verboten, das dies als Kriegsverbrechen einstuft, und Übergriffe auf Zivilisten — Tötungen, Vergewaltigungen, Entführungen — verletzen das Übereinkommen über die Rechte des Kindes selbst und die Grundsätze des humanitären Rechts. Gegenüber dem haitianischen Staat: der Einsatz von Drohnen in bewohnten Gebieten stellt den Unterscheidungsgrundsatz und den Schutz der Zivilbevölkerung auf die Probe (IV. Genfer Abkommen), und die Hochkommissarin für Menschenrechte nannte den Einsatz von Gewalt „unnötig oder unverhältnismäßig“, mit Operationen, die „als gezielte Tötungen beschrieben werden könnten“. Gegenüber der von der UNO autorisierten Truppe: die Resolution 2793 selbst beruft sich auf die Achtung der Menschenrechte und den Schutz Minderjähriger, doch — laut Ratsquellen — kritisierten mehrere Staaten eine US-Direktive, die auf das „Töten“ von Bandenmitgliedern ausgerichtet sei, in einem Land, in dem nach Schätzungen der UNO und von UNICEF 30 bis 50 % der Kämpfer Minderjährige sind. Das Sanktionsregime und das Waffenembargo (Resolution 2653) trafen bisher sehr wenige Einzelpersonen, während die meisten Waffen, die die Banden befeuern, aus den Vereinigten Staaten stammen.",
  "Es ist der bis an die Grenze getriebene Symmetrietest: derselbe Maßstab muss für die gelten, die die Gewalt ausüben, und für die, die zu ihrer Beendigung zu kommen behaupten. Eine Truppe namens „Unterdrückung“, mit einer auf den tödlichen Einsatz von Gewalt ausgerichteten Haltung gegen eine bewaffnete, zur Hälfte aus Minderjährigen bestehende Bevölkerung, wirft eine Frage auf, die das Recht seit jeher stellt: ein Kind mit einem Gewehr bleibt rechtlich vor allem ein Opfer, das zu schützen und wiedereinzugliedern ist, kein Ziel — und UNICEF selbst erinnert daran, dass rekrutierte Minderjährige zuerst als Kinder zu behandeln sind. Und doch bleibt Haiti eine der am meisten vergessenen Krisen des Planeten, seine humanitäre Hilfe zu einem Viertel finanziert und sein Leiden außerhalb des Radars. Das Recht gilt für die, die schießen, und für die, die sagen, sie kämen, um die Ordnung wiederherzustellen, oder es gilt für niemanden.",
 ]}

# ===================== ES =====================
HT['es'] = {
 'title':"Haití: una «fuerza de supresión» autorizada por la ONU contra pandillas formadas a medias por niños",
 'quote':"«La sola aplicación de la seguridad no bastará para resolver los problemas de gobernanza.» — António Guterres, Secretario General de la ONU",
 'labels':LABELS['es'],
 'bodies':[
  "El 30 de septiembre de 2025 el Consejo de Seguridad de la ONU adoptó la resolución 2793, transformando la Misión Multinacional de Apoyo a la Seguridad (MSS, liderada por Kenia, autorizada en 2023 por la resolución 2699) en una «Gang Suppression Force» de hasta 5.550 efectivos, con el mandato de realizar «operaciones antipandillas para neutralizar, aislar y disuadir» a las bandas. Es una fuerza autorizada por la ONU pero no una operación de la ONU; los Estados Unidos fueron su principal artífice, y China, Rusia y Pakistán se abstuvieron por dudas sobre reglas de enfrentamiento, financiación, supervisión y rendición de cuentas. Los primeros contingentes de Chad se esperan en abril de 2026. Sobre el terreno, la coalición de pandillas Viv Ansanm controla hasta el 90% de Puerto Príncipe y se expande hacia los departamentos de Artibonite y Centre. La crisis humanitaria está entre las más graves y menos financiadas del mundo: 6,4 millones de personas — más de la mitad de la población, incluidos 2,8 millones de niños — necesitan asistencia, y más de un haitiano de cada diez está desplazado; a finales de 2025 la respuesta humanitaria estaba financiada solo al 24%. Según ACLED, en 2025 hubo más de 4.500 muertos, uno de los balances más altos del mundo; los homicidios intencionales en Artibonite y Centre crecieron un 210% entre enero y agosto de 2025. Las muertes por drones y ataques aéreos aumentaron un 120% en el primer trimestre de 2026: según el IRC y Médicos Sin Fronteras, las fuerzas gubernamentales y la empresa militar privada Vectus Global realizaron ataques con drones en zonas residenciales, con víctimas civiles.",
  "Aquí el derecho se aplica en tres direcciones. Hacia las pandillas: el reclutamiento y el uso de menores en las hostilidades está prohibido por el Protocolo facultativo de la Convención sobre los Derechos del Niño (2000), que lo califica de crimen de guerra, y los abusos contra los civiles — homicidios, violaciones, secuestros — violan la propia Convención sobre los Derechos del Niño y los principios del derecho humanitario. Hacia el Estado haitiano: el uso de drones en zonas habitadas pone a prueba el principio de distinción y la protección de los civiles (IV Convenio de Ginebra), y la Alta Comisionada para los Derechos Humanos calificó el uso de la fuerza de «innecesario o desproporcionado», con operaciones que «podrían describirse como ejecuciones selectivas». Hacia la fuerza autorizada por la ONU: la propia resolución 2793 invoca el respeto de los derechos humanos y la protección de los menores, pero — según fuentes del Consejo — varios Estados criticaron una directiva estadounidense centrada en «matar» a los miembros de las pandillas, en un país donde, según estimaciones de la ONU y de UNICEF, entre el 30 y el 50% de los milicianos son menores. El régimen de sanciones y el embargo de armas (resolución 2653) han alcanzado hasta ahora a poquísimos individuos, mientras que la mayoría de las armas que alimentan a las pandillas provienen de los Estados Unidos.",
  "Es la prueba de la simetría llevada al límite: el mismo criterio debe aplicarse a quienes cometen las violencias y a quienes dicen venir a detenerlas. Una fuerza bautizada «de supresión», con una postura orientada al uso letal de la fuerza contra una población armada compuesta a medias por menores, plantea una pregunta que el derecho formula desde siempre: un niño con un fusil sigue siendo, jurídicamente, ante todo una víctima a proteger y reintegrar, no un blanco — y la propia UNICEF recuerda que los menores reclutados deben ser tratados primero como niños. Y, sin embargo, Haití sigue siendo una de las crisis más olvidadas del planeta, con su respuesta humanitaria financiada a un cuarto y su sufrimiento fuera del radar. El derecho vale para quien dispara y para quien dice venir a restablecer el orden, o no vale para nadie.",
 ]}

# ===================== PT =====================
HT['pt'] = {
 'title':"Haiti: uma «força de supressão» autorizada pela ONU contra gangues feitas metade por crianças",
 'quote':"«A simples aplicação da segurança não bastará para resolver os problemas de governação.» — António Guterres, Secretário-Geral da ONU",
 'labels':LABELS['pt'],
 'bodies':[
  "Em 30 de setembro de 2025 o Conselho de Segurança da ONU adotou a resolução 2793, transformando a Missão Multinacional de Apoio à Segurança (MSS, liderada pelo Quénia, autorizada em 2023 pela resolução 2699) numa «Gang Suppression Force» de até 5.550 efetivos, com o mandato de conduzir «operações antigangues para neutralizar, isolar e dissuadir» as gangues. É uma força autorizada pela ONU mas não uma operação da ONU; os Estados Unidos foram o seu principal artífice, e a China, a Rússia e o Paquistão abstiveram-se por dúvidas sobre regras de empenhamento, financiamento, supervisão e responsabilização. Os primeiros contingentes do Chade são esperados em abril de 2026. No terreno, a coligação de gangues Viv Ansanm controla até 90% de Porto Príncipe e expande-se para os departamentos de Artibonite e Centre. A crise humanitária está entre as mais graves e menos financiadas do mundo: 6,4 milhões de pessoas — mais de metade da população, incluindo 2,8 milhões de crianças — precisam de assistência, e mais de um haitiano em cada dez está deslocado; no fim de 2025 a resposta humanitária estava financiada apenas a 24%. Segundo a ACLED, em 2025 houve mais de 4.500 mortos, um dos balanços mais altos do mundo; os homicídios voluntários em Artibonite e Centre cresceram 210% entre janeiro e agosto de 2025. As mortes por drones e ataques aéreos aumentaram 120% no primeiro trimestre de 2026: segundo o IRC e os Médicos Sem Fronteiras, as forças governamentais e a empresa militar privada Vectus Global realizaram ataques com drones em zonas residenciais, com vítimas civis.",
  "Aqui o direito aplica-se em três direções. Para as gangues: o recrutamento e o uso de menores nas hostilidades é proibido pelo Protocolo facultativo à Convenção sobre os Direitos da Criança (2000), que o qualifica como crime de guerra, e os abusos contra os civis — homicídios, violações, sequestros — violam a própria Convenção sobre os Direitos da Criança e os princípios do direito humanitário. Para o Estado haitiano: o uso de drones em zonas habitadas põe à prova o princípio da distinção e a proteção dos civis (IV Convenção de Genebra), e a Alta-Comissária para os Direitos Humanos classificou o uso da força de «desnecessário ou desproporcionado», com operações que «poderiam ser descritas como execuções seletivas». Para a força autorizada pela ONU: a própria resolução 2793 invoca o respeito pelos direitos humanos e a proteção dos menores, mas — segundo fontes do Conselho — vários Estados criticaram uma diretiva norte-americana centrada em «matar» os membros das gangues, num país onde, segundo estimativas da ONU e da UNICEF, entre 30 e 50% dos milicianos são menores. O regime de sanções e o embargo de armas (resolução 2653) atingiram até agora pouquíssimos indivíduos, enquanto a maioria das armas que alimentam as gangues vem dos Estados Unidos.",
  "É o teste da simetria levado ao limite: o mesmo critério deve aplicar-se a quem comete as violências e a quem diz vir para as deter. Uma força batizada «de supressão», com uma postura orientada para o uso letal da força contra uma população armada composta metade por menores, levanta uma pergunta que o direito coloca desde sempre: uma criança com uma espingarda continua a ser, juridicamente, antes de mais uma vítima a proteger e reintegrar, não um alvo — e a própria UNICEF recorda que os menores recrutados devem ser tratados primeiro como crianças. E, no entanto, o Haiti continua a ser uma das crises mais esquecidas do planeta, com a sua resposta humanitária financiada a um quarto e o seu sofrimento fora do radar. O direito vale para quem dispara e para quem diz vir repor a ordem, ou não vale para ninguém.",
 ]}

# ===================== TR =====================
HT['tr'] = {
 'title':"Haiti: yarısı çocuklardan oluşan çetelere karşı BM'nin yetkilendirdiği bir «bastırma gücü»",
 'quote':"«Yalnızca güvenliğin uygulanması yönetişim sorunlarını çözmeye yetmeyecek.» — António Guterres, BM Genel Sekreteri",
 'labels':LABELS['tr'],
 'bodies':[
  "30 Eylül 2025'te BM Güvenlik Konseyi, 2793 sayılı kararı kabul ederek Çok Uluslu Güvenlik Destek misyonunu (MSS, Kenya liderliğinde, 2023'te 2699 sayılı kararla yetkilendirilmiş) en fazla 5.550 kişilik bir «Gang Suppression Force»a dönüştürdü; görevi çeteleri «etkisiz hâle getirmek, izole etmek ve caydırmak için çete karşıtı operasyonlar» yürütmek. Bu, BM'nin yetkilendirdiği ama bir BM operasyonu olmayan bir güç; başlıca mimarı ABD oldu ve Çin, Rusya ile Pakistan, angajman kuralları, finansman, denetim ve hesap verebilirlik konusundaki kuşkular nedeniyle çekimser kaldı. Çad'dan ilk birliklerin Nisan 2026'da gelmesi bekleniyor. Sahada, Viv Ansanm çete koalisyonu Port-au-Prince'in %90'ına kadarını denetliyor ve Artibonite ile Centre vilayetlerine yayılıyor. İnsani kriz, dünyanın en ağır ve en az finanse edilenlerinden biri: 6,4 milyon kişi — nüfusun yarısından fazlası, 2,8 milyon çocuk dâhil — yardıma muhtaç ve her on Haitili'den fazlası yerinden edilmiş; 2025 sonunda insani müdahale yalnızca %24 oranında finanse edilmişti. ACLED'e göre 2025'te 4.500'den fazla kişi öldürüldü, dünyadaki en yüksek bilançolardan biri; Artibonite ve Centre'de kasıtlı cinayetler Ocak-Ağustos 2025 arasında %210 arttı. İnsansız hava aracı ve hava saldırılarından kaynaklanan ölümler 2026'nın ilk çeyreğinde %120 arttı: IRC ve Sınır Tanımayan Doktorlar'a göre hükûmet güçleri ve özel askeri şirket Vectus Global yerleşim alanlarında insansız hava aracı saldırıları düzenledi ve sivil kayıplar oldu.",
  "Burada hukuk üç yöne işler. Çetelere karşı: çocukların çatışmalarda kullanılması ve devşirilmesi, bunu bir savaş suçu sayan Çocuk Haklarına Dair Sözleşme'ye Ek İhtiyari Protokol (2000) ile yasaktır; ve sivillere yönelik ihlaller — cinayetler, tecavüzler, kaçırmalar — Çocuk Haklarına Dair Sözleşme'nin kendisini ve insancıl hukuk ilkelerini ihlal eder. Haiti devletine karşı: meskûn alanlarda insansız hava aracı kullanımı, ayrım ilkesini ve sivillerin korunmasını sınar (IV. Cenevre Sözleşmesi); ve İnsan Hakları Yüksek Komiseri güç kullanımını «gereksiz ya da orantısız» olarak niteledi, bazı operasyonların «hedefli öldürmeler olarak tanımlanabileceğini» belirtti. BM'nin yetkilendirdiği güce karşı: 2793 sayılı kararın kendisi insan haklarına saygıyı ve çocukların korunmasını çağırır, ancak — Konsey kaynaklarına göre — çeşitli devletler, BM ve UNICEF tahminlerine göre milislerin %30 ila %50'sinin çocuk olduğu bir ülkede, çete üyelerini «öldürmeye» odaklanan bir ABD direktifini eleştirdi. Yaptırım rejimi ve silah ambargosu (2653 sayılı karar) şimdiye dek çok az kişiye dokundu; oysa çeteleri besleyen silahların çoğu ABD'den geliyor.",
  "Bu, sınırına kadar götürülen simetri sınavıdır: aynı ölçüt, şiddeti uygulayanlara da, onu durdurmaya geldiğini söyleyenlere de uygulanmalıdır. «Bastırma» adı verilen, yarısı çocuklardan oluşan silahlı bir nüfusa karşı ölümcül güç kullanımına yönelmiş bir güç, hukukun öteden beri sorduğu bir soruyu gündeme getirir: elinde tüfek olan bir çocuk, hukuken her şeyden önce korunması ve topluma kazandırılması gereken bir mağdur olarak kalır, bir hedef değil — ve UNICEF'in kendisi, devşirilen çocukların önce çocuk olarak muamele görmesi gerektiğini hatırlatır. Yine de Haiti gezegenin en unutulmuş krizlerinden biri olmayı sürdürüyor; insani müdahalesi dörtte bir oranında finanse ediliyor ve acısı radarın dışında. Hukuk, ateş edenler için de düzeni yeniden kurmaya geldiğini söyleyenler için de geçerlidir, ya da hiç kimse için.",
 ]}

# ===================== ZH =====================
HT['zh'] = {
 'title':"海地：联合国授权的“镇压部队”，对付半数由儿童组成的帮派",
 'quote':"“仅靠安全行动不足以解决治理问题。” —— 联合国秘书长安东尼奥·古特雷斯",
 'labels':LABELS['zh'],
 'bodies':[
  "2025年9月30日，联合国安理会通过第2793号决议，将多国安全支助特派团（MSS，由肯尼亚领导，2023年依第2699号决议获得授权）改组为一支最多5550人的“帮派镇压部队”（Gang Suppression Force），授权其开展“反帮派行动，以削弱、孤立并威慑”帮派。这是一支由联合国授权、却并非联合国行动的部队；美国是其主要设计者，中国、俄罗斯和巴基斯坦因对交战规则、资金、监督与问责的疑虑而投了弃权票。来自乍得的首批特遣队预计于2026年4月抵达。在当地，帮派联盟Viv Ansanm控制着太子港高达90%的地区，并向阿蒂博尼特省和中部省扩张。人道主义危机属于世界上最严重、资金最匮乏之列：640万人——超过半数人口，其中包括280万儿童——需要援助，每十名海地人中有一名以上流离失所；到2025年底，人道主义应对方案仅获得24%的资金。据ACLED称，2025年有逾4500人死亡，是全球最高的伤亡数字之一；阿蒂博尼特省和中部省的故意杀人在2025年1月至8月间上升了210%。无人机与空袭造成的死亡在2026年第一季度上升了120%：据IRC和无国界医生组织称，政府部队与私营军事公司Vectus Global在居民区实施了无人机打击，造成平民伤亡。",
  "在此，法律在三个方向上适用。对帮派：招募和使用未成年人参加敌对行动，为关于儿童卷入武装冲突问题的任择议定书（2000年）所禁止，该议定书将其定为战争罪；而对平民的侵害——杀戮、强奸、绑架——则违反了儿童权利公约本身以及人道法原则。对海地国家：在居民区使用无人机考验着区分原则与对平民的保护（日内瓦第四公约），人权事务高级专员将这种使用武力称为“不必要或不相称”，并指出一些行动“可被描述为定点清除”。对这支由联合国授权的部队：第2793号决议本身援引了尊重人权与保护未成年人，但是——据安理会消息人士称——多个国家批评了一项以“击毙”帮派成员为核心的美国指令，而据联合国和儿基会估计，在这个国家30%至50%的武装人员是未成年人。制裁制度与武器禁运（第2653号决议）迄今只触及极少数个人，而助长帮派的武器大多来自美国。",
  "这是被推向极限的对称性检验：同样的标准必须既适用于施暴者，也适用于那些声称前来制止暴力的人。一支被命名为“镇压”的部队，以对一支半数由未成年人组成的武装人口使用致命武力为取向，提出了一个法律历来都在追问的问题：一个手持步枪的孩子，在法律上首先仍是一个需要保护和重新融入社会的受害者，而非打击目标——儿基会本身也提醒，被招募的未成年人应首先被当作儿童对待。然而海地仍是地球上最被遗忘的危机之一，其人道主义应对仅获四分之一的资金，其苦难处于视线之外。法律要么既适用于开枪者，也适用于那些声称前来恢复秩序的人，要么对任何人都不适用。",
 ]}

# ===================== AR =====================
HT['ar'] = {
 'title':"هايتي: «قوة قمع» مفوّضة من الأمم المتحدة ضد عصابات نصفها من الأطفال",
 'quote':"«إنفاذ الأمن وحده لن يكفي لحل مشكلات الحوكمة.» — أنطونيو غوتيريش، الأمين العام للأمم المتحدة",
 'labels':LABELS['ar'],
 'bodies':[
  "في 30 سبتمبر 2025 اعتمد مجلس الأمن الدولي القرار 2793، محوّلاً بعثة الدعم الأمني المتعدد الجنسيات (MSS، بقيادة كينيا، المفوّضة عام 2023 بالقرار 2699) إلى «قوة قمع العصابات» (Gang Suppression Force) قوامها حتى 5550 فرداً، مكلَّفة بتنفيذ «عمليات لمكافحة العصابات من أجل تحييدها وعزلها وردعها». إنها قوة مفوّضة من الأمم المتحدة لكنها ليست عملية أممية؛ وكانت الولايات المتحدة مهندسها الرئيسي، فيما امتنعت الصين وروسيا وباكستان عن التصويت بسبب شكوك حول قواعد الاشتباك والتمويل والرقابة والمساءلة. ويُتوقع وصول أولى الوحدات من تشاد في أبريل 2026. ميدانياً، يسيطر تحالف عصابات «فيف أنسانم» على ما يصل إلى 90% من بورت أو برانس ويتمدّد نحو محافظتَي أرتيبونيت والوسط. والأزمة الإنسانية من بين الأشدّ خطورةً والأقلّ تمويلاً في العالم: 6.4 ملايين شخص — أكثر من نصف السكان، بينهم 2.8 مليون طفل — بحاجة إلى مساعدة، وأكثر من واحد من كل عشرة هايتيين نازح؛ وبنهاية 2025 لم تكن الاستجابة الإنسانية مموَّلة إلا بنسبة 24%. ووفق «أكليد» (ACLED)، قُتل أكثر من 4500 شخص عام 2025، وهي من أعلى الحصائل في العالم؛ وارتفعت جرائم القتل العمد في أرتيبونيت والوسط بنسبة 210% بين يناير وأغسطس 2025. وارتفعت الوفيات بالطائرات المسيّرة والغارات الجوية بنسبة 120% في الربع الأول من 2026: فبحسب «اللجنة الدولية للإنقاذ» وأطباء بلا حدود، نفّذت القوات الحكومية والشركة العسكرية الخاصة «فيكتوس غلوبال» ضربات بطائرات مسيّرة في مناطق سكنية، مع سقوط ضحايا مدنيين.",
  "هنا يسري القانون في ثلاثة اتجاهات. تجاه العصابات: تجنيد القُصّر واستخدامهم في الأعمال العدائية محظور بموجب البروتوكول الاختياري لاتفاقية حقوق الطفل (2000) الذي يصنّفه جريمة حرب؛ والانتهاكات بحق المدنيين — قتل واغتصاب واختطاف — تنتهك اتفاقية حقوق الطفل نفسها ومبادئ القانون الإنساني. تجاه الدولة الهايتية: استخدام الطائرات المسيّرة في المناطق المأهولة يضع مبدأ التمييز وحماية المدنيين على المحك (اتفاقية جنيف الرابعة)، وقد وصفت المفوّضة السامية لحقوق الإنسان استخدام القوة بأنه «غير ضروري أو غير متناسب»، مع عمليات «يمكن وصفها بأنها عمليات قتل مستهدَف». تجاه القوة المفوّضة من الأمم المتحدة: القرار 2793 نفسه يستحضر احترام حقوق الإنسان وحماية القُصّر، لكن — بحسب مصادر في المجلس — انتقدت عدة دول توجيهاً أميركياً يتمحور حول «قتل» أفراد العصابات، في بلد تُقدِّر الأمم المتحدة واليونيسف أن 30 إلى 50% من مقاتليه قُصّر. ولم يطل نظام العقوبات وحظر الأسلحة (القرار 2653) سوى أفراد قلائل جداً حتى الآن، في حين أن معظم الأسلحة التي تغذّي العصابات تأتي من الولايات المتحدة.",
  "إنه اختبار التماثل مدفوعاً إلى أقصاه: المعيار نفسه يجب أن يسري على من يرتكبون العنف وعلى من يقولون إنهم جاؤوا لوقفه. إن قوة تحمل اسم «القمع»، بنزعة موجَّهة نحو الاستخدام المميت للقوة ضد سكان مسلحين نصفهم من القُصّر، تطرح سؤالاً ما انفكّ القانون يطرحه: الطفل الحامل لبندقية يظلّ، قانوناً، قبل كل شيء ضحيةً ينبغي حمايتها وإعادة إدماجها، لا هدفاً — واليونيسف نفسها تذكّر بأن القُصّر المجنَّدين يجب أن يُعامَلوا أولاً بوصفهم أطفالاً. ومع ذلك تظل هايتي من أكثر الأزمات نسياناً على الكوكب، استجابتها الإنسانية مموَّلة بالربع ومعاناتها خارج الرادار. القانون يسري على من يطلق النار وعلى من يقول إنه جاء لإعادة النظام، أو لا يسري على أحد.",
 ]}

# ===================== HE =====================
HT['he'] = {
 'title':"האיטי: »כוח דיכוי« בהרשאת האו״ם נגד כנופיות שמחציתן ילדים",
 'quote':"»אכיפת ביטחון לבדה לא תספיק כדי לפתור את בעיות הממשל.« — אנטוניו גוטרש, מזכ״ל האו״ם",
 'labels':LABELS['he'],
 'bodies':[
  "ב-30 בספטמבר 2025 אימצה מועצת הביטחון של האו״ם את החלטה 2793, והפכה את משלחת התמיכה הביטחונית הרב-לאומית (MSS, בהובלת קניה, שהורשתה ב-2023 בהחלטה 2699) ל»כוח דיכוי כנופיות« (Gang Suppression Force) של עד 5,550 אנשים, שתפקידו לנהל »מבצעים נגד כנופיות כדי לנטרל, לבודד ולהרתיע« אותן. זהו כוח בהרשאת האו״ם אך לא מבצע של האו״ם; ארצות הברית הייתה האדריכלית המרכזית שלו, וסין, רוסיה ופקיסטן נמנעו בשל ספקות באשר לכללי המעורבות, המימון, הפיקוח והאחריותיות. הפלוגות הראשונות מצ׳אד צפויות באפריל 2026. בשטח, קואליציית הכנופיות Viv Ansanm שולטת בעד 90% מפורט-או-פראנס ומתפשטת אל מחוזות ארטיבוניט והמרכז. המשבר ההומניטרי הוא מן החמורים והממומנים פחות בעולם: 6.4 מיליון בני אדם — יותר ממחצית האוכלוסייה, ובהם 2.8 מיליון ילדים — זקוקים לסיוע, ויותר מאחד מכל עשרה האיטים עקור; בסוף 2025 המענה ההומניטרי מומן ב-24% בלבד. לפי ACLED, ב-2025 נהרגו יותר מ-4,500 בני אדם, מן המספרים הגבוהים בעולם; מקרי הרצח המכוון בארטיבוניט ובמרכז עלו ב-210% בין ינואר לאוגוסט 2025. מקרי המוות מכטב״מים ומתקיפות אוויר עלו ב-120% ברבעון הראשון של 2026: לפי ה-IRC ו»רופאים ללא גבולות«, כוחות הממשלה והחברה הצבאית הפרטית Vectus Global ביצעו תקיפות כטב״מים באזורי מגורים, עם נפגעים אזרחיים.",
  "כאן חל הדין בשלושה כיוונים. כלפי הכנופיות: גיוס קטינים ושימוש בהם במעשי איבה אסורים לפי הפרוטוקול האופציונלי לאמנה בדבר זכויות הילד (2000), המגדיר זאת כפשע מלחמה; וההתעללויות באזרחים — רצח, אונס, חטיפה — מפֵרות את האמנה בדבר זכויות הילד עצמה ואת עקרונות הדין ההומניטרי. כלפי מדינת האיטי: השימוש בכטב״מים באזורים מיושבים מעמיד במבחן את עקרון ההבחנה ואת הגנת האזרחים (אמנת ז׳נבה הרביעית), והנציבה העליונה לזכויות אדם כינתה את השימוש בכוח »בלתי הכרחי או בלתי מידתי«, עם מבצעים ש»ניתן לתאר כחיסולים ממוקדים«. כלפי הכוח שבהרשאת האו״ם: החלטה 2793 עצמה מזכירה כיבוד זכויות אדם והגנת קטינים, אך — לפי מקורות במועצה — מדינות אחדות מתחו ביקורת על הנחיה אמריקנית המתמקדת ב»הריגת« חברי כנופיות, במדינה שבה, לפי הערכות האו״ם והיוניצ״ף, 30 עד 50% מן הלוחמים הם קטינים. משטר הסנקציות והאמברגו על הנשק (החלטה 2653) פגעו עד כה במעטים מאוד, בעוד שרוב הנשק המזין את הכנופיות מגיע מארצות הברית.",
  "זהו מבחן הסימטריה המובא עד קצה גבולו: אותו אמת מידה חייב לחול על מי שמבצעים את האלימות ועל מי שאומרים שהם באים לעצור אותה. כוח הקרוי »דיכוי«, בעל עמדה המכוונת לשימוש קטלני בכוח נגד אוכלוסייה חמושה שמחציתה קטינים, מעלה שאלה שהדין שואל מאז ומתמיד: ילד עם רובה נותר, מבחינה משפטית, קודם כול קורבן שיש להגן עליו ולשקמו, לא מטרה — והיוניצ״ף עצמה מזכירה שקטינים שגויסו יש להתייחס אליהם תחילה כאל ילדים. ובכל זאת האיטי נותרת אחד המשברים הנשכחים ביותר בכוכב, המענה ההומניטרי שלה ממומן ברבע וסבלה מחוץ למכ״ם. הדין חל על מי שיורה ועל מי שאומר שהוא בא להשיב את הסדר, או שאינו חל על איש.",
 ]}

# ===================== RU =====================
HT['ru'] = {
 'title':"Гаити: санкционированные ООН «силы подавления» против банд, наполовину состоящих из детей",
 'quote':"«Одного лишь обеспечения безопасности не хватит, чтобы решить проблемы управления.» — Антониу Гутерриш, Генеральный секретарь ООН",
 'labels':LABELS['ru'],
 'bodies':[
  "30 сентября 2025 года Совет Безопасности ООН принял резолюцию 2793, преобразовав Многонациональную миссию по поддержке безопасности (MSS, под руководством Кении, санкционированную в 2023 году резолюцией 2699) в «Силы подавления банд» (Gang Suppression Force) численностью до 5550 человек с мандатом проводить «операции против банд для их нейтрализации, изоляции и сдерживания». Это санкционированные ООН силы, но не операция ООН; их главным архитектором были Соединённые Штаты, а Китай, Россия и Пакистан воздержались из-за сомнений по поводу правил применения силы, финансирования, надзора и подотчётности. Первые контингенты из Чада ожидаются в апреле 2026 года. На месте коалиция банд «Вив Ансанм» контролирует до 90% Порт-о-Пренса и расширяется в департаменты Артибонит и Центр. Гуманитарный кризис — один из самых тяжёлых и наименее финансируемых в мире: 6,4 миллиона человек — более половины населения, включая 2,8 миллиона детей — нуждаются в помощи, и более одного гаитянина из десяти перемещён; к концу 2025 года гуманитарный отклик был профинансирован лишь на 24%. По данным ACLED, в 2025 году погибли более 4500 человек — один из самых высоких показателей в мире; умышленные убийства в Артибоните и Центре выросли на 210% с января по август 2025 года. Смертность от ударов беспилотников и авиаударов выросла на 120% в первом квартале 2026 года: по данным IRC и «Врачей без границ», правительственные силы и частная военная компания Vectus Global наносили удары беспилотниками по жилым районам, с жертвами среди мирного населения.",
  "Здесь право действует в трёх направлениях. В отношении банд: вербовка и использование несовершеннолетних в военных действиях запрещены Факультативным протоколом к Конвенции о правах ребёнка (2000), который квалифицирует это как военное преступление; а злоупотребления против гражданских — убийства, изнасилования, похищения — нарушают саму Конвенцию о правах ребёнка и принципы гуманитарного права. В отношении гаитянского государства: применение беспилотников в населённых районах испытывает на прочность принцип различения и защиту гражданских (IV Женевская конвенция), и Верховный комиссар по правам человека назвала применение силы «излишним или несоразмерным», с операциями, которые «можно описать как целенаправленные убийства». В отношении санкционированных ООН сил: сама резолюция 2793 призывает к уважению прав человека и защите несовершеннолетних, однако — по данным источников в Совете — ряд государств раскритиковали американскую директиву, ориентированную на «убийство» членов банд, в стране, где, по оценкам ООН и ЮНИСЕФ, от 30 до 50% боевиков — несовершеннолетние. Санкционный режим и оружейное эмбарго (резолюция 2653) пока затронули очень немногих, тогда как большая часть оружия, питающего банды, поступает из Соединённых Штатов.",
  "Это доведённая до предела проверка симметрии: один и тот же стандарт должен применяться и к тем, кто творит насилие, и к тем, кто заявляет, что пришёл его остановить. Силы, названные «подавлением», с установкой на смертоносное применение силы против вооружённого населения, наполовину состоящего из несовершеннолетних, ставят вопрос, который право задаёт издавна: ребёнок с винтовкой остаётся, с правовой точки зрения, прежде всего жертвой, которую следует защитить и реинтегрировать, а не мишенью — и сама ЮНИСЕФ напоминает, что завербованных несовершеннолетних следует рассматривать в первую очередь как детей. И всё же Гаити остаётся одним из самых забытых кризисов планеты: его гуманитарный отклик профинансирован на четверть, а его страдания вне поля зрения. Право действует и для тех, кто стреляет, и для тех, кто говорит, что пришёл восстановить порядок, — или не действует ни для кого.",
 ]}

TAGS = ['Haiti','Infanzia','ONU','Diritto internazionale','Crisi dimenticate']
