# -*- coding: utf-8 -*-
# Dati notizia nd-mya — Myanmar/Rohingya: la CIG delibera sul genocidio (caso Gambia c. Myanmar)
# Schema identico a coi.py/rdc.py. REGOLA DI FERRO: fonti reali e verificate; giudizi attribuiti, mai del sito.

import html as _html

_AJ    = "https://www.aljazeera.com/news/2026/1/16/why-the-gambia-wants-myanmar-punished-for-rohingya-genocide"
_AJ_AR = "https://www.aljazeera.net/news/2026/1/12/%D8%A7%D9%84%D8%B9%D8%AF%D9%84-%D8%A7%D9%84%D8%AF%D9%88%D9%84%D9%8A%D8%A9-%D8%AA%D8%A8%D8%AF%D8%A3-%D8%A7%D9%84%D9%86%D8%B8%D8%B1-%D9%81%D9%8A-%D9%82%D8%B6%D9%8A%D8%A9-%D8%A5%D8%A8%D8%A7%D8%AF%D8%A9"
_UNNEWS= "https://news.un.org/en/story/2026/01/1166746"
_OHCHR = "https://www.ohchr.org/en/press-releases/2026/01/rohingya-voices-icj-step-toward-truth-and-justice"
_IIMM  = "https://iimm.un.org/en/icj-gambia-v-myanmar"

_FT = {'it':'Fonti','en':'Sources','fr':'Sources','de':'Quellen','es':'Fuentes','pt':'Fontes',
       'tr':'Kaynaklar','zh':'来源','ar':'المصادر','he':'מקורות','ru':'Источники'}

def _a(url,label):
    return '<a href="%s" target="_blank" rel="noopener noreferrer">%s</a>'%(url,_html.escape(label))

LANGS=['it','en','fr','de','es','pt','tr','zh','ar','he','ru']
SRC={}
for _l in LANGS:
    aj=_a(_AJ_AR,'الجزيرة') if _l=='ar' else _a(_AJ,'Al Jazeera')
    SRC[_l]='%s: %s · %s · %s · %s'%(_FT[_l], aj, _a(_UNNEWS,'UN News'), _a(_OHCHR,'OHCHR'), _a(_IIMM,'IIMM'))

DATE = {'it':'Giugno 2026','en':'June 2026','fr':'Juin 2026','de':'Juni 2026','es':'Junio de 2026',
        'pt':'Junho de 2026','tr':'Haziran 2026','zh':'2026年6月','ar':'يونيو 2026','he':'יוני 2026','ru':'Июнь 2026'}
SHARE = {'it':'Condividi','en':'Share','fr':'Partager','de':'Teilen','es':'Compartir','pt':'Partilhar',
         'tr':'Paylaş','zh':'分享','ar':'مشاركة','he':'שיתוף','ru':'Поделиться'}
READ  = {'it':"Leggi l'analisi",'en':'Read the analysis','fr':"Lire l'analyse",'de':'Analyse lesen',
         'es':'Leer el análisis','pt':'Ler a análise','tr':'Analizi oku','zh':'阅读分析',
         'ar':'اقرأ التحليل','he':'קראו את הניתוח','ru':'Читать анализ'}
FLAB  = dict(_FT)
LABELS = {
 'it':['Il fatto','Commento giuridico','Implicazioni'],'en':['The fact','Legal commentary','Implications'],
 'fr':['Le fait','Commentaire juridique','Implications'],'de':['Der Sachverhalt','Rechtlicher Kommentar','Konsequenzen'],
 'es':['El hecho','Comentario jurídico','Implicaciones'],'pt':['O facto','Comentário jurídico','Implicações'],
 'tr':['Olgu','Hukuki yorum','Sonuçlar'],'zh':['事实','法律评注','影响'],
 'ar':['الواقعة','تعليق قانوني','التبعات'],'he':['העובדה','פרשנות משפטית','השלכות'],
 'ru':['Факт','Правовой комментарий','Последствия'],
}

MYA = {}

# ===================== IT =====================
MYA['it'] = {
 'title':"La Corte Internazionale di Giustizia delibera sul genocidio dei Rohingya",
 'quote':"«Si tratta di persone reali, storie reali, un gruppo reale di esseri umani.» — Dawda Jallow, ministro della Giustizia del Gambia, alla CIG",
 'labels':LABELS['it'],
 'bodies':[
  "A cinque anni dal colpo di Stato del febbraio 2021, il Myanmar resta una delle emergenze umanitarie più vaste e meno seguite al mondo: quasi 5,2 milioni di sfollati, insicurezza alimentare acuta, e attacchi aerei sui civili passati da poche decine nel primo anno del golpe a oltre 3.300 nel 2025-26, con più di 3.800 morti civili solo dai raid. Dopo elezioni tenute tra dicembre 2025 e gennaio 2026 in soli 263 dei 330 distretti — quasi tutti in aree sotto controllo militare, con la Lega Nazionale per la Democrazia e decine di partiti di opposizione esclusi e molti leader ancora detenuti — il capo del golpe Min Aung Hlaing è diventato presidente nell'aprile 2026; l'Alto Commissario ONU per i diritti umani Volker Türk ha affermato che il processo non ha rispettato i diritti fondamentali dei cittadini, e l'International Crisis Group lo descrive come una facciata civile dietro cui i militari conservano il controllo. Sul fronte giudiziario, dal 12 al 29 gennaio 2026 la Corte Internazionale di Giustizia ha tenuto le udienze di merito nel caso Gambia contro Myanmar, sotto la Convenzione sul Genocidio, per la campagna del 2017 contro la minoranza musulmana Rohingya — oltre 700.000 persone in fuga verso il Bangladesh, con intento genocidario accertato dalla Missione d'inchiesta dell'ONU. La sentenza è attesa entro il 2026. Il Myanmar respinge le accuse: i suoi legali hanno messo in guardia contro letture selettive e l'eccessivo affidamento ai rapporti delle ONG, e nei procedimenti non hanno mai pronunciato la parola «Rohingya», usando il termine «Bengali», che il Relatore speciale dell'ONU per il Myanmar definisce dispregiativo.",
  "È il primo caso in oltre un decennio in cui la Corte Internazionale di Giustizia esamina nel merito un'accusa di genocidio (Convenzione sul Genocidio del 1948, art. IX). La sua forza sta nel principio erga omnes partes: il Gambia, Stato lontano e non coinvolto, agisce perché ogni Stato parte ha un interesse comune a prevenire e punire il genocidio — un dovere condiviso, non un affare bilaterale. Il binario penale è distinto e personale: a novembre 2024 il procuratore della Corte Penale Internazionale ha chiesto un mandato d'arresto per Min Aung Hlaing per i crimini contro l'umanità di deportazione e persecuzione dei Rohingya; a febbraio 2025 un tribunale argentino ha emesso mandati in giurisdizione universale. Si aggiungono i crimini di guerra documentati dal Meccanismo investigativo indipendente dell'ONU — raid su case, ospedali e scuole, blocco degli aiuti come punizione collettiva (IV Convenzione di Ginevra, Statuto di Roma). Trattandosi di un caso ancora in deliberazione, non esiste sentenza: il genocidio è accertato dalla Missione ONU e dedotto da un quadro di condotta, ma non ancora giudicato dalla Corte.",
  "Qui il diritto si misura nella sua coerenza. La decisione su Gambia contro Myanmar plasmerà i due altri casi di genocidio pendenti davanti alla stessa Corte — Sudafrica contro Israele e Ucraina contro Russia: stessa Convenzione, stessa soglia di prova sull'intento, stessa domanda su chi abbia il dovere di applicarla. Ma la coerenza vale anche dentro il conflitto: i Rohingya sono intrappolati tra la giunta e l'Arakan Army, e il Meccanismo dell'ONU indaga gravi abusi di entrambe le parti — esecuzioni, incendi, reclutamento forzato; mentre la macchina bellica della giunta è alimentata dalle armi di Cina, Russia e India. Eppure, con milioni di sfollati e — secondo l'ACLED — il conflitto più frammentato al mondo, l'attenzione internazionale resta marginale rispetto alla scala della crisi. È esattamente lo scarto tra gravità e attenzione che questa piattaforma esiste per documentare: il diritto vale per tutti, o non vale per nessuno.",
 ]}

# ===================== EN =====================
MYA['en'] = {
 'title':"The International Court of Justice deliberates on the Rohingya genocide",
 'quote':"“It is about real people, real stories, and a real group of human beings.” — Dawda Jallow, Gambia's Justice Minister, at the ICJ",
 'labels':LABELS['en'],
 'bodies':[
  "Five years after the February 2021 coup, Myanmar remains one of the world's largest and least-followed humanitarian emergencies: nearly 5.2 million displaced, acute food insecurity, and air strikes on civilians that rose from a few dozen in the coup's first year to more than 3,300 in 2025-26, with over 3,800 civilians killed by air strikes alone. After elections held between December 2025 and January 2026 in only 263 of 330 townships — almost all in military-controlled areas, with the National League for Democracy and dozens of opposition parties excluded and many leaders still detained — coup leader Min Aung Hlaing became president in April 2026; the UN High Commissioner for Human Rights, Volker Türk, said the process failed to respect citizens' fundamental rights, and the International Crisis Group describes it as a civilian façade behind which the military retains control. On the judicial front, from 12 to 29 January 2026 the International Court of Justice held merits hearings in The Gambia v. Myanmar, under the Genocide Convention, over the 2017 campaign against the Muslim Rohingya minority — more than 700,000 people who fled to Bangladesh, with genocidal intent found by the UN Fact-Finding Mission. A judgment is expected during 2026. Myanmar rejects the accusations: its lawyers warned against selective readings and over-reliance on NGO reports, and throughout the proceedings never uttered the word “Rohingya”, using the term “Bengali”, which the UN Special Rapporteur on Myanmar calls pejorative.",
  "This is the first case in more than a decade in which the International Court of Justice examines a genocide allegation on the merits (1948 Genocide Convention, art. IX). Its force lies in the principle erga omnes partes: The Gambia, a distant and uninvolved State, acts because every State party shares a common interest in preventing and punishing genocide — a shared duty, not a bilateral matter. The criminal track is separate and personal: in November 2024 the Prosecutor of the International Criminal Court requested an arrest warrant for Min Aung Hlaing for the crimes against humanity of deportation and persecution of the Rohingya; in February 2025 an Argentine court issued warrants under universal jurisdiction. To these are added the war crimes documented by the UN Independent Investigative Mechanism — strikes on homes, hospitals and schools, the blocking of aid as collective punishment (Fourth Geneva Convention, Rome Statute). As a case still under deliberation, there is no judgment: the genocide is found by the UN Mission and inferred from a pattern of conduct, but not yet adjudicated by the Court.",
  "Here the law is measured by its coherence. The decision in The Gambia v. Myanmar will shape the two other genocide cases pending before the same Court — South Africa v. Israel and Ukraine v. Russia: the same Convention, the same evidentiary threshold for intent, the same question of who has the duty to apply it. But coherence also holds within the conflict: the Rohingya are trapped between the junta and the Arakan Army, and the UN Mechanism is investigating grave abuses by both sides — executions, arson, forced recruitment; while the junta's war machine is fuelled by weapons from China, Russia and India. And yet, with millions displaced and — according to ACLED — the most fragmented conflict in the world, international attention remains marginal relative to the scale of the crisis. This is precisely the gap between gravity and attention that this platform exists to document: the law applies to everyone, or it applies to no one.",
 ]}

# ===================== FR =====================
MYA['fr'] = {
 'title':"La Cour internationale de Justice délibère sur le génocide des Rohingyas",
 'quote':"« Il s'agit de personnes réelles, d'histoires réelles, d'un groupe réel d'êtres humains. » — Dawda Jallow, ministre de la Justice de la Gambie, à la CIJ",
 'labels':LABELS['fr'],
 'bodies':[
  "Cinq ans après le coup d'État de février 2021, le Myanmar demeure l'une des urgences humanitaires les plus vastes et les moins suivies au monde : près de 5,2 millions de déplacés, une insécurité alimentaire aiguë, et des frappes aériennes contre les civils passées de quelques dizaines la première année du putsch à plus de 3 300 en 2025-26, avec plus de 3 800 civils tués par les seules frappes. Après des élections tenues entre décembre 2025 et janvier 2026 dans seulement 263 des 330 cantons — presque tous en zones sous contrôle militaire, avec la Ligue nationale pour la démocratie et des dizaines de partis d'opposition exclus et de nombreux dirigeants toujours détenus — le chef du putsch Min Aung Hlaing est devenu président en avril 2026 ; le Haut-Commissaire de l'ONU aux droits de l'homme, Volker Türk, a affirmé que le processus n'avait pas respecté les droits fondamentaux des citoyens, et l'International Crisis Group le décrit comme une façade civile derrière laquelle l'armée conserve le contrôle. Sur le plan judiciaire, du 12 au 29 janvier 2026 la Cour internationale de Justice a tenu les audiences au fond dans l'affaire Gambie contre Myanmar, au titre de la Convention sur le génocide, pour la campagne de 2017 contre la minorité musulmane rohingya — plus de 700 000 personnes en fuite vers le Bangladesh, avec une intention génocidaire établie par la Mission d'enquête de l'ONU. Un arrêt est attendu courant 2026. Le Myanmar rejette les accusations : ses avocats ont mis en garde contre des lectures sélectives et une dépendance excessive aux rapports d'ONG, et au cours de la procédure n'ont jamais prononcé le mot « Rohingya », employant le terme « Bengali », que le Rapporteur spécial de l'ONU sur le Myanmar qualifie de péjoratif.",
  "C'est la première affaire depuis plus d'une décennie dans laquelle la Cour internationale de Justice examine au fond une accusation de génocide (Convention sur le génocide de 1948, art. IX). Sa force tient au principe erga omnes partes : la Gambie, État lointain et non impliqué, agit parce que chaque État partie a un intérêt commun à prévenir et à punir le génocide — un devoir partagé, non une affaire bilatérale. La voie pénale est distincte et personnelle : en novembre 2024, le Procureur de la Cour pénale internationale a demandé un mandat d'arrêt contre Min Aung Hlaing pour les crimes contre l'humanité de déportation et de persécution des Rohingyas ; en février 2025, un tribunal argentin a émis des mandats au titre de la compétence universelle. S'y ajoutent les crimes de guerre documentés par le Mécanisme d'enquête indépendant de l'ONU — frappes sur des maisons, des hôpitaux et des écoles, blocage de l'aide comme châtiment collectif (IVe Convention de Genève, Statut de Rome). S'agissant d'une affaire encore en délibéré, il n'existe aucun arrêt : le génocide est établi par la Mission de l'ONU et déduit d'un ensemble de comportements, mais pas encore jugé par la Cour.",
  "Ici le droit se mesure à sa cohérence. La décision dans Gambie contre Myanmar façonnera les deux autres affaires de génocide pendantes devant la même Cour — Afrique du Sud contre Israël et Ukraine contre Russie : la même Convention, le même seuil de preuve sur l'intention, la même question de savoir qui a le devoir de l'appliquer. Mais la cohérence vaut aussi à l'intérieur du conflit : les Rohingyas sont pris entre la junte et l'Arakan Army, et le Mécanisme de l'ONU enquête sur de graves abus des deux camps — exécutions, incendies, recrutement forcé ; tandis que la machine de guerre de la junte est alimentée par les armes de la Chine, de la Russie et de l'Inde. Et pourtant, avec des millions de déplacés et — selon l'ACLED — le conflit le plus fragmenté au monde, l'attention internationale reste marginale au regard de l'ampleur de la crise. C'est exactement l'écart entre gravité et attention que cette plateforme existe pour documenter : le droit vaut pour tous, ou il ne vaut pour personne.",
 ]}

# ===================== DE =====================
MYA['de'] = {
 'title':"Der Internationale Gerichtshof berät über den Völkermord an den Rohingya",
 'quote':"„Es geht um echte Menschen, echte Geschichten, eine echte Gruppe von Menschen.“ — Dawda Jallow, Justizminister Gambias, vor dem IGH",
 'labels':LABELS['de'],
 'bodies':[
  "Fünf Jahre nach dem Putsch vom Februar 2021 bleibt Myanmar eine der größten und am wenigsten beachteten humanitären Notlagen der Welt: fast 5,2 Millionen Vertriebene, akute Ernährungsunsicherheit und Luftangriffe auf Zivilisten, die von einigen Dutzend im ersten Jahr des Putsches auf über 3.300 in den Jahren 2025-26 stiegen, mit mehr als 3.800 allein durch Luftangriffe getöteten Zivilisten. Nach Wahlen, die zwischen Dezember 2025 und Januar 2026 in nur 263 der 330 Bezirke abgehalten wurden — fast alle in militärisch kontrollierten Gebieten, unter Ausschluss der Nationalen Liga für Demokratie und Dutzender Oppositionsparteien und mit vielen weiterhin inhaftierten Anführern — wurde Putschführer Min Aung Hlaing im April 2026 Präsident; der UN-Hochkommissar für Menschenrechte, Volker Türk, erklärte, das Verfahren habe die Grundrechte der Bürger nicht geachtet, und die International Crisis Group beschreibt es als zivile Fassade, hinter der das Militär die Kontrolle behält. Auf juristischer Ebene hielt der Internationale Gerichtshof vom 12. bis 29. Januar 2026 die Verhandlungen zur Hauptsache im Fall Gambia gegen Myanmar ab, nach der Völkermordkonvention, wegen der Kampagne von 2017 gegen die muslimische Minderheit der Rohingya — mehr als 700.000 Menschen flohen nach Bangladesch, mit einer von der UN-Untersuchungsmission festgestellten Völkermordabsicht. Ein Urteil wird im Laufe des Jahres 2026 erwartet. Myanmar weist die Vorwürfe zurück: seine Anwälte warnten vor selektiven Lesarten und übermäßigem Vertrauen auf NGO-Berichte, und im Verfahren sprachen sie nie das Wort „Rohingya“ aus, sondern verwendeten den Begriff „Bengali“, den der UN-Sonderberichterstatter für Myanmar als abwertend bezeichnet.",
  "Es ist der erste Fall seit mehr als einem Jahrzehnt, in dem der Internationale Gerichtshof einen Völkermordvorwurf in der Sache prüft (Völkermordkonvention von 1948, Art. IX). Seine Kraft liegt im Grundsatz erga omnes partes: Gambia, ein ferner und nicht beteiligter Staat, handelt, weil jeder Vertragsstaat ein gemeinsames Interesse an der Verhütung und Bestrafung von Völkermord hat — eine geteilte Pflicht, keine bilaterale Angelegenheit. Der strafrechtliche Weg ist getrennt und persönlich: im November 2024 beantragte der Ankläger des Internationalen Strafgerichtshofs einen Haftbefehl gegen Min Aung Hlaing wegen der Verbrechen gegen die Menschlichkeit der Deportation und Verfolgung der Rohingya; im Februar 2025 erließ ein argentinisches Gericht Haftbefehle nach dem Weltrechtsprinzip. Hinzu kommen die vom Unabhängigen Untersuchungsmechanismus der UN dokumentierten Kriegsverbrechen — Angriffe auf Wohnhäuser, Krankenhäuser und Schulen, die Blockade von Hilfe als kollektive Bestrafung (IV. Genfer Abkommen, Römisches Statut). Da der Fall noch beraten wird, gibt es kein Urteil: der Völkermord ist von der UN-Mission festgestellt und aus einem Verhaltensmuster abgeleitet, aber vom Gerichtshof noch nicht entschieden.",
  "Hier bemisst sich das Recht an seiner Kohärenz. Die Entscheidung in Gambia gegen Myanmar wird die beiden anderen vor demselben Gerichtshof anhängigen Völkermordverfahren prägen — Südafrika gegen Israel und Ukraine gegen Russland: dieselbe Konvention, dieselbe Beweisschwelle für den Vorsatz, dieselbe Frage, wer die Pflicht zu ihrer Anwendung hat. Doch Kohärenz gilt auch innerhalb des Konflikts: die Rohingya sind zwischen der Junta und der Arakan Army gefangen, und der UN-Mechanismus untersucht schwere Übergriffe beider Seiten — Hinrichtungen, Brandstiftung, Zwangsrekrutierung; während die Kriegsmaschinerie der Junta von Waffen aus China, Russland und Indien gespeist wird. Und doch bleibt mit Millionen Vertriebenen und — laut ACLED — dem am stärksten fragmentierten Konflikt der Welt die internationale Aufmerksamkeit gemessen am Ausmaß der Krise gering. Genau diese Kluft zwischen Schwere und Aufmerksamkeit zu dokumentieren, dafür existiert diese Plattform: das Recht gilt für alle, oder es gilt für niemanden.",
 ]}

# ===================== ES =====================
MYA['es'] = {
 'title':"La Corte Internacional de Justicia delibera sobre el genocidio de los rohinyás",
 'quote':"«Se trata de personas reales, historias reales, un grupo real de seres humanos.» — Dawda Jallow, ministro de Justicia de Gambia, ante la CIJ",
 'labels':LABELS['es'],
 'bodies':[
  "Cinco años después del golpe de Estado de febrero de 2021, Myanmar sigue siendo una de las emergencias humanitarias más vastas y menos seguidas del mundo: casi 5,2 millones de desplazados, inseguridad alimentaria aguda, y ataques aéreos contra civiles que pasaron de unas pocas decenas en el primer año del golpe a más de 3.300 en 2025-26, con más de 3.800 civiles muertos solo por los bombardeos. Tras unas elecciones celebradas entre diciembre de 2025 y enero de 2026 en apenas 263 de los 330 distritos — casi todos en zonas bajo control militar, con la Liga Nacional para la Democracia y decenas de partidos de oposición excluidos y muchos líderes aún detenidos — el jefe del golpe Min Aung Hlaing se convirtió en presidente en abril de 2026; el Alto Comisionado de la ONU para los Derechos Humanos, Volker Türk, afirmó que el proceso no respetó los derechos fundamentales de los ciudadanos, y el International Crisis Group lo describe como una fachada civil tras la cual los militares conservan el control. En el plano judicial, del 12 al 29 de enero de 2026 la Corte Internacional de Justicia celebró las audiencias de fondo en el caso Gambia contra Myanmar, bajo la Convención sobre el Genocidio, por la campaña de 2017 contra la minoría musulmana rohinyá — más de 700.000 personas que huyeron a Bangladés, con intención genocida constatada por la Misión de investigación de la ONU. Se espera una sentencia a lo largo de 2026. Myanmar rechaza las acusaciones: sus abogados advirtieron contra lecturas selectivas y una dependencia excesiva de los informes de las ONG, y a lo largo del proceso nunca pronunciaron la palabra «rohinyá», usando el término «bengalí», que el Relator Especial de la ONU sobre Myanmar califica de despectivo.",
  "Es el primer caso en más de una década en que la Corte Internacional de Justicia examina en el fondo una acusación de genocidio (Convención sobre el Genocidio de 1948, art. IX). Su fuerza reside en el principio erga omnes partes: Gambia, Estado lejano y no implicado, actúa porque todo Estado parte tiene un interés común en prevenir y castigar el genocidio — un deber compartido, no un asunto bilateral. La vía penal es distinta y personal: en noviembre de 2024 el Fiscal de la Corte Penal Internacional solicitó una orden de arresto contra Min Aung Hlaing por los crímenes de lesa humanidad de deportación y persecución de los rohinyás; en febrero de 2025 un tribunal argentino emitió órdenes bajo jurisdicción universal. A ello se suman los crímenes de guerra documentados por el Mecanismo de Investigación Independiente de la ONU — ataques a viviendas, hospitales y escuelas, bloqueo de la ayuda como castigo colectivo (IV Convenio de Ginebra, Estatuto de Roma). Al tratarse de un caso aún en deliberación, no existe sentencia: el genocidio está constatado por la Misión de la ONU y deducido de un patrón de conducta, pero aún no juzgado por la Corte.",
  "Aquí el derecho se mide por su coherencia. La decisión en Gambia contra Myanmar moldeará los otros dos casos de genocidio pendientes ante la misma Corte — Sudáfrica contra Israel y Ucrania contra Rusia: la misma Convención, el mismo umbral de prueba sobre la intención, la misma pregunta sobre quién tiene el deber de aplicarla. Pero la coherencia vale también dentro del conflicto: los rohinyás están atrapados entre la junta y el Arakan Army, y el Mecanismo de la ONU investiga graves abusos de ambas partes — ejecuciones, incendios, reclutamiento forzado; mientras la maquinaria bélica de la junta se nutre de las armas de China, Rusia e India. Y sin embargo, con millones de desplazados y — según ACLED — el conflicto más fragmentado del mundo, la atención internacional sigue siendo marginal frente a la escala de la crisis. Es exactamente la distancia entre gravedad y atención que esta plataforma existe para documentar: el derecho vale para todos, o no vale para nadie.",
 ]}

# ===================== PT =====================
MYA['pt'] = {
 'title':"O Tribunal Internacional de Justiça delibera sobre o genocídio dos Rohingya",
 'quote':"«Trata-se de pessoas reais, histórias reais, um grupo real de seres humanos.» — Dawda Jallow, ministro da Justiça da Gâmbia, no TIJ",
 'labels':LABELS['pt'],
 'bodies':[
  "Cinco anos após o golpe de Estado de fevereiro de 2021, Myanmar continua a ser uma das emergências humanitárias mais vastas e menos acompanhadas do mundo: quase 5,2 milhões de deslocados, insegurança alimentar aguda, e ataques aéreos contra civis que passaram de poucas dezenas no primeiro ano do golpe para mais de 3.300 em 2025-26, com mais de 3.800 civis mortos só pelos bombardeamentos. Após eleições realizadas entre dezembro de 2025 e janeiro de 2026 em apenas 263 dos 330 distritos — quase todos em zonas sob controlo militar, com a Liga Nacional para a Democracia e dezenas de partidos da oposição excluídos e muitos líderes ainda detidos — o chefe do golpe Min Aung Hlaing tornou-se presidente em abril de 2026; o Alto-Comissário da ONU para os Direitos Humanos, Volker Türk, afirmou que o processo não respeitou os direitos fundamentais dos cidadãos, e o International Crisis Group descreve-o como uma fachada civil por trás da qual os militares conservam o controlo. No plano judicial, de 12 a 29 de janeiro de 2026 o Tribunal Internacional de Justiça realizou as audiências de mérito no caso Gâmbia contra Myanmar, ao abrigo da Convenção sobre o Genocídio, pela campanha de 2017 contra a minoria muçulmana Rohingya — mais de 700.000 pessoas que fugiram para o Bangladesh, com intenção genocida constatada pela Missão de inquérito da ONU. Uma sentença é esperada ao longo de 2026. Myanmar rejeita as acusações: os seus advogados alertaram contra leituras seletivas e uma dependência excessiva dos relatórios das ONG, e ao longo do processo nunca pronunciaram a palavra «Rohingya», usando o termo «Bengali», que o Relator Especial da ONU sobre Myanmar qualifica de depreciativo.",
  "É o primeiro caso em mais de uma década em que o Tribunal Internacional de Justiça examina no mérito uma acusação de genocídio (Convenção sobre o Genocídio de 1948, art. IX). A sua força reside no princípio erga omnes partes: a Gâmbia, Estado distante e não envolvido, age porque todo Estado parte tem um interesse comum em prevenir e punir o genocídio — um dever partilhado, não um assunto bilateral. A via penal é distinta e pessoal: em novembro de 2024 o Procurador do Tribunal Penal Internacional pediu um mandado de detenção contra Min Aung Hlaing pelos crimes contra a humanidade de deportação e perseguição dos Rohingya; em fevereiro de 2025 um tribunal argentino emitiu mandados ao abrigo da jurisdição universal. A estes somam-se os crimes de guerra documentados pelo Mecanismo de Investigação Independente da ONU — ataques a casas, hospitais e escolas, bloqueio da ajuda como castigo coletivo (IV Convenção de Genebra, Estatuto de Roma). Tratando-se de um caso ainda em deliberação, não existe sentença: o genocídio está constatado pela Missão da ONU e deduzido de um padrão de conduta, mas ainda não julgado pelo Tribunal.",
  "Aqui o direito mede-se pela sua coerência. A decisão em Gâmbia contra Myanmar moldará os outros dois casos de genocídio pendentes perante o mesmo Tribunal — África do Sul contra Israel e Ucrânia contra Rússia: a mesma Convenção, o mesmo limiar de prova sobre a intenção, a mesma pergunta sobre quem tem o dever de a aplicar. Mas a coerência vale também dentro do conflito: os Rohingya estão presos entre a junta e o Arakan Army, e o Mecanismo da ONU investiga graves abusos de ambas as partes — execuções, incêndios, recrutamento forçado; enquanto a máquina de guerra da junta é alimentada pelas armas da China, da Rússia e da Índia. E no entanto, com milhões de deslocados e — segundo a ACLED — o conflito mais fragmentado do mundo, a atenção internacional permanece marginal face à escala da crise. É exatamente o desfasamento entre gravidade e atenção que esta plataforma existe para documentar: o direito vale para todos, ou não vale para ninguém.",
 ]}

# ===================== TR =====================
MYA['tr'] = {
 'title':"Uluslararası Adalet Divanı Rohingya soykırımı üzerine müzakere ediyor",
 'quote':"«Bu, gerçek insanlarla, gerçek hikâyelerle, gerçek bir insan topluluğuyla ilgilidir.» — Dawda Jallow, Gambiya Adalet Bakanı, UAD'de",
 'labels':LABELS['tr'],
 'bodies':[
  "Şubat 2021 darbesinden beş yıl sonra Myanmar, dünyanın en büyük ve en az takip edilen insani acil durumlarından biri olmayı sürdürüyor: yaklaşık 5,2 milyon yerinden edilmiş insan, ağır gıda güvensizliği ve sivillere yönelik hava saldırıları darbenin ilk yılında birkaç düzineden 2025-26'da 3.300'ün üzerine çıktı; yalnızca hava saldırılarında 3.800'den fazla sivil öldü. Aralık 2025 ile Ocak 2026 arasında 330 ilçenin yalnızca 263'ünde — neredeyse tamamı askeri denetim altındaki bölgelerde, Ulusal Demokrasi Birliği ve onlarca muhalefet partisi dışlanmış, birçok lider hâlâ tutuklu — yapılan seçimlerin ardından darbenin lideri Min Aung Hlaing Nisan 2026'da cumhurbaşkanı oldu; BM İnsan Hakları Yüksek Komiseri Volker Türk sürecin yurttaşların temel haklarına saygı göstermediğini belirtti, International Crisis Group ise bunu ordunun denetimi elinde tuttuğu sivil bir cephe olarak tanımlıyor. Yargı cephesinde, Uluslararası Adalet Divanı 12-29 Ocak 2026'da Gambiya–Myanmar davasında esasa ilişkin duruşmaları, Soykırım Sözleşmesi kapsamında, 2017'de Müslüman Rohingya azınlığına yönelik kampanya nedeniyle gördü — 700.000'den fazla kişi Bangladeş'e kaçtı ve BM Araştırma Misyonu soykırım kastı tespit etti. Bir kararın 2026 içinde verilmesi bekleniyor. Myanmar suçlamaları reddediyor: avukatları seçici okumalara ve STK raporlarına aşırı bağımlılığa karşı uyardı; yargılama boyunca «Rohingya» sözcüğünü hiç telaffuz etmeyip, BM Myanmar Özel Raportörü'nün aşağılayıcı olarak nitelediği «Bengali» terimini kullandılar.",
  "Bu, Uluslararası Adalet Divanı'nın bir soykırım iddiasını esastan incelediği on yılı aşkın süredeki ilk davadır (1948 Soykırım Sözleşmesi, m. IX). Gücü erga omnes partes ilkesinde yatar: uzak ve davaya taraf olmayan bir Devlet olan Gambiya, her taraf Devletin soykırımı önleme ve cezalandırmada ortak bir çıkarı olduğu için harekete geçer — ikili bir mesele değil, paylaşılan bir yükümlülük. Ceza yolu ayrı ve kişiseldir: Kasım 2024'te Uluslararası Ceza Mahkemesi Savcısı, Min Aung Hlaing hakkında Rohingya'nın sürülmesi ve zulme uğratılması insanlığa karşı suçlarından tutuklama emri talep etti; Şubat 2025'te bir Arjantin mahkemesi evrensel yargı yetkisi uyarınca emirler çıkardı. Bunlara BM Bağımsız Araştırma Mekanizması'nın belgelediği savaş suçları eklenir — evlere, hastanelere ve okullara saldırılar, toplu ceza olarak yardımın engellenmesi (IV. Cenevre Sözleşmesi, Roma Statüsü). Dava hâlâ müzakere aşamasında olduğundan ortada karar yoktur: soykırım BM Misyonu tarafından tespit edilmiş ve bir davranış örüntüsünden çıkarsanmıştır, ancak Divan tarafından henüz hükme bağlanmamıştır.",
  "Hukuk burada tutarlılığıyla ölçülür. Gambiya–Myanmar kararı, aynı Divan önünde derdest olan diğer iki soykırım davasını biçimlendirecektir — Güney Afrika–İsrail ve Ukrayna–Rusya: aynı Sözleşme, kast konusunda aynı ispat eşiği, onu uygulama görevinin kimde olduğuna dair aynı soru. Ama tutarlılık çatışmanın içinde de geçerlidir: Rohingyalar cunta ile Arakan Ordusu arasında sıkışmış durumda ve BM Mekanizması her iki tarafın ağır ihlallerini soruşturuyor — infazlar, kundaklama, zorla askere alma; cuntanın savaş makinesi ise Çin, Rusya ve Hindistan'ın silahlarıyla besleniyor. Yine de, milyonlarca yerinden edilmiş insanla ve — ACLED'e göre — dünyanın en parçalı çatışmasıyla, uluslararası ilgi krizin ölçeğine kıyasla sınırlı kalıyor. Bu, tam da bu platformun belgelemek için var olduğu, ağırlık ile ilgi arasındaki uçurumdur: hukuk herkes için geçerlidir ya da hiç kimse için.",
 ]}

# ===================== ZH =====================
MYA['zh'] = {
 'title':"国际法院就罗兴亚种族灭绝案进行评议",
 'quote':"“这关乎真实的人、真实的故事、真实的一群人。” —— 冈比亚司法部长达瓦·贾洛，于国际法院",
 'labels':LABELS['zh'],
 'bodies':[
  "2021年2月政变五年后，缅甸仍是世界上规模最大、却最少被关注的人道主义紧急状况之一：近520万人流离失所，粮食严重不安全，针对平民的空袭从政变第一年的数十起增至2025-26年的逾3300起，仅空袭就造成3800多名平民死亡。在2025年12月至2026年1月、仅于330个镇区中的263个（几乎全部在军方控制区）举行的选举之后——全国民主联盟与数十个反对党被排除、许多领导人仍被关押——政变首领敏昂莱于2026年4月就任总统；联合国人权事务高级专员沃尔克·蒂尔克表示，该进程未能尊重公民的基本权利，国际危机组织则将其描述为军方借以维持控制的文官门面。在司法层面，国际法院于2026年1月12日至29日就冈比亚诉缅甸案举行了实体审理，依据《灭绝种族公约》，针对2017年针对穆斯林罗兴亚少数族群的行动——逾70万人逃往孟加拉国，联合国实况调查团认定存在灭绝种族的意图。判决预计在2026年内作出。缅甸否认指控：其律师告诫不要作选择性解读、不要过度依赖非政府组织的报告，并在整个程序中从未说出“罗兴亚”一词，而使用联合国缅甸问题特别报告员称之为蔑称的“孟加拉人”。",
  "这是十多年来国际法院首次就一项灭绝种族指控进行实体审理（1948年《灭绝种族公约》第九条）。其力量在于erga omnes partes（对全体缔约方）原则：冈比亚作为遥远且未卷入的国家提起诉讼，是因为每个缔约国对预防和惩治灭绝种族都负有共同利益——这是共同的义务，而非双边事务。刑事路径是独立且针对个人的：2024年11月，国际刑事法院检察官就敏昂莱在2017年对罗兴亚人实施的驱逐与迫害这两项危害人类罪请求逮捕令；2025年2月，一家阿根廷法院依普遍管辖权签发了逮捕令。此外还有联合国独立调查机制记录的战争罪——对住宅、医院和学校的袭击，以及作为集体惩罚的封锁援助（《日内瓦第四公约》《罗马规约》）。由于此案仍在评议中，尚无判决：灭绝种族系由联合国调查团认定、并从一系列行为模式中推断，但尚未经法院裁判。",
  "在此，法律以其一致性来衡量。冈比亚诉缅甸案的裁决将影响在同一法院待审的另外两起灭绝种族案——南非诉以色列、乌克兰诉俄罗斯：同一部公约、关于意图的同一证明门槛、关于谁有义务适用它的同一问题。但一致性在冲突内部同样适用：罗兴亚人被夹在军政府与若开军之间，联合国机制正在调查双方的严重侵权——处决、纵火、强迫征兵；与此同时，军政府的战争机器由中国、俄罗斯和印度的武器供养。然而，在数百万流离失所者之下、并且据ACLED称是世界上最碎片化的冲突，国际社会的关注相对于危机的规模仍然微弱。这正是本平台之所以存在去记录的、严重程度与关注度之间的落差：法律要么对所有人适用，要么对任何人都不适用。",
 ]}

# ===================== AR =====================
MYA['ar'] = {
 'title':"محكمة العدل الدولية تتداول في قضية إبادة الروهينغا",
 'quote':"«الأمر يتعلق بأشخاص حقيقيين، وقصص حقيقية، ومجموعة حقيقية من البشر.» — داودا جالو، وزير العدل في غامبيا، أمام محكمة العدل الدولية",
 'labels':LABELS['ar'],
 'bodies':[
  "بعد خمس سنوات على انقلاب فبراير 2021، تظل ميانمار واحدة من أوسع حالات الطوارئ الإنسانية وأقلها متابعةً في العالم: نحو 5.2 مليون نازح، وانعدام حادّ للأمن الغذائي، وغارات جوية على المدنيين ارتفعت من بضع عشرات في العام الأول للانقلاب إلى أكثر من 3300 في 2025-26، مع أكثر من 3800 قتيل مدني من الغارات وحدها. وبعد انتخابات جرت بين ديسمبر 2025 ويناير 2026 في 263 فقط من أصل 330 بلدة — جميعها تقريباً في مناطق خاضعة للسيطرة العسكرية، مع استبعاد الرابطة الوطنية من أجل الديمقراطية وعشرات أحزاب المعارضة واستمرار احتجاز كثير من القادة — أصبح زعيم الانقلاب مين أونغ هلاينغ رئيساً في أبريل 2026؛ وقال المفوض السامي للأمم المتحدة لحقوق الإنسان فولكر تورك إن العملية لم تحترم الحقوق الأساسية للمواطنين، فيما تصفها مجموعة الأزمات الدولية بأنها واجهة مدنية يحتفظ الجيش خلفها بالسيطرة. وعلى الصعيد القضائي، عقدت محكمة العدل الدولية من 12 إلى 29 يناير 2026 جلسات النظر في موضوع قضية غامبيا ضد ميانمار، بموجب اتفاقية منع الإبادة الجماعية، بشأن حملة 2017 ضد أقلية الروهينغا المسلمة — أكثر من 700 ألف شخص فرّوا إلى بنغلاديش، مع نيّة إبادية أثبتتها بعثة تقصّي الحقائق التابعة للأمم المتحدة. ويُتوقع صدور حكم خلال عام 2026. وتنفي ميانمار الاتهامات: حذّر محاموها من القراءات الانتقائية ومن الإفراط في الاعتماد على تقارير المنظمات غير الحكومية، ولم ينطقوا طوال الإجراءات بكلمة «الروهينغا»، مستخدمين مصطلح «بنغالي» الذي يصفه المقرّر الخاص للأمم المتحدة المعني بميانمار بأنه ازدرائي.",
  "إنها أول قضية منذ أكثر من عقد تنظر فيها محكمة العدل الدولية في موضوع اتهام بالإبادة الجماعية (اتفاقية منع الإبادة الجماعية لعام 1948، المادة التاسعة). وتكمن قوتها في مبدأ erga omnes partes: فغامبيا، وهي دولة بعيدة وغير معنية مباشرةً، تتحرك لأن لكل دولة طرف مصلحة مشتركة في منع الإبادة الجماعية والمعاقبة عليها — واجب مشترك لا شأن ثنائي. والمسار الجنائي منفصل وشخصي: ففي نوفمبر 2024 طلب المدعي العام للمحكمة الجنائية الدولية مذكرة توقيف بحق مين أونغ هلاينغ عن جريمتي الترحيل والاضطهاد بوصفهما من الجرائم ضد الإنسانية بحق الروهينغا؛ وفي فبراير 2025 أصدرت محكمة أرجنتينية مذكرات بموجب الولاية القضائية العالمية. يُضاف إلى ذلك جرائم الحرب التي وثّقتها آلية التحقيق المستقلة التابعة للأمم المتحدة — ضربات على المنازل والمستشفيات والمدارس، وحجب المساعدات كعقاب جماعي (اتفاقية جنيف الرابعة، نظام روما الأساسي). وبما أن القضية لا تزال قيد المداولة، فلا يوجد حكم: الإبادة الجماعية أثبتتها بعثة الأمم المتحدة واستُنتجت من نمط سلوك، لكن لم تفصل فيها المحكمة بعد.",
  "هنا يُقاس القانون باتساقه. سيشكّل القرار في قضية غامبيا ضد ميانمار القضيتين الأخريين للإبادة الجماعية المعروضتين أمام المحكمة نفسها — جنوب أفريقيا ضد إسرائيل وأوكرانيا ضد روسيا: الاتفاقية نفسها، وعتبة الإثبات نفسها بشأن النيّة، والسؤال نفسه عمّن يقع عليه واجب تطبيقها. لكن الاتساق يسري أيضاً داخل النزاع: فالروهينغا محاصرون بين المجلس العسكري وجيش أراكان، وتحقّق آلية الأمم المتحدة في انتهاكات جسيمة من الطرفين — إعدامات وحرق وتجنيد قسري؛ بينما تتغذّى آلة الحرب لدى المجلس العسكري على أسلحة من الصين وروسيا والهند. ومع ذلك، ومع ملايين النازحين و — بحسب أكليد (ACLED) — النزاع الأكثر تشظّياً في العالم، يظل الاهتمام الدولي هامشياً قياساً إلى حجم الأزمة. هذا بالضبط هو الفارق بين الجسامة والاهتمام الذي وُجدت هذه المنصة لتوثيقه: القانون يسري على الجميع، أو لا يسري على أحد.",
 ]}

# ===================== HE =====================
MYA['he'] = {
 'title':"בית הדין הבינלאומי לצדק דן ברצח העם של הרוהינגה",
 'quote':"»מדובר באנשים אמיתיים, סיפורים אמיתיים, קבוצה אמיתית של בני אדם.« — דאודה ג׳אלו, שר המשפטים של גמביה, בבית הדין",
 'labels':LABELS['he'],
 'bodies':[
  "חמש שנים אחרי ההפיכה של פברואר 2021, מיאנמר נותרת אחת מחירומי הומניטריים הרחבים והנעקבים פחות בעולם: כ-5.2 מיליון עקורים, חוסר ביטחון תזונתי חמור, ותקיפות אוויריות על אזרחים שעלו מעשרות בודדות בשנה הראשונה להפיכה ליותר מ-3,300 בשנים 2025-26, עם יותר מ-3,800 אזרחים שנהרגו מתקיפות אוויר בלבד. לאחר בחירות שנערכו בין דצמבר 2025 לינואר 2026 ב-263 בלבד מתוך 330 הנפות — כמעט כולן באזורים בשליטה צבאית, כשהליגה הלאומית לדמוקרטיה ועשרות מפלגות אופוזיציה הודרו ורבים ממנהיגיהן עדיין עצורים — נעשה מנהיג ההפיכה מין אונג הליינג לנשיא באפריל 2026; הנציב העליון של האו״ם לזכויות אדם, פולקר טירק, אמר כי ההליך לא כיבד את זכויות היסוד של האזרחים, וה-International Crisis Group מתאר אותו כחזית אזרחית שמאחוריה הצבא שומר על השליטה. במישור המשפטי, בין 12 ל-29 בינואר 2026 קיים בית הדין הבינלאומי לצדק את הדיונים לגופו של עניין בתיק גמביה נגד מיאנמר, מכוח אמנת מניעת רצח העם, בגין מסע 2017 נגד מיעוט הרוהינגה המוסלמי — יותר מ-700,000 בני אדם שנמלטו לבנגלדש, כשכוונת רצח עם נקבעה בידי משלחת החקירה של האו״ם. פסק דין צפוי במהלך 2026. מיאנמר דוחה את ההאשמות: עורכי דינה הזהירו מפני קריאות סלקטיביות והסתמכות יתר על דוחות ארגונים לא-ממשלתיים, ולאורך ההליך מעולם לא הגו את המילה «רוהינגה», אלא השתמשו במונח «בנגלי», שהכתב המיוחד של האו״ם למיאנמר מגדיר כמשפיל.",
  "זהו התיק הראשון בלמעלה מעשור שבו בית הדין הבינלאומי לצדק בוחן לגופה האשמה ברצח עם (אמנת מניעת רצח העם מ-1948, סעיף 9). כוחו טמון בעקרון erga omnes partes: גמביה, מדינה רחוקה ולא מעורבת, פועלת משום שלכל מדינה צד יש אינטרס משותף במניעת רצח עם ובענישתו — חובה משותפת, לא עניין דו-צדדי. המסלול הפלילי נפרד ואישי: בנובמבר 2024 ביקש התובע של בית הדין הפלילי הבינלאומי צו מעצר נגד מין אונג הליינג בגין פשעים נגד האנושות של גירוש ורדיפת הרוהינגה; בפברואר 2025 הוציא בית משפט בארגנטינה צווים מכוח סמכות שיפוט אוניברסלית. לאלה מתווספים פשעי המלחמה שתיעד מנגנון החקירה העצמאי של האו״ם — תקיפות על בתים, בתי חולים ובתי ספר, וחסימת סיוע כעונש קולקטיבי (אמנת ז׳נבה הרביעית, חוקת רומא). מאחר שהתיק עדיין בדיון, אין פסק דין: רצח העם נקבע בידי משלחת האו״ם והוסק מדפוס התנהגות, אך טרם נפסק בידי בית הדין.",
  "כאן נמדד הדין בעקביותו. ההכרעה בגמביה נגד מיאנמר תעצב את שני תיקי רצח העם האחרים התלויים בפני אותו בית דין — דרום אפריקה נגד ישראל ואוקראינה נגד רוסיה: אותה אמנה, אותו רף הוכחה לכוונה, אותה שאלה מי חב בחובה ליישמה. אך העקביות חלה גם בתוך הסכסוך: הרוהינגה לכודים בין החונטה לבין צבא אראקאן, ומנגנון האו״ם חוקר הפרות חמורות של שני הצדדים — הוצאות להורג, הצתות, גיוס בכפייה; בעוד מכונת המלחמה של החונטה ניזונה מנשק של סין, רוסיה והודו. ובכל זאת, עם מיליוני עקורים ו — לפי ACLED — הסכסוך המפוצל ביותר בעולם, תשומת הלב הבינלאומית נותרת שולית ביחס להיקף המשבר. זהו בדיוק הפער בין החומרה לתשומת הלב שהפלטפורמה הזו קיימת כדי לתעד: הדין חל על הכול, או שאינו חל על איש.",
 ]}

# ===================== RU =====================
MYA['ru'] = {
 'title':"Международный Суд совещается по делу о геноциде рохинджа",
 'quote':"«Речь идёт о реальных людях, реальных историях, реальной группе людей.» — Давда Джаллоу, министр юстиции Гамбии, в Международном Суде",
 'labels':LABELS['ru'],
 'bodies':[
  "Спустя пять лет после переворота февраля 2021 года Мьянма остаётся одной из крупнейших и наименее освещаемых гуманитарных чрезвычайных ситуаций в мире: почти 5,2 миллиона перемещённых лиц, острая нехватка продовольствия и авиаудары по гражданским, число которых выросло с нескольких десятков в первый год переворота до более чем 3300 в 2025-26 годах, причём только от авиаударов погибли свыше 3800 мирных жителей. После выборов, проведённых с декабря 2025 по январь 2026 года лишь в 263 из 330 округов — почти все в районах под военным контролем, с отстранением Национальной лиги за демократию и десятков оппозиционных партий и при многих по-прежнему задержанных лидерах — лидер переворота Мин Аун Хлайн в апреле 2026 года стал президентом; Верховный комиссар ООН по правам человека Фолькер Тюрк заявил, что процесс не обеспечил уважение основных прав граждан, а International Crisis Group описывает его как гражданский фасад, за которым военные сохраняют контроль. На судебном фронте, с 12 по 29 января 2026 года Международный Суд провёл слушания по существу в деле «Гамбия против Мьянмы» по Конвенции о геноциде в связи с кампанией 2017 года против мусульманского меньшинства рохинджа — более 700 000 человек бежали в Бангладеш, и Миссия ООН по установлению фактов констатировала геноцидальный умысел. Решение ожидается в течение 2026 года. Мьянма отвергает обвинения: её юристы предостерегли от избирательного прочтения и чрезмерной опоры на доклады НПО и на протяжении процесса ни разу не произнесли слово «рохинджа», употребляя термин «бенгальцы», который Специальный докладчик ООН по Мьянме называет уничижительным.",
  "Это первое за более чем десятилетие дело, в котором Международный Суд рассматривает обвинение в геноциде по существу (Конвенция о геноциде 1948 года, ст. IX). Его сила — в принципе erga omnes partes: Гамбия, далёкое и не вовлечённое государство, действует потому, что у каждого государства-участника есть общий интерес в предупреждении и наказании геноцида — это общая обязанность, а не двустороннее дело. Уголовный путь отдельный и персональный: в ноябре 2024 года Прокурор Международного уголовного суда запросил ордер на арест Мин Аун Хлайна за преступления против человечности в виде депортации и преследования рохинджа; в феврале 2025 года аргентинский суд выдал ордера на основании универсальной юрисдикции. К этому добавляются военные преступления, задокументированные Независимым механизмом ООН по расследованию, — удары по домам, больницам и школам, блокирование помощи как коллективное наказание (IV Женевская конвенция, Римский статут). Поскольку дело ещё на стадии совещания, решения нет: геноцид констатирован Миссией ООН и выведен из модели поведения, но ещё не вынесен Судом.",
  "Здесь право измеряется своей последовательностью. Решение по делу «Гамбия против Мьянмы» определит два других дела о геноциде, находящихся на рассмотрении того же Суда, — «ЮАР против Израиля» и «Украина против России»: та же Конвенция, тот же стандарт доказывания умысла, тот же вопрос о том, на ком лежит обязанность её применять. Но последовательность действует и внутри конфликта: рохинджа зажаты между хунтой и Араканской армией, и Механизм ООН расследует тяжкие нарушения обеих сторон — казни, поджоги, принудительную вербовку; тогда как военная машина хунты питается оружием из Китая, России и Индии. И всё же, при миллионах перемещённых и — по данным ACLED — самом фрагментированном конфликте в мире, международное внимание остаётся незначительным в сравнении с масштабом кризиса. Это именно тот разрыв между тяжестью и вниманием, ради документирования которого существует эта платформа: право действует для всех или ни для кого.",
 ]}

TAGS = ['Myanmar','Rohingya','Genocidio','ONU','Diritto internazionale']
