# -*- coding: utf-8 -*-
# Dati notizia nd-ns — Nord Stream: incriminazione tedesca (Karlsruhe, 30 giu 2026)
# Pezzo stretto e ancorato. «Autorità statali ucraine» = tesi accusatoria contestata, non condanna.
import html as _html
_AJ="https://www.aljazeera.com/news/2026/7/2/german-prosecutors-allege-ukraine-ordered-nord-stream-pipeline-attack"
_WT="https://www.washingtontimes.com/news/2026/jul/2/german-prosecutors-charge-former-ukrainian-officer-nord-stream/"
_UP="https://www.pravda.com.ua/eng/news/2026/07/02/8042079/"
_EP="https://www.eurointegration.com.ua/eng/news/2026/07/2/7240830/"
_FT={'it':'Fonti','en':'Sources','fr':'Sources','de':'Quellen','es':'Fuentes','pt':'Fontes','tr':'Kaynaklar','zh':'来源','ar':'المصادر','he':'מקורות','ru':'Источники'}
def _a(u,l): return '<a href="%s" target="_blank" rel="noopener noreferrer">%s</a>'%(u,_html.escape(l))
LANGS=['it','en','fr','de','es','pt','tr','zh','ar','he','ru']
SRC={l:'%s: %s · %s · %s · %s'%(_FT[l],_a(_AJ,'Al Jazeera'),_a(_WT,'Washington Times'),_a(_UP,'Ukrainska Pravda'),_a(_EP,'European Pravda')) for l in LANGS}
DATE={'it':'Luglio 2026','en':'July 2026','fr':'Juillet 2026','de':'Juli 2026','es':'Julio de 2026','pt':'Julho de 2026','tr':'Temmuz 2026','zh':'2026年7月','ar':'يوليو 2026','he':'יולי 2026','ru':'Июль 2026'}
SHARE={'it':'Condividi','en':'Share','fr':'Partager','de':'Teilen','es':'Compartir','pt':'Partilhar','tr':'Paylaş','zh':'分享','ar':'مشاركة','he':'שיתוף','ru':'Поделиться'}
READ={'it':"Leggi l'analisi",'en':'Read the analysis','fr':"Lire l'analyse",'de':'Analyse lesen','es':'Leer el análisis','pt':'Ler a análise','tr':'Analizi oku','zh':'阅读分析','ar':'اقرأ التحليل','he':'קראו את הניתוח','ru':'Читать анализ'}
FLAB=dict(_FT)
LABELS={'it':['Il fatto','Commento giuridico','Implicazioni'],'en':['The fact','Legal commentary','Implications'],'fr':['Le fait','Commentaire juridique','Implications'],'de':['Der Sachverhalt','Rechtlicher Kommentar','Konsequenzen'],'es':['El hecho','Comentario jurídico','Implicaciones'],'pt':['O facto','Comentário jurídico','Implicações'],'tr':['Olgu','Hukuki yorum','Sonuçlar'],'zh':['事实','法律评注','影响'],'ar':['الواقعة','تعليق قانوني','التبعات'],'he':['העובדה','פרשנות משפטית','השלכות'],'ru':['Факт','Правовой комментарий','Последствия']}
NS={}

NS['it']={'title':"Nord Stream: la Germania incrimina un ex ufficiale ucraino per il sabotaggio come crimine di guerra",
 'quote':"«Non temiamo l'accusa: chiediamo che i fatti siano accertati, e pubblicamente.» — Nicola Canestrini, avvocato della difesa",'labels':LABELS['it'],'bodies':[
 "Il 30 giugno 2026 la Procura federale tedesca di Karlsruhe ha formalizzato, davanti al tribunale anseatico di Amburgo, l'accusa contro il cittadino ucraino Serhii K. (nei media Serhii Kuznietsov), ex ufficiale delle forze armate ucraine, per concorso in un crimine di guerra: attacco contro beni civili — un'infrastruttura energetica —, esplosione, distruzione di opere, interruzione di servizi pubblici. Secondo la Procura, dopo l'inizio dell'invasione russa del febbraio 2022, K. e altri militari, «per conto di autorità statali ucraine», pianificarono la distruzione dei gasdotti Nord Stream 1 e 2 per interrompere in modo permanente le forniture di gas e privare Mosca dei proventi con cui finanziare la guerra. Il gruppo — sommozzatori, uno skipper, un esperto di esplosivi — avrebbe usato il veliero Andromeda, salpato da Rostock con documenti falsi, per collocare le cariche al largo dell'isola danese di Bornholm; le esplosioni del 26 settembre 2022 distrussero tre delle quattro condotte. Serhii K. nega ogni coinvolgimento e afferma di essere stato in Ucraina; la difesa invoca l'immunità funzionale in quanto militare. Kyiv nega qualsiasi coinvolgimento statale; il presidente Zelensky ha detto che è «troppo presto» per commentare, non avendo ricevuto i dettagli.",
 "La qualifica è pesante e precisa: non un danneggiamento, ma un crimine di guerra. La Procura la fonda sul fatto che il sabotaggio è avvenuto dentro un conflitto armato e che colpire beni civili — il principio di distinzione — è vietato dal diritto umanitario (IV Convenzione di Ginevra) e configura crimine di guerra ai sensi dello Statuto di Roma. Ma l'atto d'accusa va oltre l'esecutore: individua un livello statale — «autorità statali ucraine» —, ipotesi che Kyiv respinge. Qui la cautela è d'obbligo: è un'imputazione, non una condanna; vale la presunzione d'innocenza, e l'attribuzione allo Stato ucraino è la tesi della Procura, contestata, non un fatto accertato. Anche l'immunità funzionale invocata dalla difesa — se un militare che agisce per lo Stato risponda personalmente — è un nodo aperto del diritto internazionale.",
 "Il valore di questo caso, per chi guarda al diritto e non alle bandiere, è la sua simmetria. Un procuratore occidentale contesta un crimine di guerra al cittadino di un Paese alleato, non di un nemico: è un test pubblico su se lo stato di diritto valga in modo uniforme anche dentro l'alleanza. E impone di nominare l'asimmetria che di solito resta muta: l'attacco a un'infrastruttura finisce in un'aula di Amburgo, mentre gli attacchi sistematici russi alle infrastrutture civili ucraine — centrali elettriche, reti idriche — non sono processati in alcun tribunale occidentale. Il principio di distinzione, però, non conosce parti: vale per chi ha fatto saltare un gasdotto e per chi bombarda una rete elettrica. Il diritto vale per l'alleato come per l'avversario, o non vale per nessuno."]}

NS['en']={'title':"Nord Stream: Germany charges a former Ukrainian officer with sabotage as a war crime",
 'quote':"“We do not fear the indictment: we demand that the facts be established, and in public.” — Nicola Canestrini, defence lawyer",'labels':LABELS['en'],'bodies':[
 "On 30 June 2026 the German Federal Prosecutor in Karlsruhe filed charges, before the Hanseatic regional court in Hamburg, against the Ukrainian national Serhii K. (named in the media as Serhii Kuznietsov), a former officer of the Ukrainian armed forces, for complicity in a war crime: an attack on civilian objects — an energy infrastructure — causing an explosion, destroying structures and disrupting public services. According to the prosecutors, after the start of Russia's invasion in February 2022, K. and other servicemen, “on behalf of Ukrainian state authorities,” planned the destruction of the Nord Stream 1 and 2 pipelines to permanently halt gas supplies and deprive Moscow of the revenue to finance the war. The group — divers, a skipper, an explosives expert — allegedly used the sailing yacht Andromeda, which left Rostock on forged documents, to place the charges off the Danish island of Bornholm; the explosions of 26 September 2022 destroyed three of the four lines. Serhii K. denies any involvement and says he was in Ukraine; his defence invokes functional immunity as a serviceman. Kyiv denies any state involvement; President Zelensky said it was “too early” to comment, having not received the details.",
 "The charge is heavy and precise: not property damage, but a war crime. The prosecutors base it on the fact that the sabotage took place within an armed conflict and that striking civilian objects — the principle of distinction — is prohibited by humanitarian law (Fourth Geneva Convention) and constitutes a war crime under the Rome Statute. But the indictment goes beyond the perpetrator: it identifies a state level — “Ukrainian state authorities” — a claim Kyiv rejects. Caution is required here: it is an indictment, not a conviction; the presumption of innocence applies, and the attribution to the Ukrainian State is the prosecution's contested thesis, not an established fact. The functional immunity invoked by the defence — whether a serviceman acting for the State is personally liable — is likewise an open question of international law.",
 "The value of this case, for those who look at the law and not at flags, is its symmetry. A Western prosecutor charges a citizen of an allied country, not of an enemy, with a war crime: it is a public test of whether the rule of law applies uniformly even within the alliance. And it forces one to name the asymmetry that usually stays silent: the attack on one piece of infrastructure ends up in a Hamburg courtroom, while Russia's systematic attacks on Ukrainian civilian infrastructure — power plants, water networks — are prosecuted in no Western court. The principle of distinction, however, knows no sides: it holds for whoever blew up a pipeline and for whoever bombs a power grid. The law applies to the ally as to the adversary, or it applies to no one."]}

NS['fr']={'title':"Nord Stream : l'Allemagne inculpe un ex-officier ukrainien pour le sabotage comme crime de guerre",
 'quote':"« Nous ne craignons pas l'accusation : nous demandons que les faits soient établis, et publiquement. » — Nicola Canestrini, avocat de la défense",'labels':LABELS['fr'],'bodies':[
 "Le 30 juin 2026, le Parquet fédéral allemand de Karlsruhe a formalisé, devant le tribunal hanséatique de Hambourg, l'accusation contre le ressortissant ukrainien Serhii K. (Serhii Kuznietsov dans les médias), ancien officier des forces armées ukrainiennes, pour complicité de crime de guerre : attaque contre des biens civils — une infrastructure énergétique —, explosion, destruction d'ouvrages, interruption de services publics. Selon le Parquet, après le début de l'invasion russe de février 2022, K. et d'autres militaires, « pour le compte d'autorités d'État ukrainiennes », ont planifié la destruction des gazoducs Nord Stream 1 et 2 pour interrompre durablement les livraisons de gaz et priver Moscou des revenus finançant la guerre. Le groupe — des plongeurs, un skipper, un expert en explosifs — aurait utilisé le voilier Andromeda, parti de Rostock avec de faux documents, pour poser les charges au large de l'île danoise de Bornholm ; les explosions du 26 septembre 2022 ont détruit trois des quatre conduites. Serhii K. nie toute implication et affirme avoir été en Ukraine ; la défense invoque l'immunité fonctionnelle en tant que militaire. Kyiv nie tout rôle de l'État ; le président Zelensky a dit qu'il était « trop tôt » pour commenter, n'ayant pas reçu les détails.",
 "La qualification est lourde et précise : non un dommage, mais un crime de guerre. Le Parquet la fonde sur le fait que le sabotage a eu lieu dans un conflit armé et que frapper des biens civils — le principe de distinction — est interdit par le droit humanitaire (IVe Convention de Genève) et constitue un crime de guerre au sens du Statut de Rome. Mais l'acte d'accusation va au-delà de l'exécutant : il désigne un niveau étatique — « autorités d'État ukrainiennes » —, hypothèse que Kyiv rejette. La prudence s'impose ici : c'est une inculpation, non une condamnation ; la présomption d'innocence s'applique, et l'attribution à l'État ukrainien est la thèse contestée du Parquet, non un fait établi. L'immunité fonctionnelle invoquée par la défense — un militaire agissant pour l'État répond-il personnellement — est aussi une question ouverte du droit international.",
 "La valeur de cette affaire, pour qui regarde le droit et non les drapeaux, tient à sa symétrie. Un procureur occidental accuse d'un crime de guerre le citoyen d'un pays allié, non d'un ennemi : c'est un test public sur l'application uniforme de l'État de droit, même au sein de l'alliance. Et elle oblige à nommer l'asymétrie qui reste d'ordinaire muette : l'attaque d'une infrastructure finit dans un prétoire de Hambourg, tandis que les attaques russes systématiques contre les infrastructures civiles ukrainiennes — centrales électriques, réseaux d'eau — ne sont jugées par aucun tribunal occidental. Le principe de distinction, pourtant, ne connaît pas de camps : il vaut pour qui a fait sauter un gazoduc et pour qui bombarde un réseau électrique. Le droit vaut pour l'allié comme pour l'adversaire, ou il ne vaut pour personne."]}

NS['de']={'title':"Nord Stream: Deutschland klagt einen früheren ukrainischen Offizier wegen Sabotage als Kriegsverbrechen an",
 'quote':"„Wir fürchten die Anklage nicht: Wir fordern, dass die Fakten festgestellt werden, und zwar öffentlich.“ — Nicola Canestrini, Verteidiger",'labels':LABELS['de'],'bodies':[
 "Am 30. Juni 2026 erhob die deutsche Bundesanwaltschaft in Karlsruhe vor dem Hanseatischen Oberlandesgericht in Hamburg Anklage gegen den ukrainischen Staatsbürger Serhii K. (in den Medien Serhii Kuznietsov), einen früheren Offizier der ukrainischen Streitkräfte, wegen Beihilfe zu einem Kriegsverbrechen: Angriff auf zivile Objekte — eine Energieinfrastruktur —, Herbeiführen einer Explosion, Zerstörung von Bauwerken, Störung öffentlicher Dienste. Laut Anklage entwickelten K. und andere Militärangehörige nach Beginn der russischen Invasion im Februar 2022 „im Auftrag ukrainischer staatlicher Stellen“ einen Plan zur Zerstörung der Pipelines Nord Stream 1 und 2, um die Gaslieferungen dauerhaft zu unterbrechen und Moskau die Einnahmen zur Kriegsfinanzierung zu entziehen. Die Gruppe — Taucher, ein Skipper, ein Sprengstoffexperte — soll die Segelyacht Andromeda benutzt haben, die mit gefälschten Papieren aus Rostock auslief, um die Sätze vor der dänischen Insel Bornholm anzubringen; die Explosionen vom 26. September 2022 zerstörten drei der vier Stränge. Serhii K. bestreitet jede Beteiligung und gibt an, in der Ukraine gewesen zu sein; die Verteidigung beruft sich auf funktionale Immunität als Militärangehöriger. Kyjiw bestreitet jede staatliche Beteiligung; Präsident Selenskyj sagte, es sei „zu früh“ für einen Kommentar, da er die Details nicht erhalten habe.",
 "Die Einstufung ist schwer und präzise: keine Sachbeschädigung, sondern ein Kriegsverbrechen. Die Anklage stützt sie darauf, dass die Sabotage innerhalb eines bewaffneten Konflikts geschah und dass der Angriff auf zivile Objekte — der Unterscheidungsgrundsatz — vom humanitären Recht (IV. Genfer Abkommen) verboten ist und nach dem Römischen Statuts ein Kriegsverbrechen darstellt. Doch die Anklage geht über den Ausführenden hinaus: sie benennt eine staatliche Ebene — „ukrainische staatliche Stellen“ —, was Kyjiw zurückweist. Vorsicht ist hier geboten: es ist eine Anklage, keine Verurteilung; die Unschuldsvermutung gilt, und die Zuschreibung an den ukrainischen Staat ist die bestrittene These der Anklage, keine feststehende Tatsache. Auch die von der Verteidigung geltend gemachte funktionale Immunität — ob ein für den Staat handelnder Soldat persönlich haftet — ist eine offene Frage des Völkerrechts.",
 "Der Wert dieses Falls liegt für den, der auf das Recht und nicht auf Fahnen schaut, in seiner Symmetrie. Ein westlicher Staatsanwalt klagt den Bürger eines verbündeten Landes, nicht eines Feindes, eines Kriegsverbrechens an: ein öffentlicher Test, ob der Rechtsstaat auch innerhalb des Bündnisses einheitlich gilt. Und er zwingt dazu, die sonst stumme Asymmetrie zu benennen: der Angriff auf eine Infrastruktur landet in einem Hamburger Gerichtssaal, während Russlands systematische Angriffe auf ukrainische zivile Infrastruktur — Kraftwerke, Wassernetze — vor keinem westlichen Gericht verhandelt werden. Der Unterscheidungsgrundsatz aber kennt keine Seiten: er gilt für den, der eine Pipeline sprengte, und für den, der ein Stromnetz bombardiert. Das Recht gilt für den Verbündeten wie für den Gegner, oder es gilt für niemanden."]}

NS['es']={'title':"Nord Stream: Alemania acusa a un exoficial ucraniano por el sabotaje como crimen de guerra",
 'quote':"«No tememos la acusación: pedimos que los hechos se establezcan, y públicamente.» — Nicola Canestrini, abogado de la defensa",'labels':LABELS['es'],'bodies':[
 "El 30 de junio de 2026 la Fiscalía Federal alemana de Karlsruhe formalizó, ante el tribunal hanseático de Hamburgo, la acusación contra el ciudadano ucraniano Serhii K. (en los medios Serhii Kuznietsov), exoficial de las fuerzas armadas ucranianas, por complicidad en un crimen de guerra: ataque contra bienes civiles — una infraestructura energética —, explosión, destrucción de obras, interrupción de servicios públicos. Según la Fiscalía, tras el inicio de la invasión rusa de febrero de 2022, K. y otros militares, «por cuenta de autoridades estatales ucranianas», planearon la destrucción de los gasoductos Nord Stream 1 y 2 para interrumpir de forma permanente los suministros de gas y privar a Moscú de los ingresos para financiar la guerra. El grupo — buzos, un patrón, un experto en explosivos — habría usado el velero Andromeda, salido de Rostock con documentos falsos, para colocar las cargas frente a la isla danesa de Bornholm; las explosiones del 26 de septiembre de 2022 destruyeron tres de las cuatro tuberías. Serhii K. niega toda implicación y afirma haber estado en Ucrania; la defensa invoca la inmunidad funcional como militar. Kyiv niega cualquier implicación estatal; el presidente Zelensky dijo que era «demasiado pronto» para comentar, al no haber recibido los detalles.",
 "La calificación es grave y precisa: no un daño, sino un crimen de guerra. La Fiscalía la funda en que el sabotaje ocurrió dentro de un conflicto armado y en que atacar bienes civiles — el principio de distinción — está prohibido por el derecho humanitario (IV Convenio de Ginebra) y constituye crimen de guerra según el Estatuto de Roma. Pero el escrito de acusación va más allá del ejecutor: señala un nivel estatal — «autoridades estatales ucranianas» —, hipótesis que Kyiv rechaza. Aquí es obligada la cautela: es una acusación, no una condena; rige la presunción de inocencia, y la atribución al Estado ucraniano es la tesis contestada de la Fiscalía, no un hecho establecido. También la inmunidad funcional invocada por la defensa — si un militar que actúa por el Estado responde personalmente — es un nudo abierto del derecho internacional.",
 "El valor de este caso, para quien mira el derecho y no las banderas, es su simetría. Un fiscal occidental acusa de un crimen de guerra al ciudadano de un país aliado, no de un enemigo: es una prueba pública sobre si el Estado de derecho se aplica de manera uniforme incluso dentro de la alianza. Y obliga a nombrar la asimetría que suele quedar muda: el ataque a una infraestructura acaba en una sala de Hamburgo, mientras los ataques rusos sistemáticos contra la infraestructura civil ucraniana — centrales eléctricas, redes de agua — no se juzgan en ningún tribunal occidental. El principio de distinción, sin embargo, no conoce bandos: vale para quien voló un gasoducto y para quien bombardea una red eléctrica. El derecho vale para el aliado como para el adversario, o no vale para nadie."]}

NS['pt']={'title':"Nord Stream: a Alemanha acusa um ex-oficial ucraniano pela sabotagem como crime de guerra",
 'quote':"«Não tememos a acusação: pedimos que os factos sejam apurados, e publicamente.» — Nicola Canestrini, advogado de defesa",'labels':LABELS['pt'],'bodies':[
 "Em 30 de junho de 2026 a Procuradoria Federal alemã de Karlsruhe formalizou, perante o tribunal hanseático de Hamburgo, a acusação contra o cidadão ucraniano Serhii K. (nos media Serhii Kuznietsov), ex-oficial das forças armadas ucranianas, por cumplicidade num crime de guerra: ataque a bens civis — uma infraestrutura energética —, explosão, destruição de obras, interrupção de serviços públicos. Segundo a Procuradoria, após o início da invasão russa de fevereiro de 2022, K. e outros militares, «por conta de autoridades estatais ucranianas», planearam a destruição dos gasodutos Nord Stream 1 e 2 para interromper de forma permanente os fornecimentos de gás e privar Moscovo das receitas para financiar a guerra. O grupo — mergulhadores, um skipper, um perito em explosivos — teria usado o veleiro Andromeda, saído de Rostock com documentos falsos, para colocar as cargas ao largo da ilha dinamarquesa de Bornholm; as explosões de 26 de setembro de 2022 destruíram três das quatro condutas. Serhii K. nega qualquer envolvimento e afirma ter estado na Ucrânia; a defesa invoca a imunidade funcional enquanto militar. Kyiv nega qualquer envolvimento estatal; o presidente Zelensky disse ser «demasiado cedo» para comentar, por não ter recebido os detalhes.",
 "A qualificação é pesada e precisa: não um dano, mas um crime de guerra. A Procuradoria funda-a no facto de a sabotagem ter ocorrido dentro de um conflito armado e de atacar bens civis — o princípio da distinção — ser proibido pelo direito humanitário (IV Convenção de Genebra) e constituir crime de guerra nos termos do Estatuto de Roma. Mas a acusação vai além do executor: aponta um nível estatal — «autoridades estatais ucranianas» —, hipótese que Kyiv rejeita. Aqui impõe-se cautela: é uma acusação, não uma condenação; vale a presunção de inocência, e a atribuição ao Estado ucraniano é a tese contestada da Procuradoria, não um facto apurado. Também a imunidade funcional invocada pela defesa — se um militar que age pelo Estado responde pessoalmente — é um nó em aberto do direito internacional.",
 "O valor deste caso, para quem olha o direito e não as bandeiras, está na sua simetria. Um procurador ocidental acusa de um crime de guerra o cidadão de um país aliado, não de um inimigo: é um teste público sobre se o Estado de direito se aplica de modo uniforme mesmo dentro da aliança. E obriga a nomear a assimetria que costuma ficar muda: o ataque a uma infraestrutura acaba numa sala de Hamburgo, enquanto os ataques russos sistemáticos à infraestrutura civil ucraniana — centrais elétricas, redes de água — não são julgados em nenhum tribunal ocidental. O princípio da distinção, porém, não conhece lados: vale para quem explodiu um gasoduto e para quem bombardeia uma rede elétrica. O direito vale para o aliado como para o adversário, ou não vale para ninguém."]}

NS['tr']={'title':"Nord Stream: Almanya, eski bir Ukraynalı subayı sabotaj nedeniyle savaş suçuyla suçluyor",
 'quote':"«Suçlamadan korkmuyoruz: olguların, hem de aleni biçimde saptanmasını istiyoruz.» — Nicola Canestrini, savunma avukatı",'labels':LABELS['tr'],'bodies':[
 "30 Haziran 2026'da Almanya Federal Savcılığı, Hamburg'daki Hansa bölge mahkemesi önünde, Ukrayna vatandaşı Serhii K. (medyada Serhii Kuznietsov), Ukrayna silahlı kuvvetlerinin eski bir subayı hakkında bir savaş suçuna iştirakten iddianame düzenledi: sivil nesnelere — bir enerji altyapısına — saldırı, patlamaya yol açma, yapıların tahribi, kamu hizmetlerinin kesintiye uğratılması. Savcılığa göre, Şubat 2022'deki Rus işgalinin başlamasının ardından K. ve diğer askerler, «Ukrayna devlet makamları adına», gaz sevkiyatını kalıcı olarak durdurmak ve Moskova'yı savaşı finanse edecek gelirlerden yoksun bırakmak amacıyla Nord Stream 1 ve 2 boru hatlarını yok etme planı geliştirdi. Grup — dalgıçlar, bir kaptan, bir patlayıcı uzmanı — sahte belgelerle Rostock'tan ayrılan Andromeda adlı yelkenliyi kullanarak Danimarka'nın Bornholm adası açıklarına yükleri yerleştirmiş olacak; 26 Eylül 2022'deki patlamalar dört hattan üçünü tahrip etti. Serhii K. her türlü katılımı reddediyor ve Ukrayna'da olduğunu söylüyor; savunma, asker sıfatıyla işlevsel dokunulmazlığı öne sürüyor. Kyiv her türlü devlet katılımını yadsıyor; Cumhurbaşkanı Zelenski, ayrıntıları almadığı için yorum yapmanın «çok erken» olduğunu söyledi.",
 "Nitelendirme ağır ve kesin: bir hasar değil, bir savaş suçu. Savcılık bunu, sabotajın bir silahlı çatışma içinde gerçekleşmesine ve sivil nesnelere saldırmanın — ayrım ilkesi — insancıl hukukça (IV. Cenevre Sözleşmesi) yasak olup Roma Statüsü uyarınca savaş suçu oluşturmasına dayandırıyor. Ancak iddianame failin ötesine geçiyor: bir devlet düzeyini — «Ukrayna devlet makamları» — işaret ediyor; Kyiv bunu reddediyor. Burada temkin şart: bu bir iddianamedir, bir mahkûmiyet değil; masumiyet karinesi geçerlidir ve Ukrayna devletine atıf, Savcılığın itiraza uğrayan tezidir, saptanmış bir olgu değil. Savunmanın öne sürdüğü işlevsel dokunulmazlık — devlet adına hareket eden bir askerin kişisel olarak sorumlu olup olmadığı — da uluslararası hukukun açık bir düğümüdür.",
 "Bu davanın değeri, bayraklara değil hukuka bakan için, simetrisindedir. Batılı bir savcı, bir düşmanın değil, müttefik bir ülkenin vatandaşını savaş suçuyla suçluyor: hukuk devletinin ittifak içinde bile tekdüze uygulanıp uygulanmadığının aleni bir sınavı. Ve genelde suskun kalan asimetriyi adlandırmayı zorunlu kılıyor: bir altyapıya saldırı Hamburg'da bir salona düşerken, Rusya'nın Ukrayna sivil altyapısına — elektrik santralleri, su şebekeleri — yönelik sistematik saldırıları hiçbir Batı mahkemesinde yargılanmıyor. Oysa ayrım ilkesi taraf tanımaz: bir boru hattını uçuran için de, bir elektrik şebekesini bombalayan için de geçerlidir. Hukuk, müttefik için de hasım için de geçerlidir ya da hiç kimse için."]}

NS['zh']={'title':"北溪：德国以战争罪起诉一名乌克兰前军官参与破坏",
 'quote':"“我们不惧怕指控：我们要求查明事实，而且是公开地查明。” —— 尼古拉·卡内斯特里尼，辩护律师",'labels':LABELS['zh'],'bodies':[
 "2026年6月30日，德国卡尔斯鲁厄联邦检察院在汉堡的汉萨地区法院对乌克兰公民塞尔希·K.（媒体称塞尔希·库兹涅佐夫）提起公诉。此人是乌克兰武装部队的前军官，被控参与一项战争罪：攻击民用目标——一处能源基础设施——引发爆炸、毁坏建筑物、扰乱公共服务。据检方称，2022年2月俄罗斯入侵开始后，K.与其他军人“受乌克兰国家当局委托”，制定了摧毁北溪1号和2号管道的计划，以永久切断天然气供应、剥夺莫斯科用于资助战争的收入。该团伙——潜水员、一名船长、一名爆破专家——据称使用了以伪造证件从罗斯托克出发的“仙女座”号帆船，在丹麦博恩霍尔姆岛附近布放炸药；2022年9月26日的爆炸摧毁了四条管道中的三条。塞尔希·K.否认任何参与，称当时身在乌克兰；辩方以其军人身份主张“职能豁免”。基辅否认任何国家层面的参与；泽连斯基总统表示，因尚未收到细节，现在评论“为时过早”。",
 "这一定性沉重而精确：不是财产损坏，而是战争罪。检方的依据是：破坏行为发生在武装冲突之中，而攻击民用目标——区分原则——为人道法（日内瓦第四公约）所禁止，并依《罗马规约》构成战争罪。但起诉超出了执行者：它指向了一个国家层级——“乌克兰国家当局”——基辅对此予以否认。此处必须审慎：这是一份起诉，而非定罪；无罪推定适用，而对乌克兰国家的归责是检方受到争议的主张，并非已查明的事实。辩方援引的职能豁免——为国家行事的军人是否需承担个人责任——同样是国际法的一个悬而未决的结。",
 "对于看重法律而非旗帜的人而言，此案的价值在于其对称性。一位西方检察官以战争罪起诉的，是一个盟国而非敌国的公民：这是对法治是否在联盟内部也一律适用的公开检验。它还迫使人们指出通常沉默的不对称：对一处基础设施的攻击被送上汉堡的法庭，而俄罗斯对乌克兰民用基础设施——发电厂、供水网络——的系统性攻击却不在任何西方法庭受审。然而区分原则不分阵营：它既适用于炸毁一条管道的人，也适用于轰炸一处电网的人。法律对盟友与对手一体适用，否则对任何人都不适用。"]}

NS['ar']={'title':"نورد ستريم: ألمانيا تتّهم ضابطاً أوكرانياً سابقاً بالتخريب بوصفه جريمة حرب",
 'quote':"«لا نخشى الاتهام: نطالب بأن تُثبَت الوقائع، وعلناً.» — نيكولا كانيستريني، محامي الدفاع",'labels':LABELS['ar'],'bodies':[
 "في 30 يونيو 2026 وجّهت النيابة الاتحادية الألمانية في كارلسروه، أمام المحكمة الهانزية في هامبورغ، الاتهام إلى المواطن الأوكراني سيرهي ك. (سيرهي كوزنيتسوف في الإعلام)، وهو ضابط سابق في القوات المسلحة الأوكرانية، بالاشتراك في جريمة حرب: هجوم على أعيان مدنية — بنية تحتية للطاقة —، وإحداث انفجار، وتدمير منشآت، وتعطيل خدمات عامة. وبحسب النيابة، فبعد بدء الغزو الروسي في فبراير 2022، وضع ك. وعسكريون آخرون، «بالنيابة عن سلطات الدولة الأوكرانية»، خطة لتدمير خطّي أنابيب نورد ستريم 1 و2 بهدف الوقف الدائم لإمدادات الغاز وحرمان موسكو من العائدات التي تموّل بها الحرب. ويُزعم أن المجموعة — غوّاصون وربّان وخبير متفجّرات — استخدمت اليخت الشراعي «أندروميدا» الذي أبحر من روستوك بوثائق مزوّرة، لزرع العبوات قبالة جزيرة بورنهولم الدنماركية؛ ودمّرت انفجارات 26 سبتمبر 2022 ثلاثة من الأنابيب الأربعة. ينفي سيرهي ك. أي تورّط ويقول إنه كان في أوكرانيا؛ ويحتجّ الدفاع بالحصانة الوظيفية بصفته عسكرياً. وتنفي كييف أي تورّط للدولة؛ وقال الرئيس زيلينسكي إنه «من المبكّر جداً» التعليق لأنه لم يتلقَّ التفاصيل.",
 "التوصيف ثقيل ودقيق: ليس إتلافاً، بل جريمة حرب. وتبني النيابة ذلك على أن التخريب وقع داخل نزاع مسلّح، وأن مهاجمة الأعيان المدنية — مبدأ التمييز — محظورة بالقانون الإنساني (اتفاقية جنيف الرابعة) وتشكّل جريمة حرب بموجب نظام روما الأساسي. لكن الاتهام يتجاوز المنفّذ: فهو يشير إلى مستوى الدولة — «سلطات الدولة الأوكرانية» — وهو ما تنفيه كييف. والحذر واجب هنا: إنه اتهام لا إدانة؛ وقرينة البراءة قائمة، ونسبة الفعل إلى الدولة الأوكرانية هي أطروحة النيابة المتنازَع عليها، لا واقعة مثبتة. كما أن الحصانة الوظيفية التي يحتجّ بها الدفاع — هل يُسأل شخصياً عسكريٌّ يتصرف باسم الدولة — عقدة مفتوحة في القانون الدولي.",
 "قيمة هذه القضية، لمن ينظر إلى القانون لا إلى الأعلام، في تماثلها. فمدّعٍ غربي يتّهم بجريمة حرب مواطن بلد حليف، لا عدوّ: إنه اختبار علني لما إذا كانت سيادة القانون تُطبَّق باطّراد حتى داخل التحالف. وهو يفرض تسمية اللاتماثل الذي يبقى صامتاً عادةً: الهجوم على بنية تحتية ينتهي في قاعة بهامبورغ، بينما الهجمات الروسية المنهجية على البنية التحتية المدنية الأوكرانية — محطات كهرباء وشبكات مياه — لا تُحاكَم أمام أي محكمة غربية. لكن مبدأ التمييز لا يعرف أطرافاً: يسري على من فجّر أنبوباً وعلى من يقصف شبكة كهرباء. القانون يسري على الحليف كما على الخصم، أو لا يسري على أحد."]}

NS['he']={'title':"נורד סטרים: גרמניה מאשימה קצין אוקראיני לשעבר בחבלה כפשע מלחמה",
 'quote':"»איננו חוששים מכתב האישום: אנו דורשים שהעובדות ייקבעו, ובפומבי.« — ניקולה קנסטריני, עורך דין ההגנה",'labels':LABELS['he'],'bodies':[
 "ב-30 ביוני 2026 הגישה התביעה הפדרלית הגרמנית בקרלסרוהה, בפני בית המשפט ההנזאתי בהמבורג, כתב אישום נגד האזרח האוקראיני סרהיי ק. (בתקשורת סרהיי קוזנייצוב), קצין לשעבר בכוחות המזוינים של אוקראינה, בגין סיוע לפשע מלחמה: תקיפת מטרות אזרחיות — תשתית אנרגיה —, גרימת פיצוץ, הריסת מבנים ושיבוש שירותים ציבוריים. לפי התביעה, לאחר תחילת הפלישה הרוסית בפברואר 2022, ק. וחיילים אחרים, »מטעם רשויות מדינה אוקראיניות«, תכננו את הרס צינורות נורד סטרים 1 ו-2 כדי לעצור לצמיתות את אספקת הגז ולשלול ממוסקבה את ההכנסות למימון המלחמה. הקבוצה — צוללנים, רב-חובל, מומחה חומרי נפץ — עשתה כביכול שימוש ביאכטת המפרש »אנדרומדה«, שיצאה מרוסטוק במסמכים מזויפים, כדי להניח את המטענים מול האי הדני בורנהולם; הפיצוצים ב-26 בספטמבר 2022 הרסו שלושה מארבעת הצינורות. סרהיי ק. מכחיש כל מעורבות ואומר שהיה באוקראינה; ההגנה טוענת לחסינות תפקודית בהיותו איש צבא. קייב מכחישה כל מעורבות מדינתית; הנשיא זלנסקי אמר ש»מוקדם מדי« להגיב, משום שלא קיבל את הפרטים.",
 "ההגדרה כבדה ומדויקת: לא נזק לרכוש, אלא פשע מלחמה. התביעה מבססת זאת על כך שהחבלה אירעה בתוך סכסוך מזוין, ושתקיפת מטרות אזרחיות — עקרון ההבחנה — אסורה לפי הדין ההומניטרי (אמנת ז'נבה הרביעית) ומהווה פשע מלחמה לפי חוקת רומא. אך כתב האישום חורג מעבר למבצע: הוא מצביע על דרג מדינתי — »רשויות מדינה אוקראיניות« — טענה שקייב דוחה. כאן נדרשת זהירות: זהו כתב אישום, לא הרשעה; חזקת החפות חלה, וייחוס המעשה למדינת אוקראינה הוא טענת התביעה השנויה במחלוקת, לא עובדה שהוכחה. גם החסינות התפקודית שההגנה טוענת לה — האם חייל הפועל בשם המדינה נושא באחריות אישית — היא סוגיה פתוחה במשפט הבינלאומי.",
 "ערכו של המקרה הזה, למי שמביט בדין ולא בדגלים, הוא בסימטריה שלו. תובע מערבי מאשים בפשע מלחמה אזרח של מדינה בעלת ברית, לא של אויב: זהו מבחן פומבי אם שלטון החוק חל באחידות אף בתוך הברית. והוא מחייב לנקוב באי-הסימטריה שנותרת בדרך כלל אילמת: התקיפה על תשתית אחת מגיעה לאולם בהמבורג, בעוד התקיפות הרוסיות השיטתיות על תשתית אזרחית אוקראינית — תחנות כוח, רשתות מים — אינן נשפטות בשום בית משפט מערבי. אך עקרון ההבחנה אינו יודע צדדים: הוא חל על מי שפוצץ צינור ועל מי שמפציץ רשת חשמל. הדין חל על בן הברית כמו על היריב, או שאינו חל על איש."]}

NS['ru']={'title':"«Северный поток»: Германия обвиняет бывшего украинского офицера в диверсии как военном преступлении",
 'quote':"«Мы не боимся обвинения: мы требуем, чтобы факты были установлены — и публично.» — Никола Канестрини, адвокат защиты",'labels':LABELS['ru'],'bodies':[
 "30 июня 2026 года Федеральная прокуратура Германии в Карлсруэ предъявила в Ганзейском земельном суде Гамбурга обвинение гражданину Украины Сергею К. (в СМИ Сергей Кузнецов), бывшему офицеру вооружённых сил Украины, в пособничестве военному преступлению: нападение на гражданские объекты — энергетическую инфраструктуру, — повлёкшее взрыв, разрушение сооружений и нарушение работы общественных служб. По версии прокуратуры, после начала российского вторжения в феврале 2022 года К. и другие военные, «по поручению государственных органов Украины», разработали план уничтожения газопроводов «Северный поток — 1» и «Северный поток — 2», чтобы навсегда прекратить поставки газа и лишить Москву доходов на финансирование войны. Группа — водолазы, шкипер, специалист по взрывчатке — якобы использовала парусную яхту «Андромеда», вышедшую из Ростока по поддельным документам, чтобы заложить заряды у датского острова Борнхольм; взрывы 26 сентября 2022 года разрушили три из четырёх ниток. Сергей К. отрицает какую-либо причастность и утверждает, что находился на Украине; защита ссылается на функциональный иммунитет как военнослужащего. Киев отрицает любую причастность государства; президент Зеленский заявил, что комментировать «слишком рано», поскольку не получил деталей.",
 "Квалификация тяжёлая и точная: не порча имущества, а военное преступление. Прокуратура обосновывает её тем, что диверсия произошла в рамках вооружённого конфликта и что нападение на гражданские объекты — принцип различения — запрещено гуманитарным правом (IV Женевская конвенция) и образует военное преступление по Римскому статуту. Но обвинение идёт дальше исполнителя: оно указывает на государственный уровень — «государственные органы Украины», — что Киев отвергает. Здесь необходима осторожность: это обвинение, а не приговор; действует презумпция невиновности, а приписывание деяния украинскому государству — оспариваемый тезис прокуратуры, а не установленный факт. Функциональный иммунитет, на который ссылается защита, — несёт ли личную ответственность военный, действующий от имени государства, — также открытый узел международного права.",
 "Ценность этого дела для того, кто смотрит на право, а не на флаги, — в его симметрии. Западный прокурор обвиняет в военном преступлении гражданина союзной, а не вражеской страны: это публичная проверка того, применяется ли верховенство права единообразно даже внутри альянса. И оно вынуждает назвать асимметрию, которая обычно молчит: нападение на одну инфраструктуру попадает в зал суда в Гамбурге, тогда как систематические российские удары по украинской гражданской инфраструктуре — электростанциям, водопроводным сетям — не рассматриваются ни одним западным судом. Однако принцип различения не знает сторон: он действует и для того, кто взорвал трубопровод, и для того, кто бомбит электросеть. Право действует для союзника так же, как для противника, — или не действует ни для кого."]}

TAGS=['Russia–Ucraina','Diritto internazionale']
