# -*- coding: utf-8 -*-
# Dati notizia nd-sd — Sudan: l'ONU avverte sul rischio a El-Obeid (Türk, 18 giu 2026)
# Schema identico a mya.py/rdc.py. REGOLA DI FERRO: fonti reali e verificate; giudizi attribuiti.

import html as _html

_OHCHR = "https://www.ohchr.org/en/press-releases/2026/06/sudan-imminent-offensive-el-obeid-must-be-halted-turk-warns-catastrophic"
_UNNEWS= "https://news.un.org/en/story/2026/06/1167752"
_AJ    = "https://www.aljazeera.com/news/2026/6/18/dozens-of-countries-warn-of-atrocities-amid-escalation-in-sudans-el-obeid"
_AJ_AR = "https://www.aljazeera.net/news/2026/6/18/%D8%AA%D8%AD%D8%B0%D9%8A%D8%B1%D8%A7%D8%AA-%D8%A3%D9%85%D9%85%D9%8A%D8%A9-%D9%88%D8%BA%D8%B1%D8%A8%D9%8A%D8%A9-%D9%85%D9%86-%D9%87%D8%AC%D9%88%D9%85-%D9%88%D8%B4%D9%8A%D9%83"
_HRW   = "https://www.hrw.org/news/2026/06/26/sudan-urgently-address-the-situation-in-and-around-el-obeid-take-bold-steps-towards"

_FT = {'it':'Fonti','en':'Sources','fr':'Sources','de':'Quellen','es':'Fuentes','pt':'Fontes',
       'tr':'Kaynaklar','zh':'来源','ar':'المصادر','he':'מקורות','ru':'Источники'}
def _a(url,label):
    return '<a href="%s" target="_blank" rel="noopener noreferrer">%s</a>'%(url,_html.escape(label))

LANGS=['it','en','fr','de','es','pt','tr','zh','ar','he','ru']
SRC={}
for _l in LANGS:
    aj=_a(_AJ_AR,'الجزيرة') if _l=='ar' else _a(_AJ,'Al Jazeera')
    SRC[_l]='%s: %s · %s · %s · %s'%(_FT[_l], aj, _a(_UNNEWS,'UN News'), _a(_OHCHR,'OHCHR'), _a(_HRW,'HRW'))

DATE = {'it':'Giugno 2026','en':'June 2026','fr':'Juin 2026','de':'Juni 2026','es':'Junio de 2026',
        'pt':'Junho de 2026','tr':'Haziran 2026','zh':'2026年6月','ar':'يونيو 2026','he':'יוני 2026','ru':'Июнь 2026'}
SHARE = {'it':'Condividi','en':'Share','fr':'Partager','de':'Teilen','es':'Compartir','pt':'Partilhar',
         'tr':'Paylaş','zh':'分享','ar':'مشاركة','he':'שיתוף','ru':'Поделиться'}
READ  = {'it':"Leggi l'analisi",'en':'Read the analysis','fr':"Lire l'analyse",'de':'Analyse lesen',
         'es':'Leer el análisis','pt':'Ler a análise','tr':'Analizi oku','zh':'阅读分析',
         'ar':'اقرأ التحليل','he':'קראו את הניתוח','ru':'Читать анализ'}
FLAB  = dict(_FT)
LABELS = {
 'it':['Il fatto','Commento giuridico','Implicazioni'],'en':['The fact','Legal commentary','Implications'],
 'fr':['Le fait','Commentaire juridique','Implications'],'de':['Der Sachverhalt','Rechtlicher Kommentar','Konsequenzen'],
 'es':['El hecho','Comentario jurídico','Implicaciones'],'pt':['O facto','Comentário jurídico','Implicações'],
 'tr':['Olgu','Hukuki yorum','Sonuçlar'],'zh':['事实','法律评注','影响'],
 'ar':['الواقعة','تعليق قانوني','التبعات'],'he':['העובדה','פרשנות משפטית','השלכות'],
 'ru':['Факт','Правовой комментарий','Последствия'],
}

SD = {}

# ===================== IT =====================
SD['it'] = {
 'title':"Sudan: l'ONU avverte che l'offensiva su El-Obeid rischia nuovi crimini internazionali",
 'quote':"«Abbiamo già visto questo copione.» — Volker Türk, Alto Commissario ONU per i diritti umani",
 'labels':LABELS['it'],
 'bodies':[
  "Il 18 giugno 2026 l'Alto Commissario delle Nazioni Unite per i diritti umani, Volker Türk, ha avvertito che un'offensiva imminente delle Forze di Supporto Rapido (RSF) su El-Obeid, capoluogo del Nord Kordofan, rischia di provocare nuovi gravi crimini internazionali. La città, da oltre 18 mesi in condizioni d'assedio, è stata colpita da dieci giorni consecutivi di attacchi con droni — su depositi di carburante, centrali idriche ed elettriche — che hanno ucciso decine di civili; circa 500.000 persone, tra cui oltre 100.000 sfollati, sono a rischio. Türk ha richiamato un precedente diretto: «Abbiamo già visto questo copione… non possiamo permettere il ripetersi delle atrocità prevenibili documentate a El-Fasher e a Zamzam». A El-Fasher — ultima roccaforte dell'esercito (SAF) in Darfur, caduta alle RSF il 26 ottobre 2025 dopo un assedio di 18 mesi che vi aveva portato la carestia — la Missione d'inchiesta dell'ONU ha concluso, il 19 febbraio 2026, che la campagna delle RSF contro le comunità non-arabe Zaghawa e Fur presenta i tratti distintivi del genocidio. Il 20 giugno 2026 il Consiglio di Sicurezza ha intimato alle RSF di fermare l'assalto. Le RSF negano e si proclamano governo legittimo; il Sudan resta dilaniato dalla guerra tra SAF ed RSF scoppiata nell'aprile 2023, con quasi 14 milioni di sfollati.",
  "L'avvertimento poggia sul dovere di prevenire: la Convenzione sul Genocidio impegna gli Stati non solo a punire ma a prevenire, e Türk ha ricordato che gli Stati che hanno influenza hanno il dovere di esercitarla ora. Il quadro penale per il Darfur esiste da tempo: la Corte Penale Internazionale ha giurisdizione dal referral del Consiglio di Sicurezza del 2005 (ris. 1593); i mandati d'arresto per l'ex presidente al-Bashir risalgono al 2009-2010 e restano ineseguiti; e solo il 6 ottobre 2025 è arrivata la prima condanna per il Darfur, quella dell'ex capo Janjaweed Ali Kosheib, per crimini del 2003-04. Si aggiungono i crimini di guerra documentati dalla Missione ONU — la fame usata come arma, gli attacchi a ospedali e civili (IV Convenzione di Ginevra, Statuto di Roma). Sul «genocidio» va tenuta la distinzione: è un accertamento della Missione d'inchiesta dell'ONU e una determinazione del governo statunitense (gennaio 2025), non una sentenza di un tribunale; il ricorso che il Sudan aveva valutato contro gli Emirati alla Corte Internazionale di Giustizia è stato respinto per difetto di giurisdizione.",
  "Qui il diritto mostra il suo limite quando non viene applicato. El-Fasher è caduta sotto la più intensa documentazione internazionale — rapporti satellitari, sessioni del Consiglio di Sicurezza, una conclusione di genocidio — e tuttavia, come osservano gli analisti, gli avvertimenti hanno avuto peso normativo senza conseguenze operative: la stessa indagine che ha accertato il genocidio ha prodotto sanzioni contro tre comandanti RSF e nessuna cessazione delle ostilità. Ora il copione si ripete a El-Obeid. La coerenza impone di nominare tutti: le RSF, accusate di genocidio, massacri, stupri e fame d'assedio; ma anche la SAF, che lancia raid aerei su mercati civili, è stata sanzionata per uso di armi chimiche e ostacola gli aiuti; e gli enabler esterni — gli Emirati Arabi Uniti accusati di armare le RSF (cosa che negano), Egitto, Arabia Saudita, Qatar, Turchia e Iran dietro la SAF, e la Russia, che nel novembre 2024 ha posto il veto a una risoluzione ONU per l'accesso umanitario. È la più vasta crisi umanitaria e di sfollamento del pianeta, e tra le meno guardate. Il diritto per prevenire esiste; manca la volontà di applicarlo. Il diritto vale per tutti, o non vale per nessuno.",
 ]}

# ===================== EN =====================
SD['en'] = {
 'title':"Sudan: the UN warns that an offensive on El-Obeid risks new international crimes",
 'quote':"“We have seen this playbook before.” — Volker Türk, UN High Commissioner for Human Rights",
 'labels':LABELS['en'],
 'bodies':[
  "On 18 June 2026 the UN High Commissioner for Human Rights, Volker Türk, warned that an imminent offensive by the Rapid Support Forces (RSF) on El-Obeid, the capital of North Kordofan, risks fresh grave international crimes. The city, under siege-like conditions for more than 18 months, has been hit by ten consecutive days of drone strikes — on fuel depots, water and power stations — that have killed dozens of civilians; some 500,000 people, including over 100,000 displaced, are at risk. Türk invoked a direct precedent: “We have seen this playbook before… we cannot allow a repeat of the preventable atrocities we documented in El-Fasher and Zamzam.” In El-Fasher — the army's (SAF) last stronghold in Darfur, which fell to the RSF on 26 October 2025 after an 18-month siege that had brought famine — the UN Fact-Finding Mission concluded, on 19 February 2026, that the RSF campaign against the non-Arab Zaghawa and Fur communities bears the hallmarks of genocide. On 20 June 2026 the Security Council demanded that the RSF halt the assault. The RSF denies the accusations and proclaims itself a legitimate government; Sudan remains torn by the war between the SAF and the RSF that erupted in April 2023, with nearly 14 million displaced.",
  "The warning rests on the duty to prevent: the Genocide Convention binds States not only to punish but to prevent, and Türk recalled that States with influence have a duty to exercise it now. The criminal framework for Darfur has long existed: the International Criminal Court has had jurisdiction since the 2005 Security Council referral (res. 1593); the arrest warrants for former president al-Bashir date to 2009-2010 and remain unexecuted; and only on 6 October 2025 came the first Darfur conviction, that of former Janjaweed leader Ali Kosheib, for crimes committed in 2003-04. To these are added the war crimes documented by the UN Mission — starvation used as a weapon, attacks on hospitals and civilians (Fourth Geneva Convention, Rome Statute). On “genocide” the distinction must be kept: it is a finding of the UN Fact-Finding Mission and a determination by the United States government (January 2025), not a court judgment; the case Sudan had considered bringing against the Emirates before the International Court of Justice was dismissed for lack of jurisdiction.",
  "Here the law shows its limit when it is not applied. El-Fasher fell under the most intense international documentation — satellite reports, Security Council sessions, a finding of genocide — and yet, as analysts observe, the warnings carried normative weight without operational consequence: the very inquiry that found genocide produced sanctions against three RSF commanders and no cessation of hostilities. Now the playbook repeats at El-Obeid. Coherence requires naming everyone: the RSF, accused of genocide, massacres, rape and siege-starvation; but also the SAF, which launches airstrikes on civilian markets, has been sanctioned for using chemical weapons, and obstructs aid; and the external enablers — the United Arab Emirates, accused of arming the RSF (which it denies), Egypt, Saudi Arabia, Qatar, Turkey and Iran behind the SAF, and Russia, which in November 2024 vetoed a UN resolution on humanitarian access. It is the world's largest humanitarian and displacement crisis, and among the least watched. The law to prevent exists; the will to apply it is missing. The law applies to everyone, or it applies to no one.",
 ]}

# ===================== FR =====================
SD['fr'] = {
 'title':"Soudan : l'ONU avertit qu'une offensive sur El-Obeid risque de nouveaux crimes internationaux",
 'quote':"« Nous avons déjà vu ce scénario. » — Volker Türk, Haut-Commissaire de l'ONU aux droits de l'homme",
 'labels':LABELS['fr'],
 'bodies':[
  "Le 18 juin 2026, le Haut-Commissaire des Nations unies aux droits de l'homme, Volker Türk, a averti qu'une offensive imminente des Forces de soutien rapide (RSF) sur El-Obeid, chef-lieu du Nord-Kordofan, risque de provoquer de nouveaux crimes internationaux graves. La ville, en état de siège depuis plus de 18 mois, a subi dix jours consécutifs de frappes de drones — sur des dépôts de carburant, des stations d'eau et d'électricité — qui ont tué des dizaines de civils ; environ 500 000 personnes, dont plus de 100 000 déplacés, sont en danger. Türk a rappelé un précédent direct : « Nous avons déjà vu ce scénario… nous ne pouvons pas permettre la répétition des atrocités évitables documentées à El-Fasher et à Zamzam. » À El-Fasher — dernier bastion de l'armée (SAF) au Darfour, tombé aux mains des RSF le 26 octobre 2025 après un siège de 18 mois qui y avait apporté la famine — la Mission d'enquête de l'ONU a conclu, le 19 février 2026, que la campagne des RSF contre les communautés non arabes zaghawa et four présente les caractéristiques du génocide. Le 20 juin 2026, le Conseil de sécurité a sommé les RSF d'arrêter l'assaut. Les RSF nient et se proclament gouvernement légitime ; le Soudan reste déchiré par la guerre entre la SAF et les RSF déclenchée en avril 2023, avec près de 14 millions de déplacés.",
  "L'avertissement repose sur le devoir de prévenir : la Convention sur le génocide oblige les États non seulement à punir mais à prévenir, et Türk a rappelé que les États qui ont de l'influence ont le devoir de l'exercer maintenant. Le cadre pénal pour le Darfour existe de longue date : la Cour pénale internationale a compétence depuis le renvoi du Conseil de sécurité de 2005 (rés. 1593) ; les mandats d'arrêt contre l'ancien président al-Bachir remontent à 2009-2010 et restent inexécutés ; et c'est seulement le 6 octobre 2025 qu'est arrivée la première condamnation pour le Darfour, celle de l'ancien chef janjawid Ali Kosheib, pour des crimes de 2003-04. S'y ajoutent les crimes de guerre documentés par la Mission de l'ONU — la famine utilisée comme arme, les attaques contre des hôpitaux et des civils (IVe Convention de Genève, Statut de Rome). Sur le « génocide », la distinction doit être maintenue : c'est un constat de la Mission d'enquête de l'ONU et une qualification du gouvernement des États-Unis (janvier 2025), non un arrêt d'un tribunal ; la requête que le Soudan avait envisagée contre les Émirats devant la Cour internationale de Justice a été rejetée pour défaut de compétence.",
  "Ici le droit montre sa limite quand il n'est pas appliqué. El-Fasher est tombée sous la documentation internationale la plus intense — rapports satellitaires, sessions du Conseil de sécurité, un constat de génocide — et pourtant, comme l'observent les analystes, les avertissements ont eu un poids normatif sans conséquence opérationnelle : l'enquête même qui a constaté le génocide a produit des sanctions contre trois commandants RSF et aucune cessation des hostilités. Désormais le scénario se répète à El-Obeid. La cohérence impose de nommer tout le monde : les RSF, accusées de génocide, de massacres, de viols et de famine de siège ; mais aussi la SAF, qui lance des frappes aériennes sur des marchés civils, a été sanctionnée pour usage d'armes chimiques et entrave l'aide ; et les soutiens extérieurs — les Émirats arabes unis, accusés d'armer les RSF (ce qu'ils nient), l'Égypte, l'Arabie saoudite, le Qatar, la Turquie et l'Iran derrière la SAF, et la Russie, qui en novembre 2024 a opposé son veto à une résolution de l'ONU sur l'accès humanitaire. C'est la plus vaste crise humanitaire et de déplacement de la planète, et l'une des moins regardées. Le droit pour prévenir existe ; la volonté de l'appliquer manque. Le droit vaut pour tous, ou il ne vaut pour personne.",
 ]}

# ===================== DE =====================
SD['de'] = {
 'title':"Sudan: Die UNO warnt, dass eine Offensive auf El-Obeid neue internationale Verbrechen riskiert",
 'quote':"„Wir haben dieses Drehbuch schon gesehen.“ — Volker Türk, UN-Hochkommissar für Menschenrechte",
 'labels':LABELS['de'],
 'bodies':[
  "Am 18. Juni 2026 warnte der UN-Hochkommissar für Menschenrechte, Volker Türk, dass eine bevorstehende Offensive der Rapid Support Forces (RSF) auf El-Obeid, die Hauptstadt von Nord-Kordofan, neue schwere internationale Verbrechen riskiert. Die Stadt, seit mehr als 18 Monaten unter belagerungsähnlichen Bedingungen, wurde von zehn aufeinanderfolgenden Tagen mit Drohnenangriffen getroffen — auf Treibstofflager, Wasser- und Kraftwerke —, die Dutzende Zivilisten töteten; etwa 500.000 Menschen, darunter über 100.000 Vertriebene, sind in Gefahr. Türk berief sich auf einen direkten Präzedenzfall: „Wir haben dieses Drehbuch schon gesehen… wir dürfen die Wiederholung der vermeidbaren Gräueltaten, die wir in El-Fasher und Zamzam dokumentiert haben, nicht zulassen.“ In El-Fasher — der letzten Hochburg der Armee (SAF) in Darfur, die am 26. Oktober 2025 nach einer 18-monatigen Belagerung, die Hungersnot gebracht hatte, an die RSF fiel — kam die UN-Untersuchungsmission am 19. Februar 2026 zu dem Schluss, dass die Kampagne der RSF gegen die nicht-arabischen Gemeinschaften der Zaghawa und Fur die Merkmale eines Völkermords trägt. Am 20. Juni 2026 forderte der Sicherheitsrat die RSF auf, den Angriff einzustellen. Die RSF bestreiten dies und erklären sich zur legitimen Regierung; Sudan bleibt zerrissen von dem im April 2023 ausgebrochenen Krieg zwischen SAF und RSF, mit fast 14 Millionen Vertriebenen.",
  "Die Warnung beruht auf der Pflicht zur Verhütung: die Völkermordkonvention verpflichtet die Staaten nicht nur zu bestrafen, sondern zu verhüten, und Türk erinnerte daran, dass Staaten mit Einfluss die Pflicht haben, ihn jetzt auszuüben. Der strafrechtliche Rahmen für Darfur besteht seit Langem: der Internationale Strafgerichtshof ist seit der Überweisung durch den Sicherheitsrat 2005 zuständig (Res. 1593); die Haftbefehle gegen Ex-Präsident al-Bashir stammen von 2009-2010 und bleiben unvollstreckt; und erst am 6. Oktober 2025 kam die erste Verurteilung für Darfur, die des früheren Janjaweed-Anführers Ali Kosheib, für Verbrechen von 2003-04. Hinzu kommen die von der UN-Mission dokumentierten Kriegsverbrechen — Hunger als Waffe, Angriffe auf Krankenhäuser und Zivilisten (IV. Genfer Abkommen, Römisches Statut). Beim „Völkermord“ ist die Unterscheidung zu wahren: es ist eine Feststellung der UN-Untersuchungsmission und eine Einstufung der US-Regierung (Januar 2025), kein Urteil eines Gerichts; die Klage, die Sudan gegen die Emirate vor dem Internationalen Gerichtshof erwogen hatte, wurde mangels Zuständigkeit abgewiesen.",
  "Hier zeigt das Recht seine Grenze, wenn es nicht angewandt wird. El-Fasher fiel unter der intensivsten internationalen Dokumentation — Satellitenberichte, Sitzungen des Sicherheitsrats, eine Völkermordfeststellung — und doch hatten die Warnungen, wie Analysten anmerken, normatives Gewicht ohne operative Konsequenz: dieselbe Untersuchung, die den Völkermord feststellte, brachte Sanktionen gegen drei RSF-Kommandeure und keine Einstellung der Feindseligkeiten. Nun wiederholt sich das Drehbuch in El-Obeid. Kohärenz verlangt, alle zu benennen: die RSF, beschuldigt des Völkermords, von Massakern, Vergewaltigungen und Belagerungshunger; aber auch die SAF, die Luftangriffe auf zivile Märkte fliegt, für den Einsatz chemischer Waffen sanktioniert wurde und Hilfe behindert; und die externen Unterstützer — die Vereinigten Arabischen Emirate, beschuldigt, die RSF zu bewaffnen (was sie bestreiten), Ägypten, Saudi-Arabien, Katar, die Türkei und Iran hinter der SAF, und Russland, das im November 2024 ein Veto gegen eine UN-Resolution zum humanitären Zugang einlegte. Es ist die größte humanitäre und Vertreibungskrise der Welt, und eine der am wenigsten beachteten. Das Recht zur Verhütung besteht; der Wille, es anzuwenden, fehlt. Das Recht gilt für alle, oder es gilt für niemanden.",
 ]}

# ===================== ES =====================
SD['es'] = {
 'title':"Sudán: la ONU advierte que una ofensiva sobre El-Obeid arriesga nuevos crímenes internacionales",
 'quote':"«Ya hemos visto este guion.» — Volker Türk, Alto Comisionado de la ONU para los Derechos Humanos",
 'labels':LABELS['es'],
 'bodies':[
  "El 18 de junio de 2026 el Alto Comisionado de las Naciones Unidas para los Derechos Humanos, Volker Türk, advirtió que una ofensiva inminente de las Fuerzas de Apoyo Rápido (RSF) sobre El-Obeid, capital de Kordofán del Norte, arriesga nuevos crímenes internacionales graves. La ciudad, en condiciones de asedio desde hace más de 18 meses, ha sido golpeada por diez días consecutivos de ataques con drones — sobre depósitos de combustible, estaciones de agua y electricidad — que han matado a decenas de civiles; unas 500.000 personas, entre ellas más de 100.000 desplazados, están en riesgo. Türk evocó un precedente directo: «Ya hemos visto este guion… no podemos permitir la repetición de las atrocidades evitables que documentamos en El-Fasher y en Zamzam». En El-Fasher — último bastión del ejército (SAF) en Darfur, caído ante las RSF el 26 de octubre de 2025 tras un asedio de 18 meses que había traído la hambruna — la Misión de investigación de la ONU concluyó, el 19 de febrero de 2026, que la campaña de las RSF contra las comunidades no árabes zaghawa y fur presenta los rasgos del genocidio. El 20 de junio de 2026 el Consejo de Seguridad conminó a las RSF a detener el asalto. Las RSF niegan y se proclaman gobierno legítimo; Sudán sigue desgarrado por la guerra entre la SAF y las RSF estallada en abril de 2023, con casi 14 millones de desplazados.",
  "La advertencia se apoya en el deber de prevenir: la Convención sobre el Genocidio obliga a los Estados no solo a castigar sino a prevenir, y Türk recordó que los Estados con influencia tienen el deber de ejercerla ahora. El marco penal para Darfur existe desde hace tiempo: la Corte Penal Internacional tiene jurisdicción desde la remisión del Consejo de Seguridad de 2005 (res. 1593); las órdenes de arresto contra el expresidente al-Bashir datan de 2009-2010 y siguen sin ejecutarse; y solo el 6 de octubre de 2025 llegó la primera condena por Darfur, la del exjefe yanyauid Ali Kosheib, por crímenes de 2003-04. A ello se suman los crímenes de guerra documentados por la Misión de la ONU — el hambre usada como arma, los ataques a hospitales y civiles (IV Convenio de Ginebra, Estatuto de Roma). Sobre el «genocidio» debe mantenerse la distinción: es una constatación de la Misión de investigación de la ONU y una determinación del gobierno de Estados Unidos (enero de 2025), no una sentencia de un tribunal; la demanda que Sudán había considerado contra los Emiratos ante la Corte Internacional de Justicia fue desestimada por falta de jurisdicción.",
  "Aquí el derecho muestra su límite cuando no se aplica. El-Fasher cayó bajo la documentación internacional más intensa — informes satelitales, sesiones del Consejo de Seguridad, una conclusión de genocidio — y, sin embargo, como observan los analistas, las advertencias tuvieron peso normativo sin consecuencia operativa: la misma investigación que constató el genocidio produjo sanciones contra tres comandantes RSF y ninguna cesación de las hostilidades. Ahora el guion se repite en El-Obeid. La coherencia obliga a nombrar a todos: las RSF, acusadas de genocidio, masacres, violaciones y hambre de asedio; pero también la SAF, que lanza ataques aéreos sobre mercados civiles, ha sido sancionada por uso de armas químicas y obstaculiza la ayuda; y los facilitadores externos — los Emiratos Árabes Unidos, acusados de armar a las RSF (lo que niegan), Egipto, Arabia Saudí, Catar, Turquía e Irán detrás de la SAF, y Rusia, que en noviembre de 2024 vetó una resolución de la ONU sobre el acceso humanitario. Es la mayor crisis humanitaria y de desplazamiento del planeta, y de las menos observadas. El derecho para prevenir existe; falta la voluntad de aplicarlo. El derecho vale para todos, o no vale para nadie.",
 ]}

# ===================== PT =====================
SD['pt'] = {
 'title':"Sudão: a ONU alerta que uma ofensiva sobre El-Obeid arrisca novos crimes internacionais",
 'quote':"«Já vimos este guião.» — Volker Türk, Alto-Comissário da ONU para os Direitos Humanos",
 'labels':LABELS['pt'],
 'bodies':[
  "Em 18 de junho de 2026 o Alto-Comissário das Nações Unidas para os Direitos Humanos, Volker Türk, alertou que uma ofensiva iminente das Forças de Apoio Rápido (RSF) sobre El-Obeid, capital do Kordofan do Norte, arrisca novos crimes internacionais graves. A cidade, em condições de cerco há mais de 18 meses, foi atingida por dez dias consecutivos de ataques com drones — sobre depósitos de combustível, estações de água e de eletricidade — que mataram dezenas de civis; cerca de 500.000 pessoas, entre elas mais de 100.000 deslocados, estão em risco. Türk evocou um precedente direto: «Já vimos este guião… não podemos permitir a repetição das atrocidades evitáveis que documentámos em El-Fasher e em Zamzam». Em El-Fasher — último bastião do exército (SAF) no Darfur, caído perante as RSF em 26 de outubro de 2025 após um cerco de 18 meses que ali trouxera a fome — a Missão de inquérito da ONU concluiu, a 19 de fevereiro de 2026, que a campanha das RSF contra as comunidades não árabes zaghawa e fur apresenta os traços do genocídio. Em 20 de junho de 2026 o Conselho de Segurança intimou as RSF a parar o assalto. As RSF negam e proclamam-se governo legítimo; o Sudão continua dilacerado pela guerra entre a SAF e as RSF deflagrada em abril de 2023, com quase 14 milhões de deslocados.",
  "O alerta assenta no dever de prevenir: a Convenção sobre o Genocídio obriga os Estados não só a punir mas a prevenir, e Türk recordou que os Estados com influência têm o dever de a exercer agora. O quadro penal para o Darfur existe há muito: o Tribunal Penal Internacional tem jurisdição desde a remessa do Conselho de Segurança de 2005 (res. 1593); os mandados de detenção contra o ex-presidente al-Bashir datam de 2009-2010 e permanecem por executar; e só a 6 de outubro de 2025 chegou a primeira condenação pelo Darfur, a do antigo chefe janjaweed Ali Kosheib, por crimes de 2003-04. A estes somam-se os crimes de guerra documentados pela Missão da ONU — a fome usada como arma, os ataques a hospitais e civis (IV Convenção de Genebra, Estatuto de Roma). Sobre o «genocídio» deve manter-se a distinção: é uma constatação da Missão de inquérito da ONU e uma determinação do governo dos Estados Unidos (janeiro de 2025), não uma sentença de um tribunal; a ação que o Sudão ponderara contra os Emirados perante o Tribunal Internacional de Justiça foi rejeitada por falta de jurisdição.",
  "Aqui o direito mostra o seu limite quando não é aplicado. El-Fasher caiu sob a mais intensa documentação internacional — relatórios de satélite, sessões do Conselho de Segurança, uma conclusão de genocídio — e, no entanto, como observam os analistas, os alertas tiveram peso normativo sem consequência operacional: a própria investigação que constatou o genocídio produziu sanções contra três comandantes RSF e nenhuma cessação das hostilidades. Agora o guião repete-se em El-Obeid. A coerência obriga a nomear todos: as RSF, acusadas de genocídio, massacres, violações e fome de cerco; mas também a SAF, que lança ataques aéreos sobre mercados civis, foi sancionada por uso de armas químicas e obstrui a ajuda; e os facilitadores externos — os Emirados Árabes Unidos, acusados de armar as RSF (o que negam), Egito, Arábia Saudita, Catar, Turquia e Irão atrás da SAF, e a Rússia, que em novembro de 2024 vetou uma resolução da ONU sobre o acesso humanitário. É a maior crise humanitária e de deslocamento do planeta, e das menos observadas. O direito para prevenir existe; falta a vontade de o aplicar. O direito vale para todos, ou não vale para ninguém.",
 ]}

# ===================== TR =====================
SD['tr'] = {
 'title':"Sudan: BM, El-Obeid'e yönelik bir saldırının yeni uluslararası suçları riske attığı konusunda uyardı",
 'quote':"«Bu senaryoyu daha önce gördük.» — Volker Türk, BM İnsan Hakları Yüksek Komiseri",
 'labels':LABELS['tr'],
 'bodies':[
  "18 Haziran 2026'da BM İnsan Hakları Yüksek Komiseri Volker Türk, Hızlı Destek Kuvvetleri'nin (RSF) Kuzey Kordofan'ın başkenti El-Obeid'e yönelik yakın bir saldırısının yeni ağır uluslararası suçları riske attığı konusunda uyardı. 18 aydan uzun süredir kuşatma benzeri koşullardaki kent, yakıt depolarına, su ve elektrik santrallerine on gün üst üste süren insansız hava aracı saldırılarıyla vuruldu; bu saldırılar onlarca sivili öldürdü; 100.000'den fazla yerinden edilmiş kişi dahil yaklaşık 500.000 kişi risk altında. Türk doğrudan bir emsale başvurdu: «Bu senaryoyu daha önce gördük… El-Fasher ve Zamzam'da belgelediğimiz önlenebilir vahşetin tekrarına izin veremeyiz.» El-Fasher'de — ordunun (SAF) Darfur'daki son kalesi, 18 aylık ve kıtlığı getiren bir kuşatmanın ardından 26 Ekim 2025'te RSF'ye düştü — BM Araştırma Misyonu, 19 Şubat 2026'da, RSF'nin Arap olmayan Zaghawa ve Fur topluluklarına yönelik kampanyasının soykırımın tanımlayıcı izlerini taşıdığı sonucuna vardı. 20 Haziran 2026'da Güvenlik Konseyi RSF'ye saldırıyı durdurma çağrısı yaptı. RSF reddediyor ve kendini meşru hükûmet ilan ediyor; Sudan, Nisan 2023'te patlak veren SAF–RSF savaşıyla parçalanmış durumda ve neredeyse 14 milyon kişi yerinden edilmiş.",
  "Uyarı, önleme yükümlülüğüne dayanır: Soykırım Sözleşmesi devletleri yalnızca cezalandırmaya değil önlemeye de bağlar ve Türk, nüfuz sahibi devletlerin bu nüfuzu şimdi kullanma görevi olduğunu hatırlattı. Darfur için ceza çerçevesi uzun süredir mevcut: Uluslararası Ceza Mahkemesi, 2005 Güvenlik Konseyi havalesinden (karar 1593) bu yana yetkili; eski cumhurbaşkanı el-Beşir hakkındaki tutuklama emirleri 2009-2010'a dayanıyor ve hâlâ infaz edilmedi; ve Darfur için ilk mahkûmiyet ancak 6 Ekim 2025'te geldi — eski Cancavid lideri Ali Koşeyb'inki, 2003-04 suçlarından. Bunlara BM Misyonu'nun belgelediği savaş suçları eklenir — silah olarak kullanılan açlık, hastane ve sivillere saldırılar (IV. Cenevre Sözleşmesi, Roma Statüsü). «Soykırım» konusunda ayrım korunmalıdır: bu, BM Araştırma Misyonu'nun bir tespiti ve ABD hükûmetinin bir nitelendirmesidir (Ocak 2025), bir mahkemenin hükmü değil; Sudan'ın Birleşik Arap Emirlikleri aleyhine Uluslararası Adalet Divanı önünde değerlendirdiği dava yetki yokluğundan reddedildi.",
  "Burada hukuk, uygulanmadığında sınırını gösterir. El-Fasher en yoğun uluslararası belgeleme altında düştü — uydu raporları, Güvenlik Konseyi oturumları, bir soykırım tespiti — yine de, analistlerin gözlemlediği gibi, uyarılar operasyonel sonuç doğurmayan normatif bir ağırlık taşıdı: soykırımı tespit eden aynı soruşturma, üç RSF komutanına yaptırım üretti ve hiçbir çatışma durdurma getirmedi. Şimdi senaryo El-Obeid'de tekrarlanıyor. Tutarlılık herkesin adını koymayı gerektirir: soykırım, katliam, tecavüz ve kuşatma açlığıyla suçlanan RSF; ama aynı zamanda sivil pazarlara hava saldırıları düzenleyen, kimyasal silah kullanımı nedeniyle yaptırıma uğrayan ve yardımı engelleyen SAF; ve dış destekçiler — RSF'yi silahlandırmakla suçlanan (kabul etmedikleri) Birleşik Arap Emirlikleri, SAF'ın arkasındaki Mısır, Suudi Arabistan, Katar, Türkiye ve İran, ve Kasım 2024'te insani erişime ilişkin bir BM kararını veto eden Rusya. Bu, gezegenin en büyük insani ve yerinden edilme kriz, ve en az izlenenlerinden biri. Önlemek için hukuk var; uygulama iradesi yok. Hukuk herkes için geçerlidir ya da hiç kimse için.",
 ]}

# ===================== ZH =====================
SD['zh'] = {
 'title':"苏丹：联合国警告，对欧贝伊德的攻势可能带来新的国际罪行",
 'quote':"“我们以前见过这套剧本。” —— 联合国人权事务高级专员沃尔克·蒂尔克",
 'labels':LABELS['zh'],
 'bodies':[
  "2026年6月18日，联合国人权事务高级专员沃尔克·蒂尔克警告说，快速支援部队（RSF）对北科尔多凡州首府欧贝伊德即将发动的攻势，可能带来新的严重国际罪行。这座城市处于围困状态已逾18个月，连续十天遭到无人机袭击——目标是燃料库、供水站和发电站——造成数十名平民死亡；约50万人面临危险，其中包括逾10万名流离失所者。蒂尔克援引了一个直接先例：“我们以前见过这套剧本……我们不能允许在法希尔和扎姆扎姆所记录的、本可预防的暴行重演。”在法希尔——军队（SAF）在达尔富尔的最后据点，在长达18个月、带来饥荒的围困之后，于2025年10月26日落入RSF之手——联合国实况调查团于2026年2月19日得出结论：RSF针对非阿拉伯的扎加瓦和富尔社群的行动，带有种族灭绝的标志性特征。2026年6月20日，安理会要求RSF停止攻击。RSF予以否认，并自称合法政府；苏丹仍因2023年4月爆发的SAF与RSF之间的战争而四分五裂，近1400万人流离失所。",
  "这一警告立足于预防义务：《灭绝种族公约》要求各国不仅要惩治、更要预防，蒂尔克提醒说，拥有影响力的国家有义务现在就行使这种影响力。针对达尔富尔的刑事框架早已存在：国际刑事法院自2005年安理会移交（第1593号决议）以来即拥有管辖权；针对前总统巴希尔的逮捕令可追溯至2009-2010年，至今仍未执行；而针对达尔富尔的首次定罪迟至2025年10月6日才到来——即对前金戈威德首领阿里·库赛卜2003-04年罪行的定罪。此外还有联合国调查团记录的战争罪——把饥饿当作武器、对医院和平民的袭击（《日内瓦第四公约》《罗马规约》）。关于“种族灭绝”，必须保持区分：这是联合国实况调查团的认定与美国政府的定性（2025年1月），而非法院的判决；苏丹曾考虑就阿联酋向国际法院提起的诉讼，因缺乏管辖权而被驳回。",
  "在此，法律在不被适用时显出其界限。法希尔是在最密集的国际记录之下陷落的——卫星报告、安理会会议、一项种族灭绝的认定——然而正如分析人士所言，这些警告只有规范上的分量、却无行动上的后果：正是认定了种族灭绝的那项调查，只换来对三名RSF指挥官的制裁，而敌对行动并未停止。如今同样的剧本在欧贝伊德重演。一致性要求点出所有人：被指控犯有种族灭绝、屠杀、强奸与围困致饥的RSF；但也有对平民市场发动空袭、因使用化学武器而受制裁、并阻碍援助的SAF；以及外部支持者——被指控武装RSF（其予以否认）的阿联酋，SAF背后的埃及、沙特、卡塔尔、土耳其和伊朗，以及2024年11月否决了一项关于人道准入的联合国决议的俄罗斯。这是地球上规模最大、却最少被注视的人道主义与流离失所危机之一。用以预防的法律是存在的；缺的是适用它的意愿。法律要么对所有人适用，要么对任何人都不适用。",
 ]}

# ===================== AR =====================
SD['ar'] = {
 'title':"السودان: الأمم المتحدة تحذّر من أن هجوماً على الأُبيّض يهدّد بجرائم دولية جديدة",
 'quote':"«لقد رأينا هذا السيناريو من قبل.» — فولكر تورك، المفوّض السامي للأمم المتحدة لحقوق الإنسان",
 'labels':LABELS['ar'],
 'bodies':[
  "في 18 يونيو 2026 حذّر المفوّض السامي للأمم المتحدة لحقوق الإنسان، فولكر تورك، من أن هجوماً وشيكاً لقوات الدعم السريع (RSF) على الأُبيّض، عاصمة شمال كردفان، يهدّد بارتكاب جرائم دولية خطيرة جديدة. فالمدينة، التي تعيش أوضاعاً شبيهة بالحصار منذ أكثر من 18 شهراً، تعرّضت لعشرة أيام متتالية من هجمات الطائرات المسيّرة — على مستودعات الوقود ومحطات المياه والكهرباء — أوقعت عشرات القتلى المدنيين؛ ونحو 500 ألف شخص، بينهم أكثر من 100 ألف نازح، في خطر. واستحضر تورك سابقة مباشرة: «لقد رأينا هذا السيناريو من قبل… لا يمكننا السماح بتكرار الفظائع التي كان بالإمكان منعها والتي وثّقناها في الفاشر وزمزم». وفي الفاشر — آخر معاقل الجيش (SAF) في دارفور، التي سقطت بيد الدعم السريع في 26 أكتوبر 2025 بعد حصار دام 18 شهراً جلب المجاعة — خلصت بعثة تقصّي الحقائق التابعة للأمم المتحدة، في 19 فبراير 2026، إلى أن حملة الدعم السريع ضد جماعتَي الزغاوة والفور غير العربيتين تحمل السمات المميِّزة للإبادة الجماعية. وفي 20 يونيو 2026 طالب مجلس الأمن الدعم السريع بوقف الهجوم. ينفي الدعم السريع ويعلن نفسه حكومةً شرعية؛ ويظل السودان ممزّقاً بالحرب بين الجيش والدعم السريع التي اندلعت في أبريل 2023، مع نحو 14 مليون نازح.",
  "يستند التحذير إلى واجب المنع: فاتفاقية منع الإبادة الجماعية تُلزم الدول لا بالمعاقبة فحسب بل بالمنع، وذكّر تورك بأن على الدول ذات النفوذ واجب ممارسته الآن. والإطار الجنائي لدارفور قائم منذ زمن: فالمحكمة الجنائية الدولية لها اختصاص منذ إحالة مجلس الأمن عام 2005 (القرار 1593)؛ ومذكّرات توقيف الرئيس السابق البشير تعود إلى 2009-2010 وتبقى غير منفّذة؛ ولم تأتِ أول إدانة بشأن دارفور إلا في 6 أكتوبر 2025 — إدانة زعيم الجنجويد السابق علي كوشيب عن جرائم 2003-04. يُضاف إلى ذلك جرائم الحرب التي وثّقتها بعثة الأمم المتحدة — التجويع المستخدَم سلاحاً، والهجمات على المستشفيات والمدنيين (اتفاقية جنيف الرابعة، نظام روما الأساسي). وبشأن «الإبادة الجماعية» يجب الإبقاء على التمييز: إنها استنتاج لبعثة تقصّي الحقائق التابعة للأمم المتحدة وتوصيف من حكومة الولايات المتحدة (يناير 2025)، لا حكم محكمة؛ أما الدعوى التي كان السودان قد فكّر في رفعها ضد الإمارات أمام محكمة العدل الدولية فقد رُفضت لانتفاء الاختصاص.",
  "هنا يُظهر القانون حدوده حين لا يُطبَّق. سقطت الفاشر تحت أكثف توثيق دولي — تقارير الأقمار الاصطناعية وجلسات مجلس الأمن واستنتاج بوقوع إبادة جماعية — ومع ذلك، كما يلاحظ المحلّلون، كان للتحذيرات ثقل معياري بلا أثر عملي: فالتحقيق نفسه الذي أثبت الإبادة لم يُنتج سوى عقوبات على ثلاثة من قادة الدعم السريع، دون أي وقف للأعمال العدائية. والآن يتكرّر السيناريو في الأُبيّض. ويفرض الاتساق تسمية الجميع: الدعم السريع، المتّهم بالإبادة الجماعية والمجازر والاغتصاب وتجويع الحصار؛ لكن أيضاً الجيش (SAF)، الذي يشنّ غارات جوية على أسواق مدنية، وعوقب لاستخدامه أسلحة كيميائية، ويعرقل المساعدات؛ والداعمون الخارجيون — الإمارات العربية المتحدة المتّهمة بتسليح الدعم السريع (وهو ما تنفيه)، ومصر والسعودية وقطر وتركيا وإيران خلف الجيش، وروسيا التي استخدمت في نوفمبر 2024 حق النقض ضد قرار أممي بشأن وصول المساعدات. إنها أوسع أزمة إنسانية ونزوح على الكوكب، ومن أقلّها متابعةً. القانون الذي يَمنع موجود؛ ما ينقص هو إرادة تطبيقه. القانون يسري على الجميع، أو لا يسري على أحد.",
 ]}

# ===================== HE =====================
SD['he'] = {
 'title':"סודאן: האו״ם מזהיר שמתקפה על אל-אוביד מסכנת פשעים בינלאומיים חדשים",
 'quote':"»כבר ראינו את התסריט הזה.« — פולקר טירק, הנציב העליון של האו״ם לזכויות אדם",
 'labels':LABELS['he'],
 'bodies':[
  "ב-18 ביוני 2026 הזהיר הנציב העליון של האו״ם לזכויות אדם, פולקר טירק, כי מתקפה קרֵבה של כוחות התמיכה המהירה (RSF) על אל-אוביד, בירת צפון קורדופן, מסכנת פשעים בינלאומיים חמורים חדשים. העיר, הנתונה בתנאי מצור זה יותר מ-18 חודשים, נפגעה מעשרה ימים רצופים של תקיפות כטב״מים — על מאגרי דלק, תחנות מים וחשמל — שהרגו עשרות אזרחים; כ-500,000 בני אדם, ובהם יותר מ-100,000 עקורים, בסכנה. טירק הזכיר תקדים ישיר: »כבר ראינו את התסריט הזה… איננו יכולים להרשות את חזרת הזוועות הניתנות למניעה שתיעדנו באל-פאשר ובזמזם.« באל-פאשר — מעוז הצבא (SAF) האחרון בדארפור, שנפל לידי ה-RSF ב-26 באוקטובר 2025 לאחר מצור בן 18 חודשים שהביא עמו רעב — קבעה משלחת החקירה של האו״ם, ב-19 בפברואר 2026, כי מסע ה-RSF נגד הקהילות הלא-ערביות זע׳אווה ופור נושא את סימני ההיכר של רצח עם. ב-20 ביוני 2026 דרשה מועצת הביטחון מה-RSF להפסיק את ההסתערות. ה-RSF מכחישים ומכריזים על עצמם כממשלה לגיטימית; סודאן נותרת קרועה במלחמה בין ה-SAF ל-RSF שפרצה באפריל 2023, עם כ-14 מיליון עקורים.",
  "האזהרה נשענת על חובת המניעה: אמנת מניעת רצח העם מחייבת את המדינות לא רק להעניש אלא למנוע, וטירק הזכיר כי על מדינות בעלות השפעה מוטלת החובה להפעילה עכשיו. המסגרת הפלילית לדארפור קיימת זה מכבר: לבית הדין הפלילי הבינלאומי יש סמכות מאז הפניית מועצת הביטחון ב-2005 (החלטה 1593); צווי המעצר נגד הנשיא לשעבר אל-בשיר הם משנת 2009-2010 ונותרו בלתי מבוצעים; ורק ב-6 באוקטובר 2025 הגיעה ההרשעה הראשונה בעניין דארפור — זו של מנהיג הג׳נג׳וויד לשעבר עלי קושייב, על פשעים מ-2003-04. לאלה מתווספים פשעי המלחמה שתיעדה משלחת האו״ם — הרעבה כנשק, תקיפות על בתי חולים ואזרחים (אמנת ז׳נבה הרביעית, חוקת רומא). באשר ל»רצח עם« יש לשמור על ההבחנה: זו קביעה של משלחת החקירה של האו״ם והגדרה של ממשלת ארצות הברית (ינואר 2025), לא פסק דין של בית משפט; התביעה ששקלה סודאן נגד איחוד האמירויות בפני בית הדין הבינלאומי לצדק נדחתה מחוסר סמכות.",
  "כאן מראה הדין את גבולו כשאינו מיושם. אל-פאשר נפלה תחת התיעוד הבינלאומי הצפוף ביותר — דוחות לוויין, ישיבות מועצת הביטחון, קביעת רצח עם — ובכל זאת, כפי שמציינים אנליסטים, לאזהרות היה משקל נורמטיבי בלא תוצאה מעשית: אותה חקירה עצמה שקבעה רצח עם הפיקה סנקציות נגד שלושה ממפקדי ה-RSF ושום הפסקת לחימה. כעת התסריט חוזר באל-אוביד. העקביות מחייבת לנקוב בשם כולם: ה-RSF, המואשמים ברצח עם, בטבח, באונס וברעב מצור; אך גם ה-SAF, המבצע תקיפות אוויר על שווקים אזרחיים, הוטלו עליו סנקציות על שימוש בנשק כימי, והוא מכשיל סיוע; והמאפשרים החיצוניים — איחוד האמירויות, המואשם בחימוש ה-RSF (דבר שהוא מכחיש), מצרים, ערב הסעודית, קטר, טורקיה ואיראן מאחורי ה-SAF, ורוסיה, שבנובמבר 2024 הטילה וטו על החלטת או״ם בדבר גישה הומניטרית. זהו משבר ההומניטרי והעקירה הגדול בעולם, ומן הפחות נצפים. הדין שנועד למנוע קיים; חסר הרצון ליישמו. הדין חל על הכול, או שאינו חל על איש.",
 ]}

# ===================== RU =====================
SD['ru'] = {
 'title':"Судан: ООН предупреждает, что наступление на Эль-Обейд грозит новыми международными преступлениями",
 'quote':"«Мы уже видели этот сценарий.» — Фолькер Тюрк, Верховный комиссар ООН по правам человека",
 'labels':LABELS['ru'],
 'bodies':[
  "18 июня 2026 года Верховный комиссар ООН по правам человека Фолькер Тюрк предупредил, что неминуемое наступление Сил быстрой поддержки (СБП, RSF) на Эль-Обейд, административный центр Северного Кордофана, грозит новыми тяжкими международными преступлениями. Город, более 18 месяцев находящийся в условиях, близких к осаде, десять дней подряд подвергался ударам беспилотников — по топливным складам, водо- и электростанциям, — в результате чего погибли десятки мирных жителей; под угрозой около 500 000 человек, в том числе более 100 000 перемещённых лиц. Тюрк сослался на прямой прецедент: «Мы уже видели этот сценарий… мы не можем допустить повторения предотвратимых злодеяний, которые мы задокументировали в Эль-Фашире и в лагере Замзам». В Эль-Фашире — последнем оплоте армии (СВС, SAF) в Дарфуре, павшем перед СБП 26 октября 2025 года после 18-месячной осады, принёсшей голод, — Миссия ООН по установлению фактов 19 февраля 2026 года заключила, что кампания СБП против неарабских общин загава и фур несёт характерные признаки геноцида. 20 июня 2026 года Совет Безопасности потребовал от СБП прекратить штурм. СБП всё отрицают и провозглашают себя законным правительством; Судан остаётся раздираемым войной между СВС и СБП, вспыхнувшей в апреле 2023 года, с почти 14 миллионами перемещённых лиц.",
  "Предупреждение опирается на обязанность предупреждать: Конвенция о геноциде обязывает государства не только наказывать, но и предупреждать, и Тюрк напомнил, что у государств, обладающих влиянием, есть обязанность применить его сейчас. Уголовные рамки для Дарфура существуют давно: Международный уголовный суд обладает юрисдикцией с момента передачи Советом Безопасности в 2005 году (резолюция 1593); ордера на арест бывшего президента аль-Башира выданы в 2009-2010 годах и остаются неисполненными; и лишь 6 октября 2025 года вынесен первый приговор по Дарфуру — бывшему главарю «джанджавид» Али Кушайбу за преступления 2003-04 годов. К этому добавляются военные преступления, задокументированные Миссией ООН, — голод как оружие, удары по больницам и гражданским (IV Женевская конвенция, Римский статут). В отношении «геноцида» следует сохранять различие: это вывод Миссии ООН по установлению фактов и квалификация правительства США (январь 2025 года), а не решение суда; иск, который Судан намеревался подать против Эмиратов в Международный Суд, был отклонён за отсутствием юрисдикции.",
  "Здесь право обнаруживает свой предел, когда не применяется. Эль-Фашир пал под самым плотным международным документированием — спутниковые отчёты, заседания Совета Безопасности, вывод о геноциде — и всё же, как отмечают аналитики, предупреждения имели нормативный вес без оперативных последствий: то самое расследование, что установило геноцид, обернулось санкциями против трёх командиров СБП и никаким прекращением боёв. Теперь сценарий повторяется в Эль-Обейде. Последовательность требует назвать всех: СБП, обвиняемые в геноциде, массовых убийствах, изнасилованиях и голоде осады; но также СВС, которые наносят авиаудары по гражданским рынкам, попали под санкции за применение химического оружия и препятствуют помощи; и внешние пособники — Объединённые Арабские Эмираты, обвиняемые в вооружении СБП (что они отрицают), Египет, Саудовская Аравия, Катар, Турция и Иран за СВС, и Россия, которая в ноябре 2024 года наложила вето на резолюцию ООН о гуманитарном доступе. Это крупнейший в мире гуманитарный кризис и кризис перемещения — и один из наименее замечаемых. Право, призванное предупреждать, существует; недостаёт воли его применять. Право действует для всех или ни для кого.",
 ]}

TAGS = ['Sudan','Genocidio','Fame e carestia','ONU','Diritto internazionale']
